//! The cross-language conformance fixture set.
//!
//! The instants are chosen, not sampled: each one is a moment where the screen
//! shows something a parser is supposed to understand. They are the same seven
//! recordings and the same eleven instants the Swift golden suite already
//! pins, so this is not a new claim — it is the existing claim, made in three
//! languages at once.
//!
//! Times are integer milliseconds. The Swift goldens name them in seconds;
//! 13.5 s is 13500 ms and nothing about the frame changes, but an integer
//! removes float formatting from the comparison entirely.

/// `(cast, instant label, time in milliseconds, what this instant exercises)`
pub const INSTANTS: &[(&str, &str, i64, &str)] = &[
    (
        "claude-basic-turn",
        "thinking",
        8500,
        "working indicator with no elapsed time yet, empty composer",
    ),
    (
        "claude-basic-turn",
        "tool-running",
        11000,
        "an in-flight tool activity row and a token count",
    ),
    (
        "claude-basic-turn",
        "complete",
        13500,
        "file edit with a real diff, agent message, completion line",
    ),
    (
        "claude-subagent-and-mode",
        "mode-manual",
        14000,
        "the mode footer after cycling with shift+tab",
    ),
    (
        "claude-subagent-and-mode",
        "subagent-done",
        40000,
        "a backgrounded subagent, its completion row, a numbered list",
    ),
    (
        "claude-tool-error",
        "read-failed",
        30000,
        "the agent reporting a failed read in prose",
    ),
    (
        "claude-bash-error",
        "permission-question",
        25000,
        "a shell call parked on a four-option permission question",
    ),
    (
        "claude-plan-question",
        "plan-approval",
        30000,
        "plan-mode approval question with a selected option",
    ),
    (
        "claude-interrupted",
        "mid-turn",
        13200,
        "the agent working, before the interrupt",
    ),
    (
        "claude-interrupted",
        "after-escape",
        16000,
        "after Esc: 2.1.278 removes the turn rather than marking it",
    ),
    (
        "claude-awaiting-answer",
        "auto-mode-answer",
        18000,
        "auto mode footer, composer holding a restored draft",
    ),
];

/// The frame fixture file name for one instant.
pub fn frame_fixture_name(cast: &str, instant: &str) -> String {
    format!("{cast}@{instant}.frame.json")
}

/// The JSON-UI fixture file name for one instant. These are the eleven Swift
/// goldens promoted to cross-language fixtures: same recordings, same instants,
/// now compared in three languages instead of one.
pub fn jsonui_fixture_name(cast: &str, instant: &str) -> String {
    format!("{cast}@{instant}.jsonui.json")
}

/// `instants.json`: the index every language reads so that adding an instant
/// is one edit in Rust rather than three edits in three test suites.
pub fn instants_json() -> String {
    use crate::framedoc::Node;
    let entries = INSTANTS
        .iter()
        .map(|(cast, instant, time_ms, purpose)| {
            Node::object(vec![
                ("cast", Node::string(*cast)),
                ("instant", Node::string(*instant)),
                ("time_ms", Node::Int(*time_ms)),
                ("purpose", Node::string(*purpose)),
                ("frame", Node::string(frame_fixture_name(cast, instant))),
                ("jsonui", Node::string(jsonui_fixture_name(cast, instant))),
            ])
        })
        .collect();
    Node::object(vec![
        ("schema", Node::string("cua.transcript.conformance/1")),
        (
            "generated_notice",
            Node::string("Generated by cua-spaces-fixtures; do not edit by hand."),
        ),
        ("frame_schema", Node::string(crate::framedoc::FRAME_SCHEMA)),
        ("jsonui_schema", Node::string(crate::jsonui::JSONUI_SCHEMA)),
        ("instants", Node::Array(entries)),
    ])
    .to_json()
}
