// SPDX-License-Identifier: FSL-1.1-MIT
// Copyright (c) 2026 Cua AI, Inc.

// Generated by scripts/gen-images.mjs from libs/images/sandbox-images.json.
// Do not edit: change the JSON and rerun `node scripts/gen-images.mjs`.

extension SandboxImages {
    /// The groups that have at least one published image, in file order.
    static let groups: [SandboxImageGroup] = [
        SandboxImageGroup(id: "canonical", label: "Desktop images"),
        SandboxImageGroup(id: "distro", label: "Distribution images"),
    ]

    /// Every published image, in file order.
    static let published: [SandboxImage] = [
        SandboxImage(
            ref: "ghcr.io/trycua/linux:24.04",
            group: "canonical",
            os: "linux",
            name: "Ubuntu 24.04",
            variant: "container",
            summary: "Linux desktop with cua-spacesd and Chromium. Starts in seconds.",
            spacesd: true,
            local: "container",
            cloud: "gvisor",
            tier: "full"),
        SandboxImage(
            ref: "ghcr.io/trycua/linux:24.04-disk",
            group: "canonical",
            os: "linux",
            name: "Ubuntu 24.04 VM",
            variant: "vm",
            summary: "The same Linux desktop as a full VM. Lowest input latency.",
            spacesd: true,
            local: "qemu",
            cloud: "kubevirt",
            tier: "full"),
        SandboxImage(
            ref: "ghcr.io/trycua/linux:24.04-slim",
            group: "canonical",
            os: "linux",
            name: "Ubuntu 24.04 slim",
            variant: "container",
            summary: "The minimal Linux desktop: cua-spacesd and Chromium, no dev tooling. What CI and benchmarks run.",
            spacesd: true,
            local: "container",
            cloud: "gvisor",
            tier: "slim"),
        SandboxImage(
            ref: "ghcr.io/trycua/linux:24.04-slim-disk",
            group: "canonical",
            os: "linux",
            name: "Ubuntu 24.04 slim VM",
            variant: "vm",
            summary: "The minimal Linux desktop as a full VM.",
            spacesd: true,
            local: "qemu",
            cloud: "kubevirt",
            tier: "slim"),
        SandboxImage(
            ref: "ghcr.io/trycua/windows:2022",
            group: "canonical",
            os: "windows",
            name: "Windows Server 2022",
            variant: "vm",
            summary: "Windows VM with cua-spacesd and cua-driver.",
            spacesd: true,
            local: "qemu",
            cloud: "kubevirt",
            tier: "full"),
        SandboxImage(
            ref: "ghcr.io/trycua/macos:26",
            group: "canonical",
            os: "macos",
            name: "macOS Tahoe 26",
            variant: "vm",
            summary: "macOS VM on Apple silicon through Lume, with cua-spacesd at login: screenshots, desktop and window streams, input, files and exec, plus the Command Line Tools, Homebrew and dev tools. Local only.",
            spacesd: true,
            local: "lume",
            cloud: nil,
            tier: "full"),
        SandboxImage(
            ref: "ghcr.io/trycua/macos:26-slim",
            group: "canonical",
            os: "macos",
            name: "macOS Tahoe 26 slim",
            variant: "vm",
            summary: "The minimal macOS VM: cua-spacesd at login, Safari and Google Chrome, no dev tooling. What CI and benchmarks run. Local only.",
            spacesd: true,
            local: "lume",
            cloud: nil,
            tier: "slim"),
        SandboxImage(
            ref: "ghcr.io/trycua/macos:15",
            group: "canonical",
            os: "macos",
            name: "macOS Sequoia 15",
            variant: "vm",
            summary: "macOS VM on Apple silicon through Lume. Local only; exec, screenshots and view over SSH and VNC.",
            spacesd: false,
            local: "lume",
            cloud: nil,
            tier: nil),
        SandboxImage(
            ref: "ghcr.io/trycua/omarchy:edge",
            group: "distro",
            os: "linux",
            name: "Omarchy",
            variant: "vm",
            summary: "Omarchy edge (Arch, Hyprland) VM with Omarchy's cua-driver and Hyprland input plugin, plus cua-spacesd.",
            spacesd: true,
            local: "qemu",
            cloud: "kubevirt",
            tier: nil),
        SandboxImage(
            ref: "ghcr.io/trycua/omarchy:edge-disk",
            group: "distro",
            os: "linux",
            name: "Omarchy disk",
            variant: "vm",
            summary: "The containerDisk the Omarchy VM boots. Resolved from omarchy:edge; not offered on its own.",
            spacesd: true,
            local: "qemu",
            cloud: "kubevirt",
            tier: nil),
    ]
}
