#!/usr/bin/env python3
"""Generate a bounded Fumadocs MDX reference from mkdocstrings-python data."""

from __future__ import annotations
import argparse
import difflib
from pathlib import Path
from typing import Any
from mkdocstrings_handlers.python import PythonConfig, PythonHandler

ROOT = Path(__file__).resolve().parents[2]
PACKAGE_PATH = ROOT / "libs/python/cua-sandbox"
OUTPUT = ROOT / "docs/content/docs/reference/sandbox-sdk/index.mdx"
PRIVATE_RESULTS = {
    "'_ConnectResult'": "'Sandbox'",
    "_TunnelContext": "TunnelInfo | dict[int | str, TunnelInfo]",
}


def collect(module_name: str) -> Any:
    """Collect static source data; never import the SDK under documentation."""
    handler = PythonHandler(
        PythonConfig(paths=[str(PACKAGE_PATH)]),
        ROOT,
        theme="material",
        custom_templates=None,
        mdx=[],
        mdx_config={},
    )
    return handler.collect(
        module_name,
        handler.get_options(
            {"allow_inspection": False, "docstring_style": "google", "members_order": "source"}
        ),
    )


def target(member: Any) -> Any:
    return member.final_target if getattr(member, "is_alias", False) else member


def type_text(value: Any) -> str:
    result = str(value) if value is not None else "Any"
    for private, public in PRIVATE_RESULTS.items():
        result = result.replace(private, public)
    return result


def signature(function: Any) -> str:
    values, keyword_only = [], False
    for parameter in function.parameters:
        kind = parameter.kind.name
        if kind == "keyword_only" and not keyword_only:
            values.append("*")
            keyword_only = True
        prefix = "*" if kind == "var_positional" else "**" if kind == "var_keyword" else ""
        value = f"{prefix}{parameter.name}"
        if parameter.annotation is not None:
            value += f": {type_text(parameter.annotation)}"
        if parameter.default is not None and kind not in {"var_positional", "var_keyword"}:
            value += f" = {parameter.default}"
        values.append(value)
    result = (
        f"{'async ' if 'async' in function.labels else ''}def {function.name}({', '.join(values)})"
    )
    return result + (f" -> {type_text(function.returns)}" if function.returns is not None else "")


def summary(object_: Any) -> str:
    docstring = getattr(object_, "docstring", None)
    return (
        docstring.value.strip()
        .splitlines()[0]
        .replace("``", "`")
        .replace("*", "_")
        .replace("{", "\\{")
        .replace("}", "\\}")
        if docstring
        else ""
    )


def function_lines(function: Any, level: int) -> list[str]:
    lines = [f"{'#' * level} `{function.name}`", "", "```python", signature(function), "```"]
    if text := summary(function):
        lines.extend(["", text])
    if function.path == "cua_sandbox.sandbox.Sandbox.get_info":
        lines.extend(["", "Raises `ValueError` when no matching local sandbox exists."])
    return lines + [""]


def export_lines(name: str, member: Any, level: int = 2) -> list[str]:
    object_ = target(member)
    if getattr(object_, "is_function", False):
        lines = function_lines(object_, level)
        lines[0] = f"{'#' * level} `{name}`"
        return lines
    lines = [f"{'#' * level} `{name}`", ""]
    if text := summary(object_):
        lines.extend([text, ""])
    if getattr(object_, "is_class", False) and name != "CloudTransport":
        for child_name, child in object_.members.items():
            child = target(child)
            if getattr(child, "is_function", False) and (
                not child_name.startswith("_") or child_name in {"__aenter__", "__aexit__"}
            ):
                lines.extend(function_lines(child, level + 1))
    return lines


def compact(lines: list[str]) -> list[str]:
    result = []
    for line in lines:
        if line or (result and result[-1]):
            result.append(line)
    return result


def render() -> str:
    root = collect("cua_sandbox")
    lines = [
        "---",
        "title: Sandbox SDK reference",
        "description: 'Generated public API reference for the cua-sandbox Python package.'",
        "---",
        "",
        "{/* Generated by generate_mkdocstrings_sandbox_reference.py; do not edit by hand. */}",
        "",
        "This static MDX artifact is collected by mkdocstrings-python and Griffe without importing `cua_sandbox`. Fumadocs does not process MkDocs directives, so the generator emits native MDX for public exports only.",
        "",
    ]
    for name in root.exports:
        lines.extend(export_lines(name, root.members[name]))
    interfaces = collect("cua_sandbox.interfaces")
    lines.extend(["## Interfaces", "", "Public interaction interfaces exposed by `Sandbox`.", ""])
    for name in interfaces.exports:
        lines.extend(export_lines(name, interfaces.members[name]))
    return "\n".join(compact(lines)).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated, current = render(), OUTPUT.read_text() if OUTPUT.exists() else ""
    if args.check and generated != current:
        print("Generated sandbox SDK reference is out of date.")
        print("".join(difflib.unified_diff(current.splitlines(True), generated.splitlines(True))))
        return 1
    if args.check:
        print(f"{OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.write_text(generated)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
