// Generated by cua-contract-gen; do not edit by hand.

import type { ToolResult } from "./result.js"

export const CONTRACT_VERSION = "0.1.0" as const
export const MCP_PROTOCOL_VERSION = "2025-06-18" as const

export interface EndSessionArgs {
  session: string
}

function endSessionToWire(input: EndSessionArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  return output
}

export interface EscalateSessionArgs {
  session: string
  reason: "ax_tree_pixel_mismatch" | "background_delivery_failed" | "foreground_ineffective" | "no_window_target" | "other"
  detail?: string
}

function escalateSessionToWire(input: EscalateSessionArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  output.reason = input.reason
  if (input.detail !== undefined) output.detail = input.detail
  return output
}

export interface GetSessionStateArgs {
  session: string
}

function getSessionStateToWire(input: GetSessionStateArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  return output
}

export interface StartSessionArgs {
  session: string
  captureScope?: "auto" | "window" | "desktop"
}

function startSessionToWire(input: StartSessionArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  if (input.captureScope !== undefined) output.capture_scope = input.captureScope
  return output
}

export abstract class GeneratedClient {
  abstract callTool(name: string, input?: Record<string, unknown>): Promise<ToolResult>

  endSession(input: EndSessionArgs): Promise<ToolResult> {
    return this.callTool("end_session", endSessionToWire(input))
  }

  escalateSession(input: EscalateSessionArgs): Promise<ToolResult> {
    return this.callTool("escalate_session", escalateSessionToWire(input))
  }

  getSessionState(input: GetSessionStateArgs): Promise<ToolResult> {
    return this.callTool("get_session_state", getSessionStateToWire(input))
  }

  startSession(input: StartSessionArgs): Promise<ToolResult> {
    return this.callTool("start_session", startSessionToWire(input))
  }

}
