# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform
import cua_driver._native_contract


# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_cua_driver_sdk_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_cua_driver_sdk_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_cua_driver_sdk_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles.
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("cua_driver_sdk")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_cua_driver_sdk_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect() != 42154:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool() != 31445:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_click() != 34118:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_drag() != 35252:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_end_session() != 33990:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_escalate_session() != 37358:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_cursor_position() != 54043:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_desktop_state() != 32992:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_screen_size() != 15250:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session_state() != 51055:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_hotkey() != 3135:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_is_available() != 42961:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_list_tools_json() != 43987:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_move_cursor() != 11209:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_press_key() != 17425:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_scroll() != 21614:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_socket_path() != 24461:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_start_session() != 53509:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_cua_driver_sdk_checksum_method_cuadriver_type_text() != 19673:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_free.restype = None
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rustbuffer_reserve.restype = _UniffiRustBuffer
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFutureDroppedCallbackStruct(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK),
    ]
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u8.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u8.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i8.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i8.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u16.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u16.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i16.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i16.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_u64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_u64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_i64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_i64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_f32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_f32.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_f64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_f64.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_poll_void.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_cancel_void.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_complete_void.restype = None
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_sdk_rust_future_free_void.restype = None
_UniffiLib.uniffi_cua_driver_sdk_fn_clone_cuadriver.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_clone_cuadriver.restype = ctypes.c_uint64
_UniffiLib.uniffi_cua_driver_sdk_fn_free_cuadriver.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_free_cuadriver.restype = None
_UniffiLib.uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect.restype = ctypes.c_uint64
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_click.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_click.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_drag.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_drag.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_end_session.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_end_session.restype = cua_driver._native_contract._UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_escalate_session.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_escalate_session.restype = cua_driver._native_contract._UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_cursor_position.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_cursor_position.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_desktop_state.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_desktop_state.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_screen_size.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_screen_size.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_session_state.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_session_state.restype = cua_driver._native_contract._UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_hotkey.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_hotkey.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_is_available.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_is_available.restype = ctypes.c_int8
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_list_tools_json.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_list_tools_json.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_move_cursor.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_move_cursor.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_press_key.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_press_key.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_scroll.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_scroll.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_socket_path.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_socket_path.restype = _UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_start_session.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_start_session.restype = cua_driver._native_contract._UniffiRustBuffer
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_type_text.argtypes = (
    ctypes.c_uint64,
    cua_driver._native_contract._UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_type_text.restype = _UniffiRustBuffer
_UniffiLib.ffi_cua_driver_sdk_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_cua_driver_sdk_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_click.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_click.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_drag.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_drag.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_end_session.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_end_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_escalate_session.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_escalate_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_cursor_position.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_cursor_position.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_desktop_state.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_desktop_state.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_screen_size.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_screen_size.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session_state.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session_state.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_hotkey.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_hotkey.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_is_available.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_is_available.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_list_tools_json.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_list_tools_json.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_move_cursor.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_move_cursor.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_press_key.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_press_key.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_scroll.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_scroll.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_socket_path.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_socket_path.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_start_session.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_start_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_type_text.argtypes = (
)
_UniffiLib.uniffi_cua_driver_sdk_checksum_method_cuadriver_type_text.restype = ctypes.c_uint16

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

@dataclass
class ImageContent:
    def __init__(self, *, mime_type:str, data_base64:str):
        self.mime_type = mime_type
        self.data_base64 = data_base64




    def __str__(self):
        return "ImageContent(mime_type={}, data_base64={})".format(self.mime_type, self.data_base64)
    def __eq__(self, other):
        if self.mime_type != other.mime_type:
            return False
        if self.data_base64 != other.data_base64:
            return False
        return True

class _UniffiFfiConverterTypeImageContent(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ImageContent(
            mime_type=_UniffiFfiConverterString.read(buf),
            data_base64=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.mime_type)
        _UniffiFfiConverterString.check_lower(value.data_base64)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.mime_type, buf)
        _UniffiFfiConverterString.write(value.data_base64, buf)

class _UniffiFfiConverterSequenceTypeImageContent(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeImageContent.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeImageContent.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeImageContent.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiFfiConverterOptionalBoolean(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterBoolean.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterBoolean.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterBoolean.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class ToolResult:
    """
    Transport-neutral result envelope used for open-ended tool calls and
    desktop tools whose platform extensions are intentionally preserved as JSON.
"""
    def __init__(self, *, text:str, images:typing.List[ImageContent], structured_json:typing.Optional[str], is_error:bool, error_code:typing.Optional[str], verified:typing.Optional[bool], degraded:bool, raw_json:str):
        self.text = text
        self.images = images
        self.structured_json = structured_json
        self.is_error = is_error
        self.error_code = error_code
        self.verified = verified
        self.degraded = degraded
        self.raw_json = raw_json




    def __str__(self):
        return "ToolResult(text={}, images={}, structured_json={}, is_error={}, error_code={}, verified={}, degraded={}, raw_json={})".format(self.text, self.images, self.structured_json, self.is_error, self.error_code, self.verified, self.degraded, self.raw_json)
    def __eq__(self, other):
        if self.text != other.text:
            return False
        if self.images != other.images:
            return False
        if self.structured_json != other.structured_json:
            return False
        if self.is_error != other.is_error:
            return False
        if self.error_code != other.error_code:
            return False
        if self.verified != other.verified:
            return False
        if self.degraded != other.degraded:
            return False
        if self.raw_json != other.raw_json:
            return False
        return True

class _UniffiFfiConverterTypeToolResult(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ToolResult(
            text=_UniffiFfiConverterString.read(buf),
            images=_UniffiFfiConverterSequenceTypeImageContent.read(buf),
            structured_json=_UniffiFfiConverterOptionalString.read(buf),
            is_error=_UniffiFfiConverterBoolean.read(buf),
            error_code=_UniffiFfiConverterOptionalString.read(buf),
            verified=_UniffiFfiConverterOptionalBoolean.read(buf),
            degraded=_UniffiFfiConverterBoolean.read(buf),
            raw_json=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.text)
        _UniffiFfiConverterSequenceTypeImageContent.check_lower(value.images)
        _UniffiFfiConverterOptionalString.check_lower(value.structured_json)
        _UniffiFfiConverterBoolean.check_lower(value.is_error)
        _UniffiFfiConverterOptionalString.check_lower(value.error_code)
        _UniffiFfiConverterOptionalBoolean.check_lower(value.verified)
        _UniffiFfiConverterBoolean.check_lower(value.degraded)
        _UniffiFfiConverterString.check_lower(value.raw_json)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.text, buf)
        _UniffiFfiConverterSequenceTypeImageContent.write(value.images, buf)
        _UniffiFfiConverterOptionalString.write(value.structured_json, buf)
        _UniffiFfiConverterBoolean.write(value.is_error, buf)
        _UniffiFfiConverterOptionalString.write(value.error_code, buf)
        _UniffiFfiConverterOptionalBoolean.write(value.verified, buf)
        _UniffiFfiConverterBoolean.write(value.degraded, buf)
        _UniffiFfiConverterString.write(value.raw_json, buf)



# DriverError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class DriverError(Exception):
    pass

_UniffiTempDriverError = DriverError

class DriverError:  # type: ignore

    class Configuration(_UniffiTempDriverError):

        def __init__(self, reason):
            super().__init__(", ".join([
                "reason={!r}".format(reason),
            ]))
            self.reason = reason

        def __repr__(self):
            return "DriverError.Configuration({})".format(str(self))
    _UniffiTempDriverError.Configuration = Configuration # type: ignore
    class InvalidArguments(_UniffiTempDriverError):

        def __init__(self, tool, reason):
            super().__init__(", ".join([
                "tool={!r}".format(tool),
                "reason={!r}".format(reason),
            ]))
            self.tool = tool
            self.reason = reason

        def __repr__(self):
            return "DriverError.InvalidArguments({})".format(str(self))
    _UniffiTempDriverError.InvalidArguments = InvalidArguments # type: ignore
    class Transport(_UniffiTempDriverError):

        def __init__(self, socket_path, reason):
            super().__init__(", ".join([
                "socket_path={!r}".format(socket_path),
                "reason={!r}".format(reason),
            ]))
            self.socket_path = socket_path
            self.reason = reason

        def __repr__(self):
            return "DriverError.Transport({})".format(str(self))
    _UniffiTempDriverError.Transport = Transport # type: ignore
    class Protocol(_UniffiTempDriverError):

        def __init__(self, reason):
            super().__init__(", ".join([
                "reason={!r}".format(reason),
            ]))
            self.reason = reason

        def __repr__(self):
            return "DriverError.Protocol({})".format(str(self))
    _UniffiTempDriverError.Protocol = Protocol # type: ignore
    class Tool(_UniffiTempDriverError):

        def __init__(self, tool, message, error_code):
            super().__init__(", ".join([
                "tool={!r}".format(tool),
                "message={!r}".format(message),
                "error_code={!r}".format(error_code),
            ]))
            self.tool = tool
            self.message = message
            self.error_code = error_code

        def __repr__(self):
            return "DriverError.Tool({})".format(str(self))
    _UniffiTempDriverError.Tool = Tool # type: ignore

DriverError = _UniffiTempDriverError # type: ignore
del _UniffiTempDriverError


class _UniffiFfiConverterTypeDriverError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return DriverError.Configuration(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return DriverError.InvalidArguments(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return DriverError.Transport(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 4:
            return DriverError.Protocol(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 5:
            return DriverError.Tool(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, DriverError.Configuration):
            _UniffiFfiConverterString.check_lower(value.reason)
            return
        if isinstance(value, DriverError.InvalidArguments):
            _UniffiFfiConverterString.check_lower(value.tool)
            _UniffiFfiConverterString.check_lower(value.reason)
            return
        if isinstance(value, DriverError.Transport):
            _UniffiFfiConverterString.check_lower(value.socket_path)
            _UniffiFfiConverterString.check_lower(value.reason)
            return
        if isinstance(value, DriverError.Protocol):
            _UniffiFfiConverterString.check_lower(value.reason)
            return
        if isinstance(value, DriverError.Tool):
            _UniffiFfiConverterString.check_lower(value.tool)
            _UniffiFfiConverterString.check_lower(value.message)
            _UniffiFfiConverterString.check_lower(value.error_code)
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, DriverError.Configuration):
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value.reason, buf)
        if isinstance(value, DriverError.InvalidArguments):
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value.tool, buf)
            _UniffiFfiConverterString.write(value.reason, buf)
        if isinstance(value, DriverError.Transport):
            buf.write_i32(3)
            _UniffiFfiConverterString.write(value.socket_path, buf)
            _UniffiFfiConverterString.write(value.reason, buf)
        if isinstance(value, DriverError.Protocol):
            buf.write_i32(4)
            _UniffiFfiConverterString.write(value.reason, buf)
        if isinstance(value, DriverError.Tool):
            buf.write_i32(5)
            _UniffiFfiConverterString.write(value.tool, buf)
            _UniffiFfiConverterString.write(value.message, buf)
            _UniffiFfiConverterString.write(value.error_code, buf)




































class CuaDriverProtocol(typing.Protocol):

    def call_tool(self, name: str,arguments_json: str) -> ToolResult:
        """
        Escape hatch for forward-compatible tools and application-owned server
        adapters. Typed methods below serialize the same canonical Rust inputs.
"""
        raise NotImplementedError
    def click(self, input: cua_driver._native_contract.ClickInput) -> ToolResult:
        raise NotImplementedError
    def drag(self, input: cua_driver._native_contract.DragInput) -> ToolResult:
        raise NotImplementedError
    def end_session(self, input: cua_driver._native_contract.EndSessionInput) -> cua_driver._native_contract.EndSessionOutput:
        raise NotImplementedError
    def escalate_session(self, input: cua_driver._native_contract.EscalateSessionInput) -> cua_driver._native_contract.SessionStateOutput:
        raise NotImplementedError
    def get_cursor_position(self, input: cua_driver._native_contract.GetCursorPositionInput) -> ToolResult:
        raise NotImplementedError
    def get_desktop_state(self, input: cua_driver._native_contract.GetDesktopStateInput) -> ToolResult:
        raise NotImplementedError
    def get_screen_size(self, input: cua_driver._native_contract.GetScreenSizeInput) -> ToolResult:
        raise NotImplementedError
    def get_session_state(self, input: cua_driver._native_contract.GetSessionStateInput) -> cua_driver._native_contract.SessionStateOutput:
        raise NotImplementedError
    def hotkey(self, input: cua_driver._native_contract.HotkeyInput) -> ToolResult:
        raise NotImplementedError
    def is_available(self, ) -> bool:
        raise NotImplementedError
    def list_tools_json(self, ) -> str:
        raise NotImplementedError
    def move_cursor(self, input: cua_driver._native_contract.MoveCursorInput) -> ToolResult:
        raise NotImplementedError
    def press_key(self, input: cua_driver._native_contract.PressKeyInput) -> ToolResult:
        raise NotImplementedError
    def scroll(self, input: cua_driver._native_contract.ScrollInput) -> ToolResult:
        raise NotImplementedError
    def socket_path(self, ) -> str:
        raise NotImplementedError
    def start_session(self, input: cua_driver._native_contract.StartSessionInput) -> cua_driver._native_contract.StartSessionOutput:
        raise NotImplementedError
    def type_text(self, input: cua_driver._native_contract.TypeTextInput) -> ToolResult:
        raise NotImplementedError

class CuaDriver(CuaDriverProtocol):

    _handle: ctypes.c_uint64
    @classmethod
    def connect(cls, socket_path: typing.Optional[str]) -> CuaDriver:
        """
        Connect to the default installed daemon or an explicitly selected socket.
        Construction does not launch a process or perform I/O.
"""

        _UniffiFfiConverterOptionalString.check_lower(socket_path)
        _uniffi_lowered_args = (
            _UniffiFfiConverterOptionalString.lower(socket_path),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeCuaDriver.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)

    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_cua_driver_sdk_fn_free_cuadriver, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_cua_driver_sdk_fn_clone_cuadriver, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def call_tool(self, name: str,arguments_json: str) -> ToolResult:
        """
        Escape hatch for forward-compatible tools and application-owned server
        adapters. Typed methods below serialize the same canonical Rust inputs.
"""

        _UniffiFfiConverterString.check_lower(name)

        _UniffiFfiConverterString.check_lower(arguments_json)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(name),
            _UniffiFfiConverterString.lower(arguments_json),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def click(self, input: cua_driver._native_contract.ClickInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeClickInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeClickInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_click,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def drag(self, input: cua_driver._native_contract.DragInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeDragInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeDragInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_drag,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def end_session(self, input: cua_driver._native_contract.EndSessionInput) -> cua_driver._native_contract.EndSessionOutput:

        cua_driver._native_contract._UniffiFfiConverterTypeEndSessionInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeEndSessionInput.lower(input),
        )
        _uniffi_lift_return = cua_driver._native_contract._UniffiFfiConverterTypeEndSessionOutput.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_end_session,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def escalate_session(self, input: cua_driver._native_contract.EscalateSessionInput) -> cua_driver._native_contract.SessionStateOutput:

        cua_driver._native_contract._UniffiFfiConverterTypeEscalateSessionInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeEscalateSessionInput.lower(input),
        )
        _uniffi_lift_return = cua_driver._native_contract._UniffiFfiConverterTypeSessionStateOutput.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_escalate_session,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_cursor_position(self, input: cua_driver._native_contract.GetCursorPositionInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeGetCursorPositionInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeGetCursorPositionInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_cursor_position,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_desktop_state(self, input: cua_driver._native_contract.GetDesktopStateInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeGetDesktopStateInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeGetDesktopStateInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_desktop_state,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_screen_size(self, input: cua_driver._native_contract.GetScreenSizeInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeGetScreenSizeInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeGetScreenSizeInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_screen_size,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_session_state(self, input: cua_driver._native_contract.GetSessionStateInput) -> cua_driver._native_contract.SessionStateOutput:

        cua_driver._native_contract._UniffiFfiConverterTypeGetSessionStateInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeGetSessionStateInput.lower(input),
        )
        _uniffi_lift_return = cua_driver._native_contract._UniffiFfiConverterTypeSessionStateOutput.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_get_session_state,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def hotkey(self, input: cua_driver._native_contract.HotkeyInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeHotkeyInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeHotkeyInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_hotkey,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def is_available(self, ) -> bool:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_is_available,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def list_tools_json(self, ) -> str:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_list_tools_json,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def move_cursor(self, input: cua_driver._native_contract.MoveCursorInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeMoveCursorInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeMoveCursorInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_move_cursor,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def press_key(self, input: cua_driver._native_contract.PressKeyInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypePressKeyInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypePressKeyInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_press_key,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def scroll(self, input: cua_driver._native_contract.ScrollInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeScrollInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeScrollInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_scroll,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def socket_path(self, ) -> str:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_socket_path,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def start_session(self, input: cua_driver._native_contract.StartSessionInput) -> cua_driver._native_contract.StartSessionOutput:

        cua_driver._native_contract._UniffiFfiConverterTypeStartSessionInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeStartSessionInput.lower(input),
        )
        _uniffi_lift_return = cua_driver._native_contract._UniffiFfiConverterTypeStartSessionOutput.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_start_session,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def type_text(self, input: cua_driver._native_contract.TypeTextInput) -> ToolResult:

        cua_driver._native_contract._UniffiFfiConverterTypeTypeTextInput.check_lower(input)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            cua_driver._native_contract._UniffiFfiConverterTypeTypeTextInput.lower(input),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeToolResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeDriverError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_cua_driver_sdk_fn_method_cuadriver_type_text,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeCuaDriver:
    @staticmethod
    def lift(value: int) -> CuaDriver:
        return CuaDriver._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: CuaDriver):
        if not isinstance(value, CuaDriver):
            raise TypeError("Expected CuaDriver instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: CuaDriver) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> CuaDriver:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: CuaDriver, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)

__all__ = [
    "InternalError",
    "DriverError",
    "ImageContent",
    "ToolResult",
    "CuaDriver",
    "CuaDriverProtocol",
]
