# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_cua_driver_contract_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_cua_driver_contract_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_cua_driver_contract_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles.
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("cua_driver_sdk")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_cua_driver_contract_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    pass

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_cua_driver_contract_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_cua_driver_contract_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_cua_driver_contract_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rustbuffer_free.restype = None
_UniffiLib.ffi_cua_driver_contract_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rustbuffer_reserve.restype = _UniffiRustBuffer
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFutureDroppedCallbackStruct(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK),
    ]
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u8.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u8.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i8.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i8.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u16.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u16.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i16.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i16.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_u64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_u64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_i64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_i64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_f32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_cua_driver_contract_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_f32.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_f64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_cua_driver_contract_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_f64.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_cua_driver_contract_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_poll_void.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_cancel_void.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_cua_driver_contract_rust_future_complete_void.restype = None
_UniffiLib.ffi_cua_driver_contract_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_cua_driver_contract_rust_future_free_void.restype = None
_UniffiLib.ffi_cua_driver_contract_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_cua_driver_contract_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterFloat64(_UniffiConverterPrimitiveFloat):
    @staticmethod
    def read(buf):
        return buf.read_double()

    @staticmethod
    def write(value, buf):
        buf.write_double(value)






class DesktopScope(enum.Enum):

    DESKTOP = 0



class _UniffiFfiConverterTypeDesktopScope(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return DesktopScope.DESKTOP
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == DesktopScope.DESKTOP:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == DesktopScope.DESKTOP:
            buf.write_i32(1)



class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")






class ClickButton(enum.Enum):

    LEFT = 0

    RIGHT = 1

    MIDDLE = 2



class _UniffiFfiConverterTypeClickButton(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return ClickButton.LEFT
        if variant == 2:
            return ClickButton.RIGHT
        if variant == 3:
            return ClickButton.MIDDLE
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == ClickButton.LEFT:
            return
        if value == ClickButton.RIGHT:
            return
        if value == ClickButton.MIDDLE:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == ClickButton.LEFT:
            buf.write_i32(1)
        if value == ClickButton.RIGHT:
            buf.write_i32(2)
        if value == ClickButton.MIDDLE:
            buf.write_i32(3)



class _UniffiFfiConverterOptionalTypeClickButton(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeClickButton.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeClickButton.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeClickButton.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterUInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.read_u32()

    @staticmethod
    def write(value, buf):
        buf.write_u32(value)

class _UniffiFfiConverterOptionalUInt32(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterUInt32.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterUInt32.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterUInt32.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class ClickInput:
    def __init__(self, *, x:float, y:float, scope:DesktopScope, session:typing.Optional[str], button:typing.Optional[ClickButton], count:typing.Optional[int]):
        self.x = x
        self.y = y
        self.scope = scope
        self.session = session
        self.button = button
        self.count = count




    def __str__(self):
        return "ClickInput(x={}, y={}, scope={}, session={}, button={}, count={})".format(self.x, self.y, self.scope, self.session, self.button, self.count)
    def __eq__(self, other):
        if self.x != other.x:
            return False
        if self.y != other.y:
            return False
        if self.scope != other.scope:
            return False
        if self.session != other.session:
            return False
        if self.button != other.button:
            return False
        if self.count != other.count:
            return False
        return True

class _UniffiFfiConverterTypeClickInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ClickInput(
            x=_UniffiFfiConverterFloat64.read(buf),
            y=_UniffiFfiConverterFloat64.read(buf),
            scope=_UniffiFfiConverterTypeDesktopScope.read(buf),
            session=_UniffiFfiConverterOptionalString.read(buf),
            button=_UniffiFfiConverterOptionalTypeClickButton.read(buf),
            count=_UniffiFfiConverterOptionalUInt32.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterFloat64.check_lower(value.x)
        _UniffiFfiConverterFloat64.check_lower(value.y)
        _UniffiFfiConverterTypeDesktopScope.check_lower(value.scope)
        _UniffiFfiConverterOptionalString.check_lower(value.session)
        _UniffiFfiConverterOptionalTypeClickButton.check_lower(value.button)
        _UniffiFfiConverterOptionalUInt32.check_lower(value.count)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterFloat64.write(value.x, buf)
        _UniffiFfiConverterFloat64.write(value.y, buf)
        _UniffiFfiConverterTypeDesktopScope.write(value.scope, buf)
        _UniffiFfiConverterOptionalString.write(value.session, buf)
        _UniffiFfiConverterOptionalTypeClickButton.write(value.button, buf)
        _UniffiFfiConverterOptionalUInt32.write(value.count, buf)

class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiFfiConverterOptionalUInt64(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterUInt64.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterUInt64.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterUInt64.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterString.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterOptionalSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterSequenceString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterSequenceString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterSequenceString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class DragInput:
    def __init__(self, *, from_x:float, from_y:float, to_x:float, to_y:float, scope:DesktopScope, session:typing.Optional[str], duration_ms:typing.Optional[int], steps:typing.Optional[int], button:typing.Optional[ClickButton], modifier:typing.Optional[typing.List[str]]):
        self.from_x = from_x
        self.from_y = from_y
        self.to_x = to_x
        self.to_y = to_y
        self.scope = scope
        self.session = session
        self.duration_ms = duration_ms
        self.steps = steps
        self.button = button
        self.modifier = modifier




    def __str__(self):
        return "DragInput(from_x={}, from_y={}, to_x={}, to_y={}, scope={}, session={}, duration_ms={}, steps={}, button={}, modifier={})".format(self.from_x, self.from_y, self.to_x, self.to_y, self.scope, self.session, self.duration_ms, self.steps, self.button, self.modifier)
    def __eq__(self, other):
        if self.from_x != other.from_x:
            return False
        if self.from_y != other.from_y:
            return False
        if self.to_x != other.to_x:
            return False
        if self.to_y != other.to_y:
            return False
        if self.scope != other.scope:
            return False
        if self.session != other.session:
            return False
        if self.duration_ms != other.duration_ms:
            return False
        if self.steps != other.steps:
            return False
        if self.button != other.button:
            return False
        if self.modifier != other.modifier:
            return False
        return True

class _UniffiFfiConverterTypeDragInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return DragInput(
            from_x=_UniffiFfiConverterFloat64.read(buf),
            from_y=_UniffiFfiConverterFloat64.read(buf),
            to_x=_UniffiFfiConverterFloat64.read(buf),
            to_y=_UniffiFfiConverterFloat64.read(buf),
            scope=_UniffiFfiConverterTypeDesktopScope.read(buf),
            session=_UniffiFfiConverterOptionalString.read(buf),
            duration_ms=_UniffiFfiConverterOptionalUInt64.read(buf),
            steps=_UniffiFfiConverterOptionalUInt64.read(buf),
            button=_UniffiFfiConverterOptionalTypeClickButton.read(buf),
            modifier=_UniffiFfiConverterOptionalSequenceString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterFloat64.check_lower(value.from_x)
        _UniffiFfiConverterFloat64.check_lower(value.from_y)
        _UniffiFfiConverterFloat64.check_lower(value.to_x)
        _UniffiFfiConverterFloat64.check_lower(value.to_y)
        _UniffiFfiConverterTypeDesktopScope.check_lower(value.scope)
        _UniffiFfiConverterOptionalString.check_lower(value.session)
        _UniffiFfiConverterOptionalUInt64.check_lower(value.duration_ms)
        _UniffiFfiConverterOptionalUInt64.check_lower(value.steps)
        _UniffiFfiConverterOptionalTypeClickButton.check_lower(value.button)
        _UniffiFfiConverterOptionalSequenceString.check_lower(value.modifier)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterFloat64.write(value.from_x, buf)
        _UniffiFfiConverterFloat64.write(value.from_y, buf)
        _UniffiFfiConverterFloat64.write(value.to_x, buf)
        _UniffiFfiConverterFloat64.write(value.to_y, buf)
        _UniffiFfiConverterTypeDesktopScope.write(value.scope, buf)
        _UniffiFfiConverterOptionalString.write(value.session, buf)
        _UniffiFfiConverterOptionalUInt64.write(value.duration_ms, buf)
        _UniffiFfiConverterOptionalUInt64.write(value.steps, buf)
        _UniffiFfiConverterOptionalTypeClickButton.write(value.button, buf)
        _UniffiFfiConverterOptionalSequenceString.write(value.modifier, buf)

@dataclass
class EndSessionInput:
    def __init__(self, *, session:str):
        self.session = session




    def __str__(self):
        return "EndSessionInput(session={})".format(self.session)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        return True

class _UniffiFfiConverterTypeEndSessionInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return EndSessionInput(
            session=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.session)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.session, buf)

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

@dataclass
class EndSessionOutput:
    """
    Successful structured result returned by `end_session`.
"""
    def __init__(self, *, session:str, active:bool):
        self.session = session
        self.active = active




    def __str__(self):
        return "EndSessionOutput(session={}, active={})".format(self.session, self.active)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        if self.active != other.active:
            return False
        return True

class _UniffiFfiConverterTypeEndSessionOutput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return EndSessionOutput(
            session=_UniffiFfiConverterString.read(buf),
            active=_UniffiFfiConverterBoolean.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.session)
        _UniffiFfiConverterBoolean.check_lower(value.active)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.session, buf)
        _UniffiFfiConverterBoolean.write(value.active, buf)






class EscalationReason(enum.Enum):

    AX_TREE_PIXEL_MISMATCH = 0

    BACKGROUND_DELIVERY_FAILED = 1

    FOREGROUND_INEFFECTIVE = 2

    NO_WINDOW_TARGET = 3

    OTHER = 4



class _UniffiFfiConverterTypeEscalationReason(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return EscalationReason.AX_TREE_PIXEL_MISMATCH
        if variant == 2:
            return EscalationReason.BACKGROUND_DELIVERY_FAILED
        if variant == 3:
            return EscalationReason.FOREGROUND_INEFFECTIVE
        if variant == 4:
            return EscalationReason.NO_WINDOW_TARGET
        if variant == 5:
            return EscalationReason.OTHER
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == EscalationReason.AX_TREE_PIXEL_MISMATCH:
            return
        if value == EscalationReason.BACKGROUND_DELIVERY_FAILED:
            return
        if value == EscalationReason.FOREGROUND_INEFFECTIVE:
            return
        if value == EscalationReason.NO_WINDOW_TARGET:
            return
        if value == EscalationReason.OTHER:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == EscalationReason.AX_TREE_PIXEL_MISMATCH:
            buf.write_i32(1)
        if value == EscalationReason.BACKGROUND_DELIVERY_FAILED:
            buf.write_i32(2)
        if value == EscalationReason.FOREGROUND_INEFFECTIVE:
            buf.write_i32(3)
        if value == EscalationReason.NO_WINDOW_TARGET:
            buf.write_i32(4)
        if value == EscalationReason.OTHER:
            buf.write_i32(5)



@dataclass
class EscalateSessionInput:
    def __init__(self, *, session:str, reason:EscalationReason, detail:typing.Optional[str]):
        self.session = session
        self.reason = reason
        self.detail = detail




    def __str__(self):
        return "EscalateSessionInput(session={}, reason={}, detail={})".format(self.session, self.reason, self.detail)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        if self.reason != other.reason:
            return False
        if self.detail != other.detail:
            return False
        return True

class _UniffiFfiConverterTypeEscalateSessionInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return EscalateSessionInput(
            session=_UniffiFfiConverterString.read(buf),
            reason=_UniffiFfiConverterTypeEscalationReason.read(buf),
            detail=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.session)
        _UniffiFfiConverterTypeEscalationReason.check_lower(value.reason)
        _UniffiFfiConverterOptionalString.check_lower(value.detail)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.session, buf)
        _UniffiFfiConverterTypeEscalationReason.write(value.reason, buf)
        _UniffiFfiConverterOptionalString.write(value.detail, buf)

@dataclass
class GetCursorPositionInput:
    def __init__(self, *, session:typing.Optional[str]):
        self.session = session




    def __str__(self):
        return "GetCursorPositionInput(session={})".format(self.session)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        return True

class _UniffiFfiConverterTypeGetCursorPositionInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return GetCursorPositionInput(
            session=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterOptionalString.check_lower(value.session)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterOptionalString.write(value.session, buf)

@dataclass
class GetDesktopStateInput:
    def __init__(self, *, session:typing.Optional[str], screenshot_out_file:typing.Optional[str]):
        self.session = session
        self.screenshot_out_file = screenshot_out_file




    def __str__(self):
        return "GetDesktopStateInput(session={}, screenshot_out_file={})".format(self.session, self.screenshot_out_file)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        if self.screenshot_out_file != other.screenshot_out_file:
            return False
        return True

class _UniffiFfiConverterTypeGetDesktopStateInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return GetDesktopStateInput(
            session=_UniffiFfiConverterOptionalString.read(buf),
            screenshot_out_file=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterOptionalString.check_lower(value.session)
        _UniffiFfiConverterOptionalString.check_lower(value.screenshot_out_file)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterOptionalString.write(value.session, buf)
        _UniffiFfiConverterOptionalString.write(value.screenshot_out_file, buf)

@dataclass
class GetScreenSizeInput:
    def __init__(self, *, session:typing.Optional[str]):
        self.session = session




    def __str__(self):
        return "GetScreenSizeInput(session={})".format(self.session)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        return True

class _UniffiFfiConverterTypeGetScreenSizeInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return GetScreenSizeInput(
            session=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterOptionalString.check_lower(value.session)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterOptionalString.write(value.session, buf)

@dataclass
class GetSessionStateInput:
    def __init__(self, *, session:str):
        self.session = session




    def __str__(self):
        return "GetSessionStateInput(session={})".format(self.session)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        return True

class _UniffiFfiConverterTypeGetSessionStateInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return GetSessionStateInput(
            session=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.session)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.session, buf)

@dataclass
class HotkeyInput:
    def __init__(self, *, keys:typing.List[str], scope:DesktopScope, session:typing.Optional[str]):
        self.keys = keys
        self.scope = scope
        self.session = session




    def __str__(self):
        return "HotkeyInput(keys={}, scope={}, session={})".format(self.keys, self.scope, self.session)
    def __eq__(self, other):
        if self.keys != other.keys:
            return False
        if self.scope != other.scope:
            return False
        if self.session != other.session:
            return False
        return True

class _UniffiFfiConverterTypeHotkeyInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return HotkeyInput(
            keys=_UniffiFfiConverterSequenceString.read(buf),
            scope=_UniffiFfiConverterTypeDesktopScope.read(buf),
            session=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceString.check_lower(value.keys)
        _UniffiFfiConverterTypeDesktopScope.check_lower(value.scope)
        _UniffiFfiConverterOptionalString.check_lower(value.session)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceString.write(value.keys, buf)
        _UniffiFfiConverterTypeDesktopScope.write(value.scope, buf)
        _UniffiFfiConverterOptionalString.write(value.session, buf)

@dataclass
class MoveCursorInput:
    def __init__(self, *, x:float, y:float, scope:DesktopScope, session:typing.Optional[str]):
        self.x = x
        self.y = y
        self.scope = scope
        self.session = session




    def __str__(self):
        return "MoveCursorInput(x={}, y={}, scope={}, session={})".format(self.x, self.y, self.scope, self.session)
    def __eq__(self, other):
        if self.x != other.x:
            return False
        if self.y != other.y:
            return False
        if self.scope != other.scope:
            return False
        if self.session != other.session:
            return False
        return True

class _UniffiFfiConverterTypeMoveCursorInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return MoveCursorInput(
            x=_UniffiFfiConverterFloat64.read(buf),
            y=_UniffiFfiConverterFloat64.read(buf),
            scope=_UniffiFfiConverterTypeDesktopScope.read(buf),
            session=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterFloat64.check_lower(value.x)
        _UniffiFfiConverterFloat64.check_lower(value.y)
        _UniffiFfiConverterTypeDesktopScope.check_lower(value.scope)
        _UniffiFfiConverterOptionalString.check_lower(value.session)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterFloat64.write(value.x, buf)
        _UniffiFfiConverterFloat64.write(value.y, buf)
        _UniffiFfiConverterTypeDesktopScope.write(value.scope, buf)
        _UniffiFfiConverterOptionalString.write(value.session, buf)

@dataclass
class PressKeyInput:
    def __init__(self, *, key:str, scope:DesktopScope, session:typing.Optional[str], modifiers:typing.Optional[typing.List[str]]):
        self.key = key
        self.scope = scope
        self.session = session
        self.modifiers = modifiers




    def __str__(self):
        return "PressKeyInput(key={}, scope={}, session={}, modifiers={})".format(self.key, self.scope, self.session, self.modifiers)
    def __eq__(self, other):
        if self.key != other.key:
            return False
        if self.scope != other.scope:
            return False
        if self.session != other.session:
            return False
        if self.modifiers != other.modifiers:
            return False
        return True

class _UniffiFfiConverterTypePressKeyInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return PressKeyInput(
            key=_UniffiFfiConverterString.read(buf),
            scope=_UniffiFfiConverterTypeDesktopScope.read(buf),
            session=_UniffiFfiConverterOptionalString.read(buf),
            modifiers=_UniffiFfiConverterOptionalSequenceString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.key)
        _UniffiFfiConverterTypeDesktopScope.check_lower(value.scope)
        _UniffiFfiConverterOptionalString.check_lower(value.session)
        _UniffiFfiConverterOptionalSequenceString.check_lower(value.modifiers)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.key, buf)
        _UniffiFfiConverterTypeDesktopScope.write(value.scope, buf)
        _UniffiFfiConverterOptionalString.write(value.session, buf)
        _UniffiFfiConverterOptionalSequenceString.write(value.modifiers, buf)






class ScrollDirection(enum.Enum):

    UP = 0

    DOWN = 1

    LEFT = 2

    RIGHT = 3



class _UniffiFfiConverterTypeScrollDirection(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return ScrollDirection.UP
        if variant == 2:
            return ScrollDirection.DOWN
        if variant == 3:
            return ScrollDirection.LEFT
        if variant == 4:
            return ScrollDirection.RIGHT
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == ScrollDirection.UP:
            return
        if value == ScrollDirection.DOWN:
            return
        if value == ScrollDirection.LEFT:
            return
        if value == ScrollDirection.RIGHT:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == ScrollDirection.UP:
            buf.write_i32(1)
        if value == ScrollDirection.DOWN:
            buf.write_i32(2)
        if value == ScrollDirection.LEFT:
            buf.write_i32(3)
        if value == ScrollDirection.RIGHT:
            buf.write_i32(4)








class ScrollBy(enum.Enum):

    LINE = 0

    PAGE = 1



class _UniffiFfiConverterTypeScrollBy(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return ScrollBy.LINE
        if variant == 2:
            return ScrollBy.PAGE
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == ScrollBy.LINE:
            return
        if value == ScrollBy.PAGE:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == ScrollBy.LINE:
            buf.write_i32(1)
        if value == ScrollBy.PAGE:
            buf.write_i32(2)



class _UniffiFfiConverterOptionalTypeScrollBy(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeScrollBy.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeScrollBy.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeScrollBy.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class ScrollInput:
    def __init__(self, *, x:float, y:float, direction:ScrollDirection, scope:DesktopScope, session:typing.Optional[str], by:typing.Optional[ScrollBy], amount:typing.Optional[int]):
        self.x = x
        self.y = y
        self.direction = direction
        self.scope = scope
        self.session = session
        self.by = by
        self.amount = amount




    def __str__(self):
        return "ScrollInput(x={}, y={}, direction={}, scope={}, session={}, by={}, amount={})".format(self.x, self.y, self.direction, self.scope, self.session, self.by, self.amount)
    def __eq__(self, other):
        if self.x != other.x:
            return False
        if self.y != other.y:
            return False
        if self.direction != other.direction:
            return False
        if self.scope != other.scope:
            return False
        if self.session != other.session:
            return False
        if self.by != other.by:
            return False
        if self.amount != other.amount:
            return False
        return True

class _UniffiFfiConverterTypeScrollInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ScrollInput(
            x=_UniffiFfiConverterFloat64.read(buf),
            y=_UniffiFfiConverterFloat64.read(buf),
            direction=_UniffiFfiConverterTypeScrollDirection.read(buf),
            scope=_UniffiFfiConverterTypeDesktopScope.read(buf),
            session=_UniffiFfiConverterOptionalString.read(buf),
            by=_UniffiFfiConverterOptionalTypeScrollBy.read(buf),
            amount=_UniffiFfiConverterOptionalUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterFloat64.check_lower(value.x)
        _UniffiFfiConverterFloat64.check_lower(value.y)
        _UniffiFfiConverterTypeScrollDirection.check_lower(value.direction)
        _UniffiFfiConverterTypeDesktopScope.check_lower(value.scope)
        _UniffiFfiConverterOptionalString.check_lower(value.session)
        _UniffiFfiConverterOptionalTypeScrollBy.check_lower(value.by)
        _UniffiFfiConverterOptionalUInt64.check_lower(value.amount)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterFloat64.write(value.x, buf)
        _UniffiFfiConverterFloat64.write(value.y, buf)
        _UniffiFfiConverterTypeScrollDirection.write(value.direction, buf)
        _UniffiFfiConverterTypeDesktopScope.write(value.scope, buf)
        _UniffiFfiConverterOptionalString.write(value.session, buf)
        _UniffiFfiConverterOptionalTypeScrollBy.write(value.by, buf)
        _UniffiFfiConverterOptionalUInt64.write(value.amount, buf)






class CaptureScope(enum.Enum):

    AUTO = 0

    WINDOW = 1

    DESKTOP = 2



class _UniffiFfiConverterTypeCaptureScope(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return CaptureScope.AUTO
        if variant == 2:
            return CaptureScope.WINDOW
        if variant == 3:
            return CaptureScope.DESKTOP
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == CaptureScope.AUTO:
            return
        if value == CaptureScope.WINDOW:
            return
        if value == CaptureScope.DESKTOP:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == CaptureScope.AUTO:
            buf.write_i32(1)
        if value == CaptureScope.WINDOW:
            buf.write_i32(2)
        if value == CaptureScope.DESKTOP:
            buf.write_i32(3)








class EffectiveScope(enum.Enum):

    WINDOW = 0

    DESKTOP = 1



class _UniffiFfiConverterTypeEffectiveScope(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return EffectiveScope.WINDOW
        if variant == 2:
            return EffectiveScope.DESKTOP
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == EffectiveScope.WINDOW:
            return
        if value == EffectiveScope.DESKTOP:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == EffectiveScope.WINDOW:
            buf.write_i32(1)
        if value == EffectiveScope.DESKTOP:
            buf.write_i32(2)



class _UniffiFfiConverterOptionalTypeEscalationReason(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeEscalationReason.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeEscalationReason.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeEscalationReason.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class SessionStateOutput:
    """
    Successful structured result shared by session state and escalation tools.
"""
    def __init__(self, *, session:str, capture_scope:CaptureScope, effective_scope:EffectiveScope, desktop_unlocked:bool, escalation_reason:typing.Optional[EscalationReason], escalation_detail:typing.Optional[str], workspace_id:typing.Optional[str]):
        self.session = session
        self.capture_scope = capture_scope
        self.effective_scope = effective_scope
        self.desktop_unlocked = desktop_unlocked
        self.escalation_reason = escalation_reason
        self.escalation_detail = escalation_detail
        self.workspace_id = workspace_id




    def __str__(self):
        return "SessionStateOutput(session={}, capture_scope={}, effective_scope={}, desktop_unlocked={}, escalation_reason={}, escalation_detail={}, workspace_id={})".format(self.session, self.capture_scope, self.effective_scope, self.desktop_unlocked, self.escalation_reason, self.escalation_detail, self.workspace_id)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        if self.capture_scope != other.capture_scope:
            return False
        if self.effective_scope != other.effective_scope:
            return False
        if self.desktop_unlocked != other.desktop_unlocked:
            return False
        if self.escalation_reason != other.escalation_reason:
            return False
        if self.escalation_detail != other.escalation_detail:
            return False
        if self.workspace_id != other.workspace_id:
            return False
        return True

class _UniffiFfiConverterTypeSessionStateOutput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SessionStateOutput(
            session=_UniffiFfiConverterString.read(buf),
            capture_scope=_UniffiFfiConverterTypeCaptureScope.read(buf),
            effective_scope=_UniffiFfiConverterTypeEffectiveScope.read(buf),
            desktop_unlocked=_UniffiFfiConverterBoolean.read(buf),
            escalation_reason=_UniffiFfiConverterOptionalTypeEscalationReason.read(buf),
            escalation_detail=_UniffiFfiConverterOptionalString.read(buf),
            workspace_id=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.session)
        _UniffiFfiConverterTypeCaptureScope.check_lower(value.capture_scope)
        _UniffiFfiConverterTypeEffectiveScope.check_lower(value.effective_scope)
        _UniffiFfiConverterBoolean.check_lower(value.desktop_unlocked)
        _UniffiFfiConverterOptionalTypeEscalationReason.check_lower(value.escalation_reason)
        _UniffiFfiConverterOptionalString.check_lower(value.escalation_detail)
        _UniffiFfiConverterOptionalString.check_lower(value.workspace_id)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.session, buf)
        _UniffiFfiConverterTypeCaptureScope.write(value.capture_scope, buf)
        _UniffiFfiConverterTypeEffectiveScope.write(value.effective_scope, buf)
        _UniffiFfiConverterBoolean.write(value.desktop_unlocked, buf)
        _UniffiFfiConverterOptionalTypeEscalationReason.write(value.escalation_reason, buf)
        _UniffiFfiConverterOptionalString.write(value.escalation_detail, buf)
        _UniffiFfiConverterOptionalString.write(value.workspace_id, buf)

class _UniffiFfiConverterOptionalTypeCaptureScope(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeCaptureScope.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeCaptureScope.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeCaptureScope.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class StartSessionInput:
    def __init__(self, *, session:str, capture_scope:typing.Optional[CaptureScope], workspace_id:typing.Optional[str]):
        self.session = session
        self.capture_scope = capture_scope
        self.workspace_id = workspace_id




    def __str__(self):
        return "StartSessionInput(session={}, capture_scope={}, workspace_id={})".format(self.session, self.capture_scope, self.workspace_id)
    def __eq__(self, other):
        if self.session != other.session:
            return False
        if self.capture_scope != other.capture_scope:
            return False
        if self.workspace_id != other.workspace_id:
            return False
        return True

class _UniffiFfiConverterTypeStartSessionInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return StartSessionInput(
            session=_UniffiFfiConverterString.read(buf),
            capture_scope=_UniffiFfiConverterOptionalTypeCaptureScope.read(buf),
            workspace_id=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.session)
        _UniffiFfiConverterOptionalTypeCaptureScope.check_lower(value.capture_scope)
        _UniffiFfiConverterOptionalString.check_lower(value.workspace_id)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.session, buf)
        _UniffiFfiConverterOptionalTypeCaptureScope.write(value.capture_scope, buf)
        _UniffiFfiConverterOptionalString.write(value.workspace_id, buf)

@dataclass
class StartSessionOutput:
    """
    Successful structured result returned by `start_session`.
"""
    def __init__(self, *, state:SessionStateOutput, active:bool, revived:bool):
        self.state = state
        self.active = active
        self.revived = revived




    def __str__(self):
        return "StartSessionOutput(state={}, active={}, revived={})".format(self.state, self.active, self.revived)
    def __eq__(self, other):
        if self.state != other.state:
            return False
        if self.active != other.active:
            return False
        if self.revived != other.revived:
            return False
        return True

class _UniffiFfiConverterTypeStartSessionOutput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return StartSessionOutput(
            state=_UniffiFfiConverterTypeSessionStateOutput.read(buf),
            active=_UniffiFfiConverterBoolean.read(buf),
            revived=_UniffiFfiConverterBoolean.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterTypeSessionStateOutput.check_lower(value.state)
        _UniffiFfiConverterBoolean.check_lower(value.active)
        _UniffiFfiConverterBoolean.check_lower(value.revived)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterTypeSessionStateOutput.write(value.state, buf)
        _UniffiFfiConverterBoolean.write(value.active, buf)
        _UniffiFfiConverterBoolean.write(value.revived, buf)

@dataclass
class TypeTextInput:
    def __init__(self, *, text:str, scope:DesktopScope, session:typing.Optional[str]):
        self.text = text
        self.scope = scope
        self.session = session




    def __str__(self):
        return "TypeTextInput(text={}, scope={}, session={})".format(self.text, self.scope, self.session)
    def __eq__(self, other):
        if self.text != other.text:
            return False
        if self.scope != other.scope:
            return False
        if self.session != other.session:
            return False
        return True

class _UniffiFfiConverterTypeTypeTextInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return TypeTextInput(
            text=_UniffiFfiConverterString.read(buf),
            scope=_UniffiFfiConverterTypeDesktopScope.read(buf),
            session=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.text)
        _UniffiFfiConverterTypeDesktopScope.check_lower(value.scope)
        _UniffiFfiConverterOptionalString.check_lower(value.session)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.text, buf)
        _UniffiFfiConverterTypeDesktopScope.write(value.scope, buf)
        _UniffiFfiConverterOptionalString.write(value.session, buf)






class Platform(enum.Enum):

    MACOS = 0

    WINDOWS = 1

    LINUX = 2



class _UniffiFfiConverterTypePlatform(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Platform.MACOS
        if variant == 2:
            return Platform.WINDOWS
        if variant == 3:
            return Platform.LINUX
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Platform.MACOS:
            return
        if value == Platform.WINDOWS:
            return
        if value == Platform.LINUX:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Platform.MACOS:
            buf.write_i32(1)
        if value == Platform.WINDOWS:
            buf.write_i32(2)
        if value == Platform.LINUX:
            buf.write_i32(3)



class _UniffiFfiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)

__all__ = [
    "InternalError",
    "DesktopScope",
    "ClickButton",
    "EscalationReason",
    "ScrollDirection",
    "ScrollBy",
    "CaptureScope",
    "EffectiveScope",
    "Platform",
    "ClickInput",
    "DragInput",
    "EndSessionInput",
    "EndSessionOutput",
    "EscalateSessionInput",
    "GetCursorPositionInput",
    "GetDesktopStateInput",
    "GetScreenSizeInput",
    "GetSessionStateInput",
    "HotkeyInput",
    "MoveCursorInput",
    "PressKeyInput",
    "ScrollInput",
    "SessionStateOutput",
    "StartSessionInput",
    "StartSessionOutput",
    "TypeTextInput",
]
