// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import nativeModule from "./cyclops_sdk-ffi";
import { type UniffiRustFutureContinuationCallback, type UniffiForeignFutureDroppedCallback, type UniffiForeignFutureDroppedCallbackStruct, type UniffiForeignFutureResultRustBuffer, type UniffiForeignFutureCompleterustBuffer, type UniffiVTableCallbackInterfaceCyclopsSdkHttpClient,
} from "./cyclops_sdk-ffi";
import { type ClaimSpec, type OsGymSandboxClaimStatus, type OsGymWorkspacePoolStatus, type PoolSpec,
} from "./cyclops_sdk_schema";
import { type FfiConverter, type UniffiByteArray, type UniffiGcObject, type UniffiHandle, type UniffiObjectFactory, type UniffiReferenceHolder, type UniffiRustCallStatus, AbstractFfiConverterByteArray, FfiConverterArray, FfiConverterArrayBuffer, FfiConverterInt32, FfiConverterMap, FfiConverterObject, FfiConverterObjectWithCallbacks, FfiConverterOptional, FfiConverterUInt16, FfiConverterUInt32, FfiConverterUInt64, FfiConverterUInt8, RustBuffer, UniffiAbstractObject, UniffiError, UniffiInternalError, UniffiResult, UniffiRustCaller, destructorGuardSymbol, pointerLiteralSymbol, uniffiCreateFfiConverterString, uniffiCreateRecord, uniffiRustCallAsync, uniffiTraitInterfaceCallAsyncWithError, uniffiTypeNameSymbol, variantOrdinalSymbol,
} from "@ubjs/core";
import uniffiCyclopsSdkSchemaModule from "./cyclops_sdk_schema";
const { FfiConverterTypeClaimSpec, FfiConverterTypeOSGymSandboxClaimStatus, FfiConverterTypeOSGymWorkspacePoolStatus, FfiConverterTypePoolSpec } = uniffiCyclopsSdkSchemaModule.converters;
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== "object" ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== "production" ||
  false;

// Public interface members begin here.

const stringConverter = (() => {
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();
    return {
        stringToBytes: (s: string) => encoder.encode(s),
        bytesToString: (ab: UniffiByteArray) => decoder.decode(ab),
        stringByteLength: (s: string) => encoder.encode(s).byteLength,
        writeStringIntoBuffer: (s: string, buf: any, offset: number): number => {
            const view = new Uint8Array(
                buf.arrayBuffer,
                offset,
                buf.arrayBuffer.byteLength - offset,
            );
            return encoder.encodeInto(s, view).written;
        },
        readStringFromBuffer: (buf: any, offset: number, length: number): string =>
            decoder.decode(new Uint8Array(buf.arrayBuffer, offset, length)),
    };
})();
const FfiConverterString = uniffiCreateFfiConverterString(stringConverter);

export type ResourceMetadata = {
    namespace: string,
    name: string,
    labels?: Map<string, string>
}

/**
 * Generated factory for {@link ResourceMetadata} record objects.
 */
export const ResourceMetadata = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<ResourceMetadata, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<ResourceMetadata>,
    });
})();

const FfiConverterTypeResourceMetadata = (() => {
    type TypeName = ResourceMetadata;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                namespace: FfiConverterString.read(from), 
                name: FfiConverterString.read(from), 
                labels: FfiConverterOptionalMapStringString.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.namespace, into);
            FfiConverterString.write(value.name, into);
            FfiConverterOptionalMapStringString.write(value.labels, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.namespace) +
             FfiConverterString.allocationSize(value.name) +
             FfiConverterOptionalMapStringString.allocationSize(value.labels);
            
        }
    };
    return new FFIConverter();
})();

export type Claim = {
    apiVersion: string,
    kind: string,
    metadata: ResourceMetadata,
    spec: ClaimSpec,
    status?: OsGymSandboxClaimStatus
}

/**
 * Generated factory for {@link Claim} record objects.
 */
export const Claim = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<Claim, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<Claim>,
    });
})();

const FfiConverterTypeClaim = (() => {
    type TypeName = Claim;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                apiVersion: FfiConverterString.read(from), 
                kind: FfiConverterString.read(from), 
                metadata: FfiConverterTypeResourceMetadata.read(from), 
                spec: FfiConverterTypeClaimSpec.read(from), 
                status: FfiConverterOptionalTypeOSGymSandboxClaimStatus.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.apiVersion, into);
            FfiConverterString.write(value.kind, into);
            FfiConverterTypeResourceMetadata.write(value.metadata, into);
            FfiConverterTypeClaimSpec.write(value.spec, into);
            FfiConverterOptionalTypeOSGymSandboxClaimStatus.write(value.status, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.apiVersion) +
             FfiConverterString.allocationSize(value.kind) +
             FfiConverterTypeResourceMetadata.allocationSize(value.metadata) +
             FfiConverterTypeClaimSpec.allocationSize(value.spec) +
             FfiConverterOptionalTypeOSGymSandboxClaimStatus.allocationSize(value.status);
            
        }
    };
    return new FFIConverter();
})();

/**
 * UniFFI cannot emit aliases for external record types. Generated bindings use
 * `OSGymWorkspacePoolStatus` and `OSGymSandboxClaimStatus` from cyclops_sdk_schema.
 */
export type Pool = {
    apiVersion: string,
    kind: string,
    metadata: ResourceMetadata,
    spec: PoolSpec,
    status?: OsGymWorkspacePoolStatus
}

/**
 * Generated factory for {@link Pool} record objects.
 */
export const Pool = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<Pool, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<Pool>,
    });
})();

const FfiConverterTypePool = (() => {
    type TypeName = Pool;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                apiVersion: FfiConverterString.read(from), 
                kind: FfiConverterString.read(from), 
                metadata: FfiConverterTypeResourceMetadata.read(from), 
                spec: FfiConverterTypePoolSpec.read(from), 
                status: FfiConverterOptionalTypeOSGymWorkspacePoolStatus.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.apiVersion, into);
            FfiConverterString.write(value.kind, into);
            FfiConverterTypeResourceMetadata.write(value.metadata, into);
            FfiConverterTypePoolSpec.write(value.spec, into);
            FfiConverterOptionalTypeOSGymWorkspacePoolStatus.write(value.status, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.apiVersion) +
             FfiConverterString.allocationSize(value.kind) +
             FfiConverterTypeResourceMetadata.allocationSize(value.metadata) +
             FfiConverterTypePoolSpec.allocationSize(value.spec) +
             FfiConverterOptionalTypeOSGymWorkspacePoolStatus.allocationSize(value.status);
            
        }
    };
    return new FFIConverter();
})();

export type CreateClaimRequest = {
    pool: Pool,
    spec?: ClaimSpec
}

/**
 * Generated factory for {@link CreateClaimRequest} record objects.
 */
export const CreateClaimRequest = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<CreateClaimRequest, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<CreateClaimRequest>,
    });
})();

const FfiConverterTypeCreateClaimRequest = (() => {
    type TypeName = CreateClaimRequest;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                pool: FfiConverterTypePool.read(from), 
                spec: FfiConverterOptionalTypeClaimSpec.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterTypePool.write(value.pool, into);
            FfiConverterOptionalTypeClaimSpec.write(value.spec, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterTypePool.allocationSize(value.pool) +
             FfiConverterOptionalTypeClaimSpec.allocationSize(value.spec);
            
        }
    };
    return new FFIConverter();
})();

export type CreatePoolRequest = {
    namespace: string,
    spec: PoolSpec
}

/**
 * Generated factory for {@link CreatePoolRequest} record objects.
 */
export const CreatePoolRequest = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<CreatePoolRequest, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<CreatePoolRequest>,
    });
})();

const FfiConverterTypeCreatePoolRequest = (() => {
    type TypeName = CreatePoolRequest;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                namespace: FfiConverterString.read(from), 
                spec: FfiConverterTypePoolSpec.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.namespace, into);
            FfiConverterTypePoolSpec.write(value.spec, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.namespace) +
             FfiConverterTypePoolSpec.allocationSize(value.spec);
            
        }
    };
    return new FFIConverter();
})();

export interface CyclopsCredentialsLike {
    
}
/**
 * @deprecated Use `CyclopsCredentialsLike` instead.
 */
export type CyclopsCredentialsInterface = CyclopsCredentialsLike;


export class CyclopsCredentials extends UniffiAbstractObject implements CyclopsCredentialsLike {

    readonly [uniffiTypeNameSymbol] = "CyclopsCredentials";
    readonly [destructorGuardSymbol]: UniffiGcObject;
    readonly [pointerLiteralSymbol]: UniffiHandle;
    constructor(clientId: string, clientSecret: string) {
        super();
        const pointer =
            uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().uniffi_cyclops_sdk_fn_constructor_cyclopscredentials_new(
        FfiConverterString.lower(clientId, nativeModule().rustbuffer_alloc),
        FfiConverterString.lower(clientSecret, nativeModule().rustbuffer_alloc),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    );
        this[pointerLiteralSymbol] = pointer;
        this[destructorGuardSymbol] = uniffiTypeCyclopsCredentialsObjectFactory.bless(pointer);
    }

    

    

    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeCyclopsCredentialsObjectFactory.pointer(this);
            uniffiTypeCyclopsCredentialsObjectFactory.freePointer(pointer);
            uniffiTypeCyclopsCredentialsObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj_: any): obj_ is CyclopsCredentials {
        return uniffiTypeCyclopsCredentialsObjectFactory.isConcreteType(obj_);
    }

    
}

const uniffiTypeCyclopsCredentialsObjectFactory: UniffiObjectFactory<CyclopsCredentialsLike> = (() => {
    
    /// <reference lib="es2021" />
    const registry = typeof FinalizationRegistry !== 'undefined' ? new FinalizationRegistry<UniffiHandle>((heldValue: UniffiHandle) => {
        uniffiTypeCyclopsCredentialsObjectFactory.freePointer(heldValue);
    }) : null;
    
    return {
    create(pointer: UniffiHandle): CyclopsCredentialsLike {
        const instance = Object.create(CyclopsCredentials.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "CyclopsCredentials";
        return instance;
    },

    
    bless(p: UniffiHandle): UniffiGcObject {
        const ptr = {
            p, // make sure this object doesn't get optimized away.
            markDestroyed: () => undefined,
        };
        if (registry) {
            registry.register(ptr, p, ptr);
        }
        return ptr;
    },

    unbless(ptr_: UniffiGcObject) {
        if (registry) {
            registry.unregister(ptr_);
        }
    },

    pointer(obj_: CyclopsCredentialsLike): UniffiHandle {
        if ((obj_ as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj_ as any)[pointerLiteralSymbol];
    },

    clonePointer(obj_: CyclopsCredentialsLike): UniffiHandle {
        const pointer = this.pointer(obj_);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_cyclops_sdk_fn_clone_cyclopscredentials(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UniffiHandle): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_cyclops_sdk_fn_free_cyclopscredentials(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj_: any): obj_ is CyclopsCredentialsLike {
        return obj_[destructorGuardSymbol] && obj_[uniffiTypeNameSymbol] === "CyclopsCredentials";
    },
}})();
const FfiConverterTypeCyclopsCredentials = new FfiConverterObject(uniffiTypeCyclopsCredentialsObjectFactory);

export type CyclopsConfiguration = {
    baseUrl: string,
    tokenUrl: string,
    credentials: CyclopsCredentialsLike,
    poolPollIntervalMs: bigint,
    poolPollLimit: number,
    claimPollIntervalMs: bigint,
    claimPollLimit: number
}

/**
 * Generated factory for {@link CyclopsConfiguration} record objects.
 */
export const CyclopsConfiguration = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<CyclopsConfiguration, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<CyclopsConfiguration>,
    });
})();

const FfiConverterTypeCyclopsConfiguration = (() => {
    type TypeName = CyclopsConfiguration;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                baseUrl: FfiConverterString.read(from), 
                tokenUrl: FfiConverterString.read(from), 
                credentials: FfiConverterTypeCyclopsCredentials.read(from), 
                poolPollIntervalMs: FfiConverterUInt64.read(from), 
                poolPollLimit: FfiConverterUInt32.read(from), 
                claimPollIntervalMs: FfiConverterUInt64.read(from), 
                claimPollLimit: FfiConverterUInt32.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.baseUrl, into);
            FfiConverterString.write(value.tokenUrl, into);
            FfiConverterTypeCyclopsCredentials.write(value.credentials, into);
            FfiConverterUInt64.write(value.poolPollIntervalMs, into);
            FfiConverterUInt32.write(value.poolPollLimit, into);
            FfiConverterUInt64.write(value.claimPollIntervalMs, into);
            FfiConverterUInt32.write(value.claimPollLimit, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.baseUrl) +
             FfiConverterString.allocationSize(value.tokenUrl) +
             FfiConverterTypeCyclopsCredentials.allocationSize(value.credentials) +
             FfiConverterUInt64.allocationSize(value.poolPollIntervalMs) +
             FfiConverterUInt32.allocationSize(value.poolPollLimit) +
             FfiConverterUInt64.allocationSize(value.claimPollIntervalMs) +
             FfiConverterUInt32.allocationSize(value.claimPollLimit);
            
        }
    };
    return new FFIConverter();
})();

export type HttpHeader = {
    name: string,
    value: string
}

/**
 * Generated factory for {@link HttpHeader} record objects.
 */
export const HttpHeader = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<HttpHeader, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<HttpHeader>,
    });
})();

const FfiConverterTypeHttpHeader = (() => {
    type TypeName = HttpHeader;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                name: FfiConverterString.read(from), 
                value: FfiConverterString.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.name, into);
            FfiConverterString.write(value.value, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.name) +
             FfiConverterString.allocationSize(value.value);
            
        }
    };
    return new FFIConverter();
})();

export type HttpRequest = {
    method: string,
    url: string,
    headers: Array<HttpHeader>,
    body?: ArrayBuffer
}

/**
 * Generated factory for {@link HttpRequest} record objects.
 */
export const HttpRequest = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<HttpRequest, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<HttpRequest>,
    });
})();

const FfiConverterTypeHttpRequest = (() => {
    type TypeName = HttpRequest;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                method: FfiConverterString.read(from), 
                url: FfiConverterString.read(from), 
                headers: FfiConverterSequenceTypeHttpHeader.read(from), 
                body: FfiConverterOptionalBytes.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.method, into);
            FfiConverterString.write(value.url, into);
            FfiConverterSequenceTypeHttpHeader.write(value.headers, into);
            FfiConverterOptionalBytes.write(value.body, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.method) +
             FfiConverterString.allocationSize(value.url) +
             FfiConverterSequenceTypeHttpHeader.allocationSize(value.headers) +
             FfiConverterOptionalBytes.allocationSize(value.body);
            
        }
    };
    return new FFIConverter();
})();

export type HttpResponse = {
    status: number,
    headers: Array<HttpHeader>,
    body: ArrayBuffer
}

/**
 * Generated factory for {@link HttpResponse} record objects.
 */
export const HttpResponse = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<HttpResponse, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<HttpResponse>,
    });
})();

const FfiConverterTypeHttpResponse = (() => {
    type TypeName = HttpResponse;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                status: FfiConverterUInt16.read(from), 
                headers: FfiConverterSequenceTypeHttpHeader.read(from), 
                body: FfiConverterArrayBuffer.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterUInt16.write(value.status, into);
            FfiConverterSequenceTypeHttpHeader.write(value.headers, into);
            FfiConverterArrayBuffer.write(value.body, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterUInt16.allocationSize(value.status) +
             FfiConverterSequenceTypeHttpHeader.allocationSize(value.headers) +
             FfiConverterArrayBuffer.allocationSize(value.body);
            
        }
    };
    return new FFIConverter();
})();

export type Sandbox = {
    namespace: string,
    claim: string,
    name: string,
    services: Array<string>
}

/**
 * Generated factory for {@link Sandbox} record objects.
 */
export const Sandbox = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<Sandbox, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<Sandbox>,
    });
})();

const FfiConverterTypeSandbox = (() => {
    type TypeName = Sandbox;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                namespace: FfiConverterString.read(from), 
                claim: FfiConverterString.read(from), 
                name: FfiConverterString.read(from), 
                services: FfiConverterSequenceString.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterString.write(value.namespace, into);
            FfiConverterString.write(value.claim, into);
            FfiConverterString.write(value.name, into);
            FfiConverterSequenceString.write(value.services, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.namespace) +
             FfiConverterString.allocationSize(value.claim) +
             FfiConverterString.allocationSize(value.name) +
             FfiConverterSequenceString.allocationSize(value.services);
            
        }
    };
    return new FFIConverter();
})();


// Error type: HttpError
export enum HttpError_Tags {
    Transport = "Transport"
}
export const HttpError = (() => {

    type Transport__interface = {
        tag: HttpError_Tags.Transport;
        inner: 
Readonly<{reason: string}>
    };
    class Transport_ extends UniffiError implements Transport__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "HttpError";
        readonly tag = HttpError_Tags.Transport;
        readonly inner: 
Readonly<{reason: string}>;
        constructor(
inner: {reason: string }) {
            super("HttpError", "Transport");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {reason: string }): Transport_ {
            return new Transport_(inner);
        }

        static instanceOf(obj: any): obj is Transport_ {
            return obj.tag === HttpError_Tags.Transport;
        }
        static hasInner(obj: any): obj is Transport_ {
            return Transport_.instanceOf(obj);
        }

        static getInner(obj: Transport_): 
Readonly<{reason: string}> {
            return obj.inner;
        }

    }

    function instanceOf(obj: any): obj is HttpError {
        return obj[uniffiTypeNameSymbol] === "HttpError";
    }

    return Object.freeze({
        instanceOf,
  Transport: Transport_
    });

})();
export type HttpError = InstanceType<
    typeof HttpError['Transport']
>;

// FfiConverter for enum HttpError
const FfiConverterTypeHttpError = (() => {
    const ordinalConverter = FfiConverterInt32;
    type TypeName = HttpError;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            switch (ordinalConverter.read(from)) {
                case 1: return new HttpError.Transport({reason: FfiConverterString.read(from) });
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        write(value: TypeName, into: RustBuffer): void {
            switch (value.tag) {
                case HttpError_Tags.Transport: {
                    ordinalConverter.write(1, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.reason, into);
                    return;
                }
                default:
                    // Throwing from here means that HttpError_Tags hasn't matched an ordinal.
                    throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        allocationSize(value: TypeName): number {
            switch (value.tag) {
                case HttpError_Tags.Transport: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(1);
                    size += FfiConverterString.allocationSize(inner.reason);
                    return size;
                }
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
    }
    return new FFIConverter();
})();


// Error type: SdkError
export enum SdkError_Tags {
    Configuration = "Configuration",
    InvalidResourceName = "InvalidResourceName",
    Transport = "Transport",
    Token = "Token",
    Body = "Body",
    Status = "Status",
    UnknownService = "UnknownService",
    InvalidServicePath = "InvalidServicePath",
    ClaimFailed = "ClaimFailed",
    ClaimTimeout = "ClaimTimeout"
}
export const SdkError = (() => {

    type Configuration__interface = {
        tag: SdkError_Tags.Configuration;
        inner: 
Readonly<{reason: string}>
    };
    class Configuration_ extends UniffiError implements Configuration__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.Configuration;
        readonly inner: 
Readonly<{reason: string}>;
        constructor(
inner: {reason: string }) {
            super("SdkError", "Configuration");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {reason: string }): Configuration_ {
            return new Configuration_(inner);
        }

        static instanceOf(obj: any): obj is Configuration_ {
            return obj.tag === SdkError_Tags.Configuration;
        }
        static hasInner(obj: any): obj is Configuration_ {
            return Configuration_.instanceOf(obj);
        }

        static getInner(obj: Configuration_): 
Readonly<{reason: string}> {
            return obj.inner;
        }

    }

    type InvalidResourceName__interface = {
        tag: SdkError_Tags.InvalidResourceName;
        inner: 
Readonly<{field: string; value: string; reason: string}>
    };
    class InvalidResourceName_ extends UniffiError implements InvalidResourceName__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.InvalidResourceName;
        readonly inner: 
Readonly<{field: string; value: string; reason: string}>;
        constructor(
inner: {field: string; value: string; reason: string }) {
            super("SdkError", "InvalidResourceName");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {field: string; value: string; reason: string }): InvalidResourceName_ {
            return new InvalidResourceName_(inner);
        }

        static instanceOf(obj: any): obj is InvalidResourceName_ {
            return obj.tag === SdkError_Tags.InvalidResourceName;
        }
        static hasInner(obj: any): obj is InvalidResourceName_ {
            return InvalidResourceName_.instanceOf(obj);
        }

        static getInner(obj: InvalidResourceName_): 
Readonly<{field: string; value: string; reason: string}> {
            return obj.inner;
        }

    }

    type Transport__interface = {
        tag: SdkError_Tags.Transport;
        inner: 
Readonly<{reason: string}>
    };
    class Transport_ extends UniffiError implements Transport__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.Transport;
        readonly inner: 
Readonly<{reason: string}>;
        constructor(
inner: {reason: string }) {
            super("SdkError", "Transport");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {reason: string }): Transport_ {
            return new Transport_(inner);
        }

        static instanceOf(obj: any): obj is Transport_ {
            return obj.tag === SdkError_Tags.Transport;
        }
        static hasInner(obj: any): obj is Transport_ {
            return Transport_.instanceOf(obj);
        }

        static getInner(obj: Transport_): 
Readonly<{reason: string}> {
            return obj.inner;
        }

    }

    type Token__interface = {
        tag: SdkError_Tags.Token;
        inner: 
Readonly<{reason: string}>
    };
    class Token_ extends UniffiError implements Token__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.Token;
        readonly inner: 
Readonly<{reason: string}>;
        constructor(
inner: {reason: string }) {
            super("SdkError", "Token");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {reason: string }): Token_ {
            return new Token_(inner);
        }

        static instanceOf(obj: any): obj is Token_ {
            return obj.tag === SdkError_Tags.Token;
        }
        static hasInner(obj: any): obj is Token_ {
            return Token_.instanceOf(obj);
        }

        static getInner(obj: Token_): 
Readonly<{reason: string}> {
            return obj.inner;
        }

    }

    type Body__interface = {
        tag: SdkError_Tags.Body;
        inner: 
Readonly<{reason: string}>
    };
    class Body_ extends UniffiError implements Body__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.Body;
        readonly inner: 
Readonly<{reason: string}>;
        constructor(
inner: {reason: string }) {
            super("SdkError", "Body");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {reason: string }): Body_ {
            return new Body_(inner);
        }

        static instanceOf(obj: any): obj is Body_ {
            return obj.tag === SdkError_Tags.Body;
        }
        static hasInner(obj: any): obj is Body_ {
            return Body_.instanceOf(obj);
        }

        static getInner(obj: Body_): 
Readonly<{reason: string}> {
            return obj.inner;
        }

    }

    type Status__interface = {
        tag: SdkError_Tags.Status;
        inner: 
Readonly<{operation: string; status: number; body: string}>
    };
    class Status_ extends UniffiError implements Status__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.Status;
        readonly inner: 
Readonly<{operation: string; status: number; body: string}>;
        constructor(
inner: {operation: string; status: number; body: string }) {
            super("SdkError", "Status");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {operation: string; status: number; body: string }): Status_ {
            return new Status_(inner);
        }

        static instanceOf(obj: any): obj is Status_ {
            return obj.tag === SdkError_Tags.Status;
        }
        static hasInner(obj: any): obj is Status_ {
            return Status_.instanceOf(obj);
        }

        static getInner(obj: Status_): 
Readonly<{operation: string; status: number; body: string}> {
            return obj.inner;
        }

    }

    type UnknownService__interface = {
        tag: SdkError_Tags.UnknownService;
        inner: 
Readonly<{requested: string; available: Array<string>}>
    };
    class UnknownService_ extends UniffiError implements UnknownService__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.UnknownService;
        readonly inner: 
Readonly<{requested: string; available: Array<string>}>;
        constructor(
inner: {requested: string; available: Array<string> }) {
            super("SdkError", "UnknownService");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {requested: string; available: Array<string> }): UnknownService_ {
            return new UnknownService_(inner);
        }

        static instanceOf(obj: any): obj is UnknownService_ {
            return obj.tag === SdkError_Tags.UnknownService;
        }
        static hasInner(obj: any): obj is UnknownService_ {
            return UnknownService_.instanceOf(obj);
        }

        static getInner(obj: UnknownService_): 
Readonly<{requested: string; available: Array<string>}> {
            return obj.inner;
        }

    }

    type InvalidServicePath__interface = {
        tag: SdkError_Tags.InvalidServicePath;
        inner: 
Readonly<{path: string}>
    };
    class InvalidServicePath_ extends UniffiError implements InvalidServicePath__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.InvalidServicePath;
        readonly inner: 
Readonly<{path: string}>;
        constructor(
inner: {path: string }) {
            super("SdkError", "InvalidServicePath");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {path: string }): InvalidServicePath_ {
            return new InvalidServicePath_(inner);
        }

        static instanceOf(obj: any): obj is InvalidServicePath_ {
            return obj.tag === SdkError_Tags.InvalidServicePath;
        }
        static hasInner(obj: any): obj is InvalidServicePath_ {
            return InvalidServicePath_.instanceOf(obj);
        }

        static getInner(obj: InvalidServicePath_): 
Readonly<{path: string}> {
            return obj.inner;
        }

    }

    type ClaimFailed__interface = {
        tag: SdkError_Tags.ClaimFailed;
        inner: 
Readonly<{phase: string; status: string}>
    };
    class ClaimFailed_ extends UniffiError implements ClaimFailed__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.ClaimFailed;
        readonly inner: 
Readonly<{phase: string; status: string}>;
        constructor(
inner: {phase: string; status: string }) {
            super("SdkError", "ClaimFailed");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {phase: string; status: string }): ClaimFailed_ {
            return new ClaimFailed_(inner);
        }

        static instanceOf(obj: any): obj is ClaimFailed_ {
            return obj.tag === SdkError_Tags.ClaimFailed;
        }
        static hasInner(obj: any): obj is ClaimFailed_ {
            return ClaimFailed_.instanceOf(obj);
        }

        static getInner(obj: ClaimFailed_): 
Readonly<{phase: string; status: string}> {
            return obj.inner;
        }

    }

    type ClaimTimeout__interface = {
        tag: SdkError_Tags.ClaimTimeout
    };
    class ClaimTimeout_ extends UniffiError implements ClaimTimeout__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "SdkError";
        readonly tag = SdkError_Tags.ClaimTimeout;
        constructor() {
            super("SdkError", "ClaimTimeout");
        }

        static new(): ClaimTimeout_ {
            return new ClaimTimeout_();
        }

        static instanceOf(obj: any): obj is ClaimTimeout_ {
            return obj.tag === SdkError_Tags.ClaimTimeout;
        }
        static hasInner(obj: any): obj is ClaimTimeout_ {
            return false;
        }

    }

    function instanceOf(obj: any): obj is SdkError {
        return obj[uniffiTypeNameSymbol] === "SdkError";
    }

    return Object.freeze({
        instanceOf,
  Configuration: Configuration_, 
  InvalidResourceName: InvalidResourceName_, 
  Transport: Transport_, 
  Token: Token_, 
  Body: Body_, 
  Status: Status_, 
  UnknownService: UnknownService_, 
  InvalidServicePath: InvalidServicePath_, 
  ClaimFailed: ClaimFailed_, 
  ClaimTimeout: ClaimTimeout_
    });

})();
export type SdkError = InstanceType<
    typeof SdkError['Configuration' | 'InvalidResourceName' | 'Transport' | 'Token' | 'Body' | 'Status' | 'UnknownService' | 'InvalidServicePath' | 'ClaimFailed' | 'ClaimTimeout']
>;

// FfiConverter for enum SdkError
const FfiConverterTypeSdkError = (() => {
    const ordinalConverter = FfiConverterInt32;
    type TypeName = SdkError;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            switch (ordinalConverter.read(from)) {
                case 1: return new SdkError.Configuration({reason: FfiConverterString.read(from) });
                case 2: return new SdkError.InvalidResourceName({field: FfiConverterString.read(from), value: FfiConverterString.read(from), reason: FfiConverterString.read(from) });
                case 3: return new SdkError.Transport({reason: FfiConverterString.read(from) });
                case 4: return new SdkError.Token({reason: FfiConverterString.read(from) });
                case 5: return new SdkError.Body({reason: FfiConverterString.read(from) });
                case 6: return new SdkError.Status({operation: FfiConverterString.read(from), status: FfiConverterUInt16.read(from), body: FfiConverterString.read(from) });
                case 7: return new SdkError.UnknownService({requested: FfiConverterString.read(from), available: FfiConverterSequenceString.read(from) });
                case 8: return new SdkError.InvalidServicePath({path: FfiConverterString.read(from) });
                case 9: return new SdkError.ClaimFailed({phase: FfiConverterString.read(from), status: FfiConverterString.read(from) });
                case 10: return new SdkError.ClaimTimeout();
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        write(value: TypeName, into: RustBuffer): void {
            switch (value.tag) {
                case SdkError_Tags.Configuration: {
                    ordinalConverter.write(1, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.reason, into);
                    return;
                }
                case SdkError_Tags.InvalidResourceName: {
                    ordinalConverter.write(2, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.field, into);
                    FfiConverterString.write(inner.value, into);
                    FfiConverterString.write(inner.reason, into);
                    return;
                }
                case SdkError_Tags.Transport: {
                    ordinalConverter.write(3, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.reason, into);
                    return;
                }
                case SdkError_Tags.Token: {
                    ordinalConverter.write(4, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.reason, into);
                    return;
                }
                case SdkError_Tags.Body: {
                    ordinalConverter.write(5, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.reason, into);
                    return;
                }
                case SdkError_Tags.Status: {
                    ordinalConverter.write(6, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.operation, into);
                    FfiConverterUInt16.write(inner.status, into);
                    FfiConverterString.write(inner.body, into);
                    return;
                }
                case SdkError_Tags.UnknownService: {
                    ordinalConverter.write(7, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.requested, into);
                    FfiConverterSequenceString.write(inner.available, into);
                    return;
                }
                case SdkError_Tags.InvalidServicePath: {
                    ordinalConverter.write(8, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.path, into);
                    return;
                }
                case SdkError_Tags.ClaimFailed: {
                    ordinalConverter.write(9, into);
                    const inner = value.inner;
                    FfiConverterString.write(inner.phase, into);
                    FfiConverterString.write(inner.status, into);
                    return;
                }
                case SdkError_Tags.ClaimTimeout: {
                    ordinalConverter.write(10, into);
                    return;
                }
                default:
                    // Throwing from here means that SdkError_Tags hasn't matched an ordinal.
                    throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        allocationSize(value: TypeName): number {
            switch (value.tag) {
                case SdkError_Tags.Configuration: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(1);
                    size += FfiConverterString.allocationSize(inner.reason);
                    return size;
                }
                case SdkError_Tags.InvalidResourceName: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(2);
                    size += FfiConverterString.allocationSize(inner.field);
                    size += FfiConverterString.allocationSize(inner.value);
                    size += FfiConverterString.allocationSize(inner.reason);
                    return size;
                }
                case SdkError_Tags.Transport: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(3);
                    size += FfiConverterString.allocationSize(inner.reason);
                    return size;
                }
                case SdkError_Tags.Token: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(4);
                    size += FfiConverterString.allocationSize(inner.reason);
                    return size;
                }
                case SdkError_Tags.Body: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(5);
                    size += FfiConverterString.allocationSize(inner.reason);
                    return size;
                }
                case SdkError_Tags.Status: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(6);
                    size += FfiConverterString.allocationSize(inner.operation);
                    size += FfiConverterUInt16.allocationSize(inner.status);
                    size += FfiConverterString.allocationSize(inner.body);
                    return size;
                }
                case SdkError_Tags.UnknownService: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(7);
                    size += FfiConverterString.allocationSize(inner.requested);
                    size += FfiConverterSequenceString.allocationSize(inner.available);
                    return size;
                }
                case SdkError_Tags.InvalidServicePath: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(8);
                    size += FfiConverterString.allocationSize(inner.path);
                    return size;
                }
                case SdkError_Tags.ClaimFailed: {
                    const inner = value.inner;
                    let size = ordinalConverter.allocationSize(9);
                    size += FfiConverterString.allocationSize(inner.phase);
                    size += FfiConverterString.allocationSize(inner.status);
                    return size;
                }
                case SdkError_Tags.ClaimTimeout: {
                    return ordinalConverter.allocationSize(10);
                }
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
    }
    return new FFIConverter();
})();

export interface CyclopsClientLike {
    
    createClaim(request: CreateClaimRequest, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Claim>;
    createPool(request: CreatePoolRequest, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Pool>;
    deleteClaim(claim: Claim, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    deletePool(pool: Pool, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    getClaim(claim: Claim, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Claim>;
    getPool(pool: Pool, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Pool>;
    listClaims(namespace: string, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Array<Claim>>;
    listPools(namespace: string, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Array<Pool>>;
    serviceRequest(sandbox: Sandbox, service: string, path: string, request: HttpRequest, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<HttpResponse>;
    updatePool(pool: Pool, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Pool>;
    waitClaim(claim: Claim, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<Sandbox>;
}
/**
 * @deprecated Use `CyclopsClientLike` instead.
 */
export type CyclopsClientInterface = CyclopsClientLike;


export class CyclopsClient extends UniffiAbstractObject implements CyclopsClientLike {

    readonly [uniffiTypeNameSymbol] = "CyclopsClient";
    readonly [destructorGuardSymbol]: UniffiGcObject;
    readonly [pointerLiteralSymbol]: UniffiHandle;
    // No primary constructor declared for this class.
private constructor(pointer: UniffiHandle) {
    super();
    this[pointerLiteralSymbol] = pointer;
    this[destructorGuardSymbol] = uniffiTypeCyclopsClientObjectFactory.bless(pointer);
}

    
    static connect(configuration: CyclopsConfiguration, httpClient: HttpClient): CyclopsClientLike /*throws*/ {
    return FfiConverterTypeCyclopsClient.lift(uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError),
            /*caller:*/ (callStatus) => {
                return nativeModule().uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect(
        FfiConverterTypeCyclopsConfiguration.lower(configuration, nativeModule().rustbuffer_alloc),
        FfiConverterTypeHttpClient.lower(httpClient, nativeModule().rustbuffer_alloc),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    ));
    }
    

    
    async createClaim(request: CreateClaimRequest, asyncOpts_?: { signal: AbortSignal }): Promise<Claim> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_create_claim(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypeCreateClaimRequest.lower(request, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypeClaim.lift.bind(FfiConverterTypeClaim),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async createPool(request: CreatePoolRequest, asyncOpts_?: { signal: AbortSignal }): Promise<Pool> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_create_pool(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypeCreatePoolRequest.lower(request, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypePool.lift.bind(FfiConverterTypePool),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async deleteClaim(claim: Claim, asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_claim(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypeClaim.lower(claim, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async deletePool(pool: Pool, asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_pool(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypePool.lower(pool, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async getClaim(claim: Claim, asyncOpts_?: { signal: AbortSignal }): Promise<Claim> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_get_claim(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypeClaim.lower(claim, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypeClaim.lift.bind(FfiConverterTypeClaim),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async getPool(pool: Pool, asyncOpts_?: { signal: AbortSignal }): Promise<Pool> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_get_pool(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypePool.lower(pool, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypePool.lift.bind(FfiConverterTypePool),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async listClaims(namespace: string, asyncOpts_?: { signal: AbortSignal }): Promise<Array<Claim>> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_list_claims(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterString.lower(namespace, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterSequenceTypeClaim.lift.bind(FfiConverterSequenceTypeClaim),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async listPools(namespace: string, asyncOpts_?: { signal: AbortSignal }): Promise<Array<Pool>> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_list_pools(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterString.lower(namespace, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterSequenceTypePool.lift.bind(FfiConverterSequenceTypePool),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async serviceRequest(sandbox: Sandbox, service: string, path: string, request: HttpRequest, asyncOpts_?: { signal: AbortSignal }): Promise<HttpResponse> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_service_request(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypeSandbox.lower(sandbox, nativeModule().rustbuffer_alloc),FfiConverterString.lower(service, nativeModule().rustbuffer_alloc),FfiConverterString.lower(path, nativeModule().rustbuffer_alloc),FfiConverterTypeHttpRequest.lower(request, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypeHttpResponse.lift.bind(FfiConverterTypeHttpResponse),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async updatePool(pool: Pool, asyncOpts_?: { signal: AbortSignal }): Promise<Pool> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_update_pool(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypePool.lower(pool, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypePool.lift.bind(FfiConverterTypePool),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async waitClaim(claim: Claim, asyncOpts_?: { signal: AbortSignal }): Promise<Sandbox> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_cyclopsclient_wait_claim(
                    uniffiTypeCyclopsClientObjectFactory.clonePointer(this),FfiConverterTypeClaim.lower(claim, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypeSandbox.lift.bind(FfiConverterTypeSandbox),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeSdkError.lift.bind(FfiConverterTypeSdkError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    

    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeCyclopsClientObjectFactory.pointer(this);
            uniffiTypeCyclopsClientObjectFactory.freePointer(pointer);
            uniffiTypeCyclopsClientObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj_: any): obj_ is CyclopsClient {
        return uniffiTypeCyclopsClientObjectFactory.isConcreteType(obj_);
    }

    
}

const uniffiTypeCyclopsClientObjectFactory: UniffiObjectFactory<CyclopsClientLike> = (() => {
    
    /// <reference lib="es2021" />
    const registry = typeof FinalizationRegistry !== 'undefined' ? new FinalizationRegistry<UniffiHandle>((heldValue: UniffiHandle) => {
        uniffiTypeCyclopsClientObjectFactory.freePointer(heldValue);
    }) : null;
    
    return {
    create(pointer: UniffiHandle): CyclopsClientLike {
        const instance = Object.create(CyclopsClient.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "CyclopsClient";
        return instance;
    },

    
    bless(p: UniffiHandle): UniffiGcObject {
        const ptr = {
            p, // make sure this object doesn't get optimized away.
            markDestroyed: () => undefined,
        };
        if (registry) {
            registry.register(ptr, p, ptr);
        }
        return ptr;
    },

    unbless(ptr_: UniffiGcObject) {
        if (registry) {
            registry.unregister(ptr_);
        }
    },

    pointer(obj_: CyclopsClientLike): UniffiHandle {
        if ((obj_ as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj_ as any)[pointerLiteralSymbol];
    },

    clonePointer(obj_: CyclopsClientLike): UniffiHandle {
        const pointer = this.pointer(obj_);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_cyclops_sdk_fn_clone_cyclopsclient(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UniffiHandle): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_cyclops_sdk_fn_free_cyclopsclient(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj_: any): obj_ is CyclopsClientLike {
        return obj_[destructorGuardSymbol] && obj_[uniffiTypeNameSymbol] === "CyclopsClient";
    },
}})();
const FfiConverterTypeCyclopsClient = new FfiConverterObject(uniffiTypeCyclopsClientObjectFactory);

export interface HttpClient {
    
    execute(request: HttpRequest, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<HttpResponse>;
}


export class HttpClientImpl extends UniffiAbstractObject implements HttpClient {

    readonly [uniffiTypeNameSymbol] = "HttpClientImpl";
    readonly [destructorGuardSymbol]: UniffiGcObject;
    readonly [pointerLiteralSymbol]: UniffiHandle;
    // No primary constructor declared for this class.
private constructor(pointer: UniffiHandle) {
    super();
    this[pointerLiteralSymbol] = pointer;
    this[destructorGuardSymbol] = uniffiTypeHttpClientImplObjectFactory.bless(pointer);
}

    

    
    async execute(request: HttpRequest, asyncOpts_?: { signal: AbortSignal }): Promise<HttpResponse> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_cyclops_sdk_fn_method_httpclient_execute(
                    uniffiTypeHttpClientImplObjectFactory.clonePointer(this),FfiConverterTypeHttpRequest.lower(request, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_cyclops_sdk_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypeHttpResponse.lift.bind(FfiConverterTypeHttpResponse),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeHttpError.lift.bind(FfiConverterTypeHttpError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    

    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeHttpClientImplObjectFactory.pointer(this);
            uniffiTypeHttpClientImplObjectFactory.freePointer(pointer);
            uniffiTypeHttpClientImplObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj_: any): obj_ is HttpClientImpl {
        return uniffiTypeHttpClientImplObjectFactory.isConcreteType(obj_);
    }

    
}

const uniffiTypeHttpClientImplObjectFactory: UniffiObjectFactory<HttpClient> = (() => {
    
    /// <reference lib="es2021" />
    const registry = typeof FinalizationRegistry !== 'undefined' ? new FinalizationRegistry<UniffiHandle>((heldValue: UniffiHandle) => {
        uniffiTypeHttpClientImplObjectFactory.freePointer(heldValue);
    }) : null;
    
    return {
    create(pointer: UniffiHandle): HttpClient {
        const instance = Object.create(HttpClientImpl.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "HttpClientImpl";
        return instance;
    },

    
    bless(p: UniffiHandle): UniffiGcObject {
        const ptr = {
            p, // make sure this object doesn't get optimized away.
            markDestroyed: () => undefined,
        };
        if (registry) {
            registry.register(ptr, p, ptr);
        }
        return ptr;
    },

    unbless(ptr_: UniffiGcObject) {
        if (registry) {
            registry.unregister(ptr_);
        }
    },

    pointer(obj_: HttpClient): UniffiHandle {
        if ((obj_ as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj_ as any)[pointerLiteralSymbol];
    },

    clonePointer(obj_: HttpClient): UniffiHandle {
        const pointer = this.pointer(obj_);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_cyclops_sdk_fn_clone_httpclient(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UniffiHandle): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_cyclops_sdk_fn_free_httpclient(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj_: any): obj_ is HttpClient {
        return obj_[destructorGuardSymbol] && obj_[uniffiTypeNameSymbol] === "HttpClientImpl";
    },
}})();
const FfiConverterTypeHttpClient = new FfiConverterObjectWithCallbacks(uniffiTypeHttpClientImplObjectFactory);

// Add a vtable for the callbacks that go in HttpClient.

// Put the implementation in a struct so we don't pollute the top-level namespace
const uniffiCallbackInterfaceHttpClient: { vtable: any; register: () => void; } = {
    // Create the VTable using a series of closures.
    // ts automatically converts these into C callback functions.
    vtable: {
        execute: (
            uniffiHandle: bigint,
            request: Uint8Array,
            uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer,
            uniffiCallbackData: bigint) => {
            const uniffiMakeCall = 
            async (signal: AbortSignal)
            : Promise<HttpResponse> => {
                const jsCallback = FfiConverterTypeHttpClient.lift(uniffiHandle);
                return await jsCallback.execute(
                    FfiConverterTypeHttpRequest.lift(request), { signal }
                )
            };
            const uniffiHandleSuccess = (returnValue: HttpResponse) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultRustBuffer */{
                        return_value: FfiConverterTypeHttpResponse.lower(returnValue, nativeModule().rustbuffer_alloc),
                        call_status: uniffiCaller.createCallStatus()
                    }
                );
            };
            const uniffiHandleError = (code: number, errorBuf: UniffiByteArray) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultRustBuffer */{
                        return_value: /*empty*/ new Uint8Array(0),
                        // TODO create callstatus with error.
                        call_status: uniffiCaller.createErrorStatus(code, errorBuf),
                    }
                );
            };
            const uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*isErrorType:*/ HttpError.instanceOf,
                /*lowerError:*/ FfiConverterTypeHttpError.lower.bind(FfiConverterTypeHttpError),
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            );
            return uniffiForeignFuture;
        },
        uniffi_free: (uniffiHandle: UniffiHandle): void => {
            // this will throw a stale handle error if the handle isn't found.
            FfiConverterTypeHttpClient.drop(uniffiHandle);
        },
        uniffi_clone: (uniffiHandle: UniffiHandle): UniffiHandle => {
            return FfiConverterTypeHttpClient.clone(uniffiHandle);
        }
    },
    register: () => {nativeModule().uniffi_cyclops_sdk_fn_init_callback_vtable_httpclient(
            uniffiCallbackInterfaceHttpClient.vtable
        );
    },
};

// FfiConverter for Map<string, string>
const FfiConverterMapStringString = new FfiConverterMap(FfiConverterString, FfiConverterString);

// FfiConverter for Map<string, string> | undefined
const FfiConverterOptionalMapStringString = new FfiConverterOptional(FfiConverterMapStringString);

// FfiConverter for OsGymSandboxClaimStatus | undefined
const FfiConverterOptionalTypeOSGymSandboxClaimStatus = new FfiConverterOptional(FfiConverterTypeOSGymSandboxClaimStatus);

// FfiConverter for OsGymWorkspacePoolStatus | undefined
const FfiConverterOptionalTypeOSGymWorkspacePoolStatus = new FfiConverterOptional(FfiConverterTypeOSGymWorkspacePoolStatus);

// FfiConverter for ClaimSpec | undefined
const FfiConverterOptionalTypeClaimSpec = new FfiConverterOptional(FfiConverterTypeClaimSpec);

// FfiConverter for Array<HttpHeader>
const FfiConverterSequenceTypeHttpHeader = new FfiConverterArray(FfiConverterTypeHttpHeader);

// FfiConverter for ArrayBuffer | undefined
const FfiConverterOptionalBytes = new FfiConverterOptional(FfiConverterArrayBuffer);

// FfiConverter for Array<string>
const FfiConverterSequenceString = new FfiConverterArray(FfiConverterString);

// FfiConverter for Array<Claim>
const FfiConverterSequenceTypeClaim = new FfiConverterArray(FfiConverterTypeClaim);

// FfiConverter for Array<Pool>
const FfiConverterSequenceTypePool = new FfiConverterArray(FfiConverterTypePool);


/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
    // Get the bindings contract version from our ComponentInterface
    const bindingsContractVersion = 30;
    // Get the scaffolding contract version by calling the into the dylib
    const scaffoldingContractVersion = nativeModule().ffi_cyclops_sdk_uniffi_contract_version();
    if (bindingsContractVersion !== scaffoldingContractVersion) {
        throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect() !== 54404) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_claim() !== 23330) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_claim");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_pool() !== 48557) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_pool");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_claim() !== 20460) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_claim");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_pool() !== 31235) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_pool");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_claim() !== 17760) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_claim");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_pool() !== 43327) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_pool");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_claims() !== 7802) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_claims");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_pools() !== 27984) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_pools");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_service_request() !== 46699) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_service_request");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_update_pool() !== 17695) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_update_pool");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_cyclopsclient_wait_claim() !== 18984) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_cyclopsclient_wait_claim");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_constructor_cyclopscredentials_new() !== 25746) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_constructor_cyclopscredentials_new");
    }
    if (nativeModule().uniffi_cyclops_sdk_checksum_method_httpclient_execute() !== 38803) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_cyclops_sdk_checksum_method_httpclient_execute");
    }

    uniffiCallbackInterfaceHttpClient.register();
    }

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeClaim,
    FfiConverterTypeCreateClaimRequest,
    FfiConverterTypeCreatePoolRequest,
    FfiConverterTypeCyclopsClient,
    FfiConverterTypeCyclopsConfiguration,
    FfiConverterTypeCyclopsCredentials,
    FfiConverterTypeHttpClient,
    FfiConverterTypeHttpError,
    FfiConverterTypeHttpHeader,
    FfiConverterTypeHttpRequest,
    FfiConverterTypeHttpResponse,
    FfiConverterTypePool,
    FfiConverterTypeResourceMetadata,
    FfiConverterTypeSandbox,
    FfiConverterTypeSdkError,
  }
});