#!/usr/bin/env python3
# SPDX-License-Identifier: FSL-1.1-MIT
# Copyright (c) 2026 Cua AI, Inc.

"""Writes the Cua Spaces icon sources from the Cua mark.

- src-tauri/icons/app-icon.svg: the app / Dock icon. The onboarding's
  SpacesStackMark (the white Cua mark in three stacked, overlapping rounded
  squares) on an opaque macOS-style rounded-square background.
- src-tauri/icons/tray-template.svg: the menu bar item, the same stack as a
  black-on-transparent template image (macOS tints it).
- ../cua-spaces-macos/Sources/CuaSpacesMacKit/Resources/stack-mark.svg: the
  SwiftUI app's onboarding mark, the app icon's stack without its tile.
  (That app's bundle also copies icon.icns and tray-template*.png from
  src-tauri/icons, so both apps ship one set of assets.)

Then rasterize (resvg, via the Tauri CLI), from apps/cua-spaces:

    python3 scripts/icons/gen-icon-svgs.py
    pnpm tauri icon src-tauri/icons/app-icon.svg -o src-tauri/icons
    pnpm tauri icon src-tauri/icons/tray-template.svg -o <tmp> -p 18 -p 36
    # copy <tmp>/18x18.png and 36x36.png to tray-template.png / tray-template@2x.png
"""
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
APP = HERE.parent.parent
MARK = APP / "src/assets/brand/cua-mark-white.svg"
ICONS = APP / "src-tauri/icons"
MARK_VIEW = "0 0 1117.09 1117.09"

paths = re.findall(r'\sd="([^"]+)"', MARK.read_text(), re.S)
assert paths, "no paths in the Cua mark"


def mark(x, y, size, fill):
    body = "".join(f'<path d="{" ".join(d.split())}"/>' for d in paths)
    return (f'<svg x="{x:g}" y="{y:g}" width="{size:g}" height="{size:g}" viewBox="{MARK_VIEW}">'
            f'<g fill="{fill}">{body}</g></svg>')


# The SpacesStackMark geometry (SIDE 84, RADIUS 20, LOGO 50, offsets 0/18/36).
SIDE, RADIUS, LOGO, OFFSETS = 84, 20, 50, (0, 18, 36)


def app_icon():
    s = 2.4
    side, r, logo = SIDE * s, RADIUS * s, LOGO * s
    extent = side + OFFSETS[-1] * s
    x0 = (512 - extent) / 2
    fills = ("#3a3d45", "#4d515a", "#626772")
    shadows = (0.30, 0.38, 0.46)
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">',
           "<!-- Generated by scripts/icons/gen-icon-svgs.py; edit that, not this. -->",
           "<defs>",
           '<linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">'
           '<stop offset="0" stop-color="#2a2c32"/><stop offset="1" stop-color="#0d0e11"/></linearGradient>']
    for i, sh in enumerate(shadows):
        out.append(f'<filter id="sh{i}" x="-30%" y="-30%" width="160%" height="160%">'
                   f'<feDropShadow dx="0" dy="6" stdDeviation="7" flood-color="#000" flood-opacity="{sh}"/></filter>')
    out.append("</defs>")
    # macOS icon grid: an 824/1024 rounded square, centred.
    out.append('<rect x="50" y="50" width="412" height="412" rx="92" fill="url(#bg)"/>')
    out.append('<rect x="50.75" y="50.75" width="410.5" height="410.5" rx="91.25" fill="none" '
               'stroke="#ffffff" stroke-opacity=".10" stroke-width="1.5"/>')
    for i, off in enumerate(OFFSETS):
        x = y = x0 + off * s
        out.append(f'<rect x="{x:g}" y="{y:g}" width="{side:g}" height="{side:g}" rx="{r:g}" '
                   f'fill="{fills[i]}" stroke="#ffffff" stroke-opacity=".14" stroke-width="1.5" filter="url(#sh{i})"/>')
        out.append(mark(x + (side - logo) / 2, y + (side - logo) / 2, logo, "#ffffff"))
    out.append("</svg>")
    return "\n".join(out) + "\n"


def stack_mark():
    s = 2.4
    side, r, logo = SIDE * s, RADIUS * s, LOGO * s
    extent = side + OFFSETS[-1] * s
    fills = ("#3a3d45", "#4d515a", "#626772")
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="-12 -12 {extent + 24:g} {extent + 24:g}">',
           "<!-- Generated by apps/cua-spaces/scripts/icons/gen-icon-svgs.py; edit that, not this. -->"]
    for i, off in enumerate(OFFSETS):
        x = y = off * s
        out.append(f'<rect x="{x:g}" y="{y:g}" width="{side:g}" height="{side:g}" rx="{r:g}" '
                   f'fill="{fills[i]}" stroke="#ffffff" stroke-opacity=".14" stroke-width="1.5"/>')
        out.append(mark(x + (side - logo) / 2, y + (side - logo) / 2, logo, "#ffffff"))
    out.append("</svg>")
    return "\n".join(out) + "\n"


def tray_icon():
    # 36 x 36 canvas (18 pt @2x). Each square cuts a gap into the one behind
    # it, and the front square cuts out the mark, so it reads at 18 pt.
    side, r, gap, logo = 22.0, 5.5, 1.6, 15.5
    offs = (1.0, 7.0, 13.0)
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36">',
           "<!-- Generated by scripts/icons/gen-icon-svgs.py; edit that, not this. -->",
           "<defs>"]
    for i in range(2):
        n = offs[i + 1]
        out.append(f'<mask id="m{i}" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36">'
                   '<rect width="36" height="36" fill="#fff"/>'
                   f'<rect x="{n - gap:g}" y="{n - gap:g}" width="{side + 2 * gap:g}" height="{side + 2 * gap:g}" '
                   f'rx="{r + gap:g}" fill="#000"/></mask>')
    f = offs[2]
    out.append('<mask id="m2" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36">'
               '<rect width="36" height="36" fill="#fff"/>'
               + mark(f + (side - logo) / 2, f + (side - logo) / 2 + 0.5, logo, "#000") + "</mask>")
    out.append("</defs>")
    for i, o in enumerate(offs):
        out.append(f'<rect x="{o:g}" y="{o:g}" width="{side:g}" height="{side:g}" rx="{r:g}" fill="#000" mask="url(#m{i})"/>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


(ICONS / "app-icon.svg").write_text(app_icon())
(ICONS / "tray-template.svg").write_text(tray_icon())
MAC = APP.parent / "cua-spaces-macos/Sources/CuaSpacesMacKit/Resources"
if MAC.is_dir():
    (MAC / "stack-mark.svg").write_text(stack_mark())
print("wrote", ICONS / "app-icon.svg", "and", ICONS / "tray-template.svg", "and", MAC / "stack-mark.svg")
