// Generated by cua-contract-gen; do not edit by hand.

import type { ToolResult } from "./result.js"

export const CONTRACT_VERSION = "0.2.0" as const
export const MCP_PROTOCOL_VERSION = "2025-06-18" as const

export interface ClickArgs {
  x: number
  y: number
  scope: "desktop"
  button?: "left" | "right" | "middle"
  count?: number
  session?: string
}

function clickToWire(input: ClickArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.x = input.x
  output.y = input.y
  output.scope = input.scope
  if (input.button !== undefined) output.button = input.button
  if (input.count !== undefined) output.count = input.count
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface DragArgs {
  fromX: number
  fromY: number
  toX: number
  toY: number
  scope: "desktop"
  button?: "left" | "right" | "middle"
  durationMs?: number
  modifier?: string[]
  session?: string
  steps?: number
}

function dragToWire(input: DragArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.from_x = input.fromX
  output.from_y = input.fromY
  output.to_x = input.toX
  output.to_y = input.toY
  output.scope = input.scope
  if (input.button !== undefined) output.button = input.button
  if (input.durationMs !== undefined) output.duration_ms = input.durationMs
  if (input.modifier !== undefined) output.modifier = input.modifier
  if (input.session !== undefined) output.session = input.session
  if (input.steps !== undefined) output.steps = input.steps
  return output
}

export interface EndSessionArgs {
  session: string
}

function endSessionToWire(input: EndSessionArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  return output
}

export interface EscalateSessionArgs {
  session: string
  reason: "ax_tree_pixel_mismatch" | "background_delivery_failed" | "foreground_ineffective" | "no_window_target" | "other"
  detail?: string
}

function escalateSessionToWire(input: EscalateSessionArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  output.reason = input.reason
  if (input.detail !== undefined) output.detail = input.detail
  return output
}

export interface GetCursorPositionArgs {
  session?: string
}

function getCursorPositionToWire(input: GetCursorPositionArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface GetDesktopStateArgs {
  screenshotOutFile?: string
  session?: string
}

function getDesktopStateToWire(input: GetDesktopStateArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  if (input.screenshotOutFile !== undefined) output.screenshot_out_file = input.screenshotOutFile
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface GetScreenSizeArgs {
  session?: string
}

function getScreenSizeToWire(input: GetScreenSizeArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface GetSessionStateArgs {
  session: string
}

function getSessionStateToWire(input: GetSessionStateArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  return output
}

export interface HotkeyArgs {
  keys: string[]
  scope: "desktop"
  session?: string
}

function hotkeyToWire(input: HotkeyArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.keys = input.keys
  output.scope = input.scope
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface MoveCursorArgs {
  x: number
  y: number
  scope: "desktop"
  session?: string
}

function moveCursorToWire(input: MoveCursorArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.x = input.x
  output.y = input.y
  output.scope = input.scope
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface PressKeyArgs {
  key: string
  scope: "desktop"
  modifiers?: string[]
  session?: string
}

function pressKeyToWire(input: PressKeyArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.key = input.key
  output.scope = input.scope
  if (input.modifiers !== undefined) output.modifiers = input.modifiers
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface ScrollArgs {
  x: number
  y: number
  direction: "up" | "down" | "left" | "right"
  scope: "desktop"
  amount?: number
  by?: "line" | "page"
  session?: string
}

function scrollToWire(input: ScrollArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.x = input.x
  output.y = input.y
  output.direction = input.direction
  output.scope = input.scope
  if (input.amount !== undefined) output.amount = input.amount
  if (input.by !== undefined) output.by = input.by
  if (input.session !== undefined) output.session = input.session
  return output
}

export interface StartSessionArgs {
  session: string
  captureScope?: "auto" | "window" | "desktop"
}

function startSessionToWire(input: StartSessionArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.session = input.session
  if (input.captureScope !== undefined) output.capture_scope = input.captureScope
  return output
}

export interface TypeTextArgs {
  text: string
  scope: "desktop"
  session?: string
}

function typeTextToWire(input: TypeTextArgs): Record<string, unknown> {
  const output: Record<string, unknown> = {}
  output.text = input.text
  output.scope = input.scope
  if (input.session !== undefined) output.session = input.session
  return output
}

export abstract class GeneratedDriver {
  abstract callTool(name: string, input?: Record<string, unknown>): Promise<ToolResult>

  click(input: ClickArgs): Promise<ToolResult> {
    return this.callTool("click", clickToWire(input))
  }

  drag(input: DragArgs): Promise<ToolResult> {
    return this.callTool("drag", dragToWire(input))
  }

  endSession(input: EndSessionArgs): Promise<ToolResult> {
    return this.callTool("end_session", endSessionToWire(input))
  }

  escalateSession(input: EscalateSessionArgs): Promise<ToolResult> {
    return this.callTool("escalate_session", escalateSessionToWire(input))
  }

  getCursorPosition(input: GetCursorPositionArgs): Promise<ToolResult> {
    return this.callTool("get_cursor_position", getCursorPositionToWire(input))
  }

  getDesktopState(input: GetDesktopStateArgs): Promise<ToolResult> {
    return this.callTool("get_desktop_state", getDesktopStateToWire(input))
  }

  getScreenSize(input: GetScreenSizeArgs): Promise<ToolResult> {
    return this.callTool("get_screen_size", getScreenSizeToWire(input))
  }

  getSessionState(input: GetSessionStateArgs): Promise<ToolResult> {
    return this.callTool("get_session_state", getSessionStateToWire(input))
  }

  hotkey(input: HotkeyArgs): Promise<ToolResult> {
    return this.callTool("hotkey", hotkeyToWire(input))
  }

  moveCursor(input: MoveCursorArgs): Promise<ToolResult> {
    return this.callTool("move_cursor", moveCursorToWire(input))
  }

  pressKey(input: PressKeyArgs): Promise<ToolResult> {
    return this.callTool("press_key", pressKeyToWire(input))
  }

  scroll(input: ScrollArgs): Promise<ToolResult> {
    return this.callTool("scroll", scrollToWire(input))
  }

  startSession(input: StartSessionArgs): Promise<ToolResult> {
    return this.callTool("start_session", startSessionToWire(input))
  }

  typeText(input: TypeTextArgs): Promise<ToolResult> {
    return this.callTool("type_text", typeTextToWire(input))
  }

}
