// SPDX-License-Identifier: FSL-1.1-MIT
// Copyright (c) 2026 Cua AI, Inc.

/**
 * Arguments that take every operation down its usual path on the demo
 * host's data (its Spaces, runs, Keyvault requests and grants), for the
 * contract tests here and in apps/cua-spaces-desktop.
 */

import type { OpArgs, OpName } from "../protocol";

const SPACE = "local:design-review";

export const DEMO_ARGS: { [K in OpName]: OpArgs<K> } = {
  "spaces.list": {},
  "spaces.create": { config: { image: "linux", on: "local", name: "contract-check" }, pendingId: "pending:contract" },
  "spaces.cancelCreate": { pendingId: "pending:none" },
  "spaces.setPower": { spaceId: SPACE, on: true },
  "spaces.delete": { spaceId: "local:agent-sandbox" },
  "spaces.open": { spaceId: SPACE },
  "machines.list": {},
  "host.status": {},
  "settings.get": {},
  "settings.set": { key: "menuBar", value: true },
  "settings.choose": { row: "auto-connect", option: "off" },
  "keyvault.overview": {},
  "keyvault.unlock": { passphrase: null },
  "keyvault.setup": { passphrase: null },
  "keyvault.showItems": {},
  "keyvault.delete": { itemIds: ["kv-linear"] },
  "keyvault.run": { command: { type: "revoke-grant", id: "grant-1" } },
  "keyvault.dismiss": { imports: ["imp-1"] },
  "keyvault.setUnattended": { itemIds: ["kv-linear"], unattended: true },
  "keyvault.setDisabled": { disabled: false },
  "keyvault.approve": { requestId: "req-1", items: null },
  "keyvault.deny": { requestId: "req-2" },
  "keyvault.revokeGrant": { id: "grant-1" },
  "session.get": {},
  "session.signIn": {},
  "session.signOut": {},
  "session.completeOnboarding": { mode: "client" },
  "session.openExternal": { url: "https://cua.ai" },
  "agents.list": {},
  "agents.runs": { spaceId: SPACE },
  "agents.events": { spaceId: SPACE, runId: "run-ada-7", cursor: 0 },
  "agents.pause": { name: "ada" },
  "agents.resume": { name: "ada" },
  "agents.setup": {},
  "agents.configure": { agents: null },
  "spaces.createOptions": {},
  "spaces.add": { url: "studio.local:7400", token: null, name: null },
  "clouds.status": {},
  "clouds.test": { target: { provider: "aws", region: "us-west-2" } },
  "clouds.connect": { target: { provider: "aws", region: "us-west-2" }, makeDefault: false },
  "teleport.catalog": { spaceId: SPACE },
  "teleport.entryForPath": { path: "/Applications/Slack.app" },
  "teleport.windows": {},
  "teleport.remoteWindows": { spaceId: SPACE },
  "teleport.icon": { spaceId: SPACE, icon: { kind: "host", path: "/Applications/Slack.app" } },
  "teleport.thumbnail": { spaceId: SPACE, thumbnail: { kind: "host-window", windowId: 41 } },
  "teleport.plan": { spaceId: SPACE, entry: { id: "slack" } as never, move: "app_only", files: [], sensitiveGroups: [] },
  "teleport.run": {
    spaceId: SPACE,
    plan: { app: { id: "slack" }, steps: [], consent: [] } as never,
    consent: { approved: true, acknowledgeSensitive: false },
    runId: "run-contract",
  },
  "teleport.sites": { providerId: "chrome" },
  "teleport.remembered": { providerId: "chrome", spaceId: SPACE },
  "teleport.streamWindow": { spaceId: SPACE, spaceName: "design-review", windowId: "w-1", appName: "Firefox", title: "Mozilla Firefox" },
  "sharing.list": { spaceId: SPACE },
  "sharing.share": { spaceId: SPACE, who: "bob@example.com", role: "viewer" },
  "sharing.unshare": { spaceId: SPACE, who: "bob@example.com" },
  "agentKeys.list": {},
  "agentKeys.set": { provider: "anthropic", value: "sk-ant-test-0000" },
  "agentKeys.remove": { env: "ANTHROPIC_API_KEY" },
  "volume.overview": {},
  "volume.storage": {},
  "volume.storageSet": { update: { backend: "fs", s3: null, access_key_id: null, secret_access_key: null, dry_run: true } },
  "volume.mount": {},
  "volume.unmount": {},
  "volume.approve": { id: "req-research" },
  "volume.deny": { id: "q2" },
  "volume.revoke": { id: "grant-writer" },
  "volume.resolve": { path: "public/plan.md" },
  "volume.reveal": { path: "/Users/ada/Cua Volume/public" },
  "agents.setupDriver": { agents: ["codex"] },
  "spaces.openStream": { spaceId: SPACE, tier: "tile" },
  "about.get": {},
  "about.set": { channel: "beta" },
  "about.checkNow": {},
  "experiments.get": {},
  "experiments.set": { experiments: { cuaVolume: true } },
  "loginItem.get": {},
  "loginItem.set": { on: true },
  "loginItem.openSettings": {},
  "devices.get": {},
  "devices.enroll": {},
  "devices.checkEnrolled": {},
  "devices.approve": { code: "K7QX-M2RP", deviceId: null },
  "devices.rename": { id: "dev_studio", name: "Studio" },
  "devices.revoke": { id: "dev_old" },
  "devices.confirmMachine": { id: "m1" },
  "storage.get": {},
  "storage.run": { request: { kind: "clear-cache" } },
  "notifications.list": {},
  "notifications.markAllRead": {},
  "telemetry.track": { signals: [{ type: "step", step: "app_launched", ok: true }] },
  "spaces.usage": { spaceId: SPACE },
  "spaces.windows": { spaceId: SPACE },
  "stream.pip": { spaceId: SPACE, command: { type: "open", row: "desktop" } },
  "spaces.thumbnail": { spaceId: SPACE },
  "spaces.chooseFiles": {},
  "spaces.droppedFiles": { names: ["notes.txt"] },
  "spaces.sendFiles": { spaceId: SPACE, paths: ["/tmp/cua-contract-notes.txt"] },
  "host.setUp": { request: { mode: "relay" } },
  "host.action": { action: "stop-sharing" },
  "host.openSettings": { url: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility" },
  "startup.get": {},
  "startup.act": { action: "allowAccess" },
};

/** Operations the demo host refuses on purpose, and why. */
export const DEMO_REFUSES: Partial<Record<OpName, string>> = {
  "spaces.openStream": "the demo host has no video; the page keeps its drawn thumbnail",
};
