// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Cua AI, Inc.

//! Canonical, platform-neutral contract declarations for cua-driver clients.
//!
//! This crate deliberately contains no transport or platform implementation.
//! The native driver remains the only execution engine; this package owns the
//! typed inputs/results and versioned declarations used by the live runtime
//! and to generate experimental client SDKs.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::sync::OnceLock;

pub mod compatibility;
mod desktop;
mod inputs;
mod outputs;
mod session;

pub use inputs::{
    CaptureScope, ClickButton, ClickInput, DesktopScope, DragInput, EndSessionInput,
    EscalateSessionInput, EscalationReason, GetCursorPositionInput, GetDesktopStateInput,
    GetScreenSizeInput, GetSessionStateInput, HotkeyInput, MoveCursorInput, PressKeyInput,
    ScrollBy, ScrollDirection, ScrollInput, StartSessionInput, ToolInput, TypeTextInput,
};
pub use outputs::{
    ClickOutput, CursorPositionOutput, DesktopActionOutput, DesktopStateOutput, EffectiveScope,
    EndSessionOutput, MoveCursorOutput, ScreenSizeOutput, SessionStateOutput, StartSessionOutput,
    ToolOutput,
};

/// Shape version for the MCP `tools/list` result emitted by cua-driver.
pub const TOOLS_LIST_SCHEMA_VERSION: &str = "1";

/// Version of the additive capability-token vocabulary.
pub const CAPABILITY_VERSION: &str = "1";

/// Shape version for the checked-in generated client contract.
pub const CONTRACT_VERSION: &str = "0.2.0";

/// MCP protocol version used by current cua-driver clients.
pub const MCP_PROTOCOL_VERSION: &str = "2025-06-18";

#[derive(
    Debug, Clone, Copy, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq, PartialOrd, Ord,
)]
#[serde(rename_all = "snake_case")]
pub enum Platform {
    Macos,
    Windows,
    Linux,
}

/// Whether a client contract is also the canonical live MCP schema, or a
/// deliberately narrower cross-platform subset accepted by every backend.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SchemaMode {
    CanonicalRuntime,
    PortableSubset,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolAnnotations {
    pub read_only: bool,
    pub destructive: bool,
    pub idempotent: bool,
    pub open_world: bool,
}

pub type OutputValidator = fn(Value) -> Result<(), String>;

fn default_output_validator() -> OutputValidator {
    |_| Ok(())
}

pub(crate) fn validate_typed_output<T: ToolOutput>(value: Value) -> Result<(), String> {
    let output = serde_json::from_value::<T>(value).map_err(|error| error.to_string())?;
    output.validate()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolContract {
    pub name: String,
    pub description: String,
    pub platforms: Vec<Platform>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub aliases: Vec<String>,
    pub capabilities: Vec<String>,
    pub annotations: ToolAnnotations,
    pub schema_mode: SchemaMode,
    pub input_schema: Value,
    /// Schema for successful `structuredContent` only. It is experimental and
    /// is not advertised as MCP `outputSchema` until transport parity is proven.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub success_output_schema: Option<Value>,
    /// Runtime-only validator bound to the same Rust output type that produced
    /// `success_output_schema`; omitted from the generated manifest.
    #[serde(skip, default = "default_output_validator")]
    pub(crate) output_validator: OutputValidator,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContractManifest {
    pub generated_notice: String,
    pub experimental: bool,
    pub contract_version: String,
    pub tools_list_schema_version: String,
    pub capability_version: String,
    pub mcp_protocol_version: String,
    pub transport: String,
    pub tools: Vec<ToolContract>,
}

pub fn manifest() -> ContractManifest {
    let mut tools = session::contracts();
    tools.extend(desktop::contracts());
    tools.sort_by(|left, right| left.name.cmp(&right.name));
    ContractManifest {
        generated_notice: "Generated by cua-contract-gen; do not edit by hand.".into(),
        experimental: true,
        contract_version: CONTRACT_VERSION.into(),
        tools_list_schema_version: TOOLS_LIST_SCHEMA_VERSION.into(),
        capability_version: CAPABILITY_VERSION.into(),
        mcp_protocol_version: MCP_PROTOCOL_VERSION.into(),
        transport: "mcp_stdio".into(),
        tools,
    }
}

pub fn tool_contract(name: &str) -> Option<ToolContract> {
    manifest().tools.into_iter().find(|tool| tool.name == name)
}

#[derive(Debug)]
struct ToolIndexEntry {
    capabilities: Vec<String>,
    input_fields: BTreeSet<String>,
    output_validator: OutputValidator,
}

fn tool_index() -> &'static BTreeMap<String, ToolIndexEntry> {
    static INDEX: OnceLock<BTreeMap<String, ToolIndexEntry>> = OnceLock::new();
    INDEX.get_or_init(|| {
        manifest()
            .tools
            .into_iter()
            .map(|tool| {
                let input_fields = tool
                    .input_schema
                    .get("properties")
                    .and_then(Value::as_object)
                    .into_iter()
                    .flatten()
                    .map(|(name, _)| name.clone())
                    .collect();
                (
                    tool.name,
                    ToolIndexEntry {
                        capabilities: tool.capabilities,
                        input_fields,
                        output_validator: tool.output_validator,
                    },
                )
            })
            .collect()
    })
}

/// Return capability tokens for one published tool without rebuilding schemas
/// on every live `tools/list` entry.
pub fn tool_capabilities(name: &str) -> Option<Vec<String>> {
    tool_index()
        .get(name)
        .map(|entry| entry.capabilities.clone())
}

/// Names owned by a published portable input projection.
pub fn tool_input_fields(name: &str) -> Option<&'static BTreeSet<String>> {
    tool_index().get(name).map(|entry| &entry.input_fields)
}

/// Validate a successful structured payload against the Rust output type that
/// also generates its SDK schema. Returns `Ok(false)` for non-SDK tools.
pub fn validate_success_output(name: &str, value: Value) -> Result<bool, String> {
    if let Some(entry) = tool_index().get(name) {
        (entry.output_validator)(value)?;
        Ok(true)
    } else {
        Ok(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_is_sorted_and_versioned() {
        let manifest = manifest();
        let names: Vec<_> = manifest
            .tools
            .iter()
            .map(|tool| tool.name.as_str())
            .collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        assert_eq!(names, sorted);
        assert_eq!(manifest.contract_version, "0.2.0");
        assert!(manifest.experimental);
    }

    #[test]
    fn every_contract_has_success_schema_and_platforms() {
        for tool in manifest().tools {
            assert!(!tool.platforms.is_empty(), "{} has no platform", tool.name);
            assert!(
                tool.success_output_schema.is_some(),
                "{} has no success output schema",
                tool.name
            );
        }
    }

    #[test]
    fn desktop_contracts_are_explicit_portable_subsets() {
        for name in [
            "click",
            "drag",
            "get_cursor_position",
            "get_desktop_state",
            "get_screen_size",
            "hotkey",
            "move_cursor",
            "press_key",
            "scroll",
            "type_text",
        ] {
            assert_eq!(
                tool_contract(name).expect("desktop contract").schema_mode,
                SchemaMode::PortableSubset,
                "{name}"
            );
        }
    }

    #[test]
    fn session_success_schemas_require_every_typed_field() {
        let start = tool_contract("start_session").expect("start_session contract");
        let success_schema = start.success_output_schema.expect("success schema");
        let required = success_schema["required"]
            .as_array()
            .expect("required array")
            .iter()
            .filter_map(Value::as_str)
            .collect::<Vec<_>>();
        assert_eq!(
            required,
            [
                "session",
                "capture_scope",
                "effective_scope",
                "desktop_unlocked",
                "escalation_reason",
                "escalation_detail",
                "active",
                "revived",
            ]
        );
    }

    #[test]
    fn typed_success_outputs_accept_extensions_and_reject_wrong_common_fields() {
        assert_eq!(
            validate_success_output(
                "get_screen_size",
                serde_json::json!({
                    "width": 1512,
                    "height": 982,
                    "scale_factor": 2,
                    "backend": "core_graphics"
                }),
            ),
            Ok(true)
        );
        assert!(validate_success_output(
            "get_screen_size",
            serde_json::json!({
                "width": "1512",
                "height": 982,
                "scale_factor": 2
            }),
        )
        .is_err());
        assert!(validate_success_output(
            "end_session",
            serde_json::json!({"session": "run", "active": true}),
        )
        .is_err());
    }

    #[test]
    fn every_published_tool_has_a_live_typed_output_validator() {
        for contract in manifest().tools {
            let invalid = serde_json::json!([]);
            assert!(
                validate_success_output(&contract.name, invalid).is_err(),
                "{} has no typed output validator",
                contract.name
            );
        }
    }
}
