// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Cua AI, Inc.

//! Canonical, platform-neutral contract declarations for cua-driver clients.
//!
//! This crate deliberately contains no transport or platform implementation.
//! The native driver remains the only execution engine; this package owns the
//! versioned declarations used to generate experimental client SDKs.

use serde::{Deserialize, Serialize};
use serde_json::Value;

mod outputs;
pub mod schema;
mod session;

pub use outputs::{EndSessionOutput, SessionStateOutput, StartSessionOutput};

/// Shape version for the MCP `tools/list` result emitted by cua-driver.
pub const TOOLS_LIST_SCHEMA_VERSION: &str = "1";

/// Version of the additive capability-token vocabulary.
pub const CAPABILITY_VERSION: &str = "1";

/// Shape version for the checked-in generated client contract.
pub const CONTRACT_VERSION: &str = "0.1.0";

/// MCP protocol version used by current cua-driver clients.
pub const MCP_PROTOCOL_VERSION: &str = "2025-06-18";

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum Platform {
    Macos,
    Windows,
    Linux,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolAnnotations {
    pub read_only: bool,
    pub destructive: bool,
    pub idempotent: bool,
    pub open_world: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolContract {
    pub name: String,
    pub description: String,
    pub platforms: Vec<Platform>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub aliases: Vec<String>,
    pub capabilities: Vec<String>,
    pub annotations: ToolAnnotations,
    pub input_schema: Value,
    /// Schema for successful `structuredContent` only. It is experimental and
    /// is not advertised as MCP `outputSchema` until transport parity is proven.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub success_output_schema: Option<Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ContractManifest {
    pub generated_notice: String,
    pub experimental: bool,
    pub contract_version: String,
    pub tools_list_schema_version: String,
    pub capability_version: String,
    pub mcp_protocol_version: String,
    pub transport: String,
    pub tools: Vec<ToolContract>,
}

pub fn manifest() -> ContractManifest {
    let mut tools = session::contracts();
    tools.sort_by(|left, right| left.name.cmp(&right.name));
    ContractManifest {
        generated_notice: "Generated by cua-contract-gen; do not edit by hand.".into(),
        experimental: true,
        contract_version: CONTRACT_VERSION.into(),
        tools_list_schema_version: TOOLS_LIST_SCHEMA_VERSION.into(),
        capability_version: CAPABILITY_VERSION.into(),
        mcp_protocol_version: MCP_PROTOCOL_VERSION.into(),
        transport: "mcp_stdio".into(),
        tools,
    }
}

pub fn tool_contract(name: &str) -> Option<ToolContract> {
    manifest().tools.into_iter().find(|tool| tool.name == name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_is_sorted_and_versioned() {
        let manifest = manifest();
        let names: Vec<_> = manifest
            .tools
            .iter()
            .map(|tool| tool.name.as_str())
            .collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        assert_eq!(names, sorted);
        assert_eq!(manifest.contract_version, "0.1.0");
        assert!(manifest.experimental);
    }

    #[test]
    fn every_contract_has_success_schema_and_platforms() {
        for tool in manifest().tools {
            assert!(!tool.platforms.is_empty(), "{} has no platform", tool.name);
            assert!(
                tool.success_output_schema.is_some(),
                "{} has no success output schema",
                tool.name
            );
        }
    }

    #[test]
    fn session_success_schemas_require_every_typed_field() {
        let start = tool_contract("start_session").expect("start_session contract");
        let success_schema = start.success_output_schema.expect("success schema");
        let required = success_schema["required"]
            .as_array()
            .expect("required array")
            .iter()
            .filter_map(Value::as_str)
            .collect::<Vec<_>>();
        assert_eq!(
            required,
            [
                "session",
                "capture_scope",
                "effective_scope",
                "desktop_unlocked",
                "escalation_reason",
                "escalation_detail",
                "active",
                "revived",
            ]
        );
    }
}
