#!/usr/bin/env node

/**
 * Build `@trycua/cua/browser`: the cua-sdk wasm32 build (env over gRPC-Web
 * + Fleet) through UBRN's web target and wasm-bindgen 0.2.126, like
 * libs/fleet/sdk-bindings/ts-uniffi-browser.
 *
 * Output (gitignored build artifacts): libs/cua/typescript/browser/
 *   - generated TypeScript bindings (cua_sdk.ts, cua_sdk-ffi.ts, index.web.ts)
 *   - wasm-bindgen glue and the .wasm binary (browser/wasm/)
 *
 * Usage: node build-wasm.mjs [--debug]
 */

import { spawnSync } from "node:child_process"
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const cuaRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const typescriptRoot = join(cuaRoot, "typescript")
const work = join(typescriptRoot, "browser-build")
const release = !process.argv.includes("--debug")

function run(command, args, cwd, env = process.env) {
  const result = spawnSync(command, args, { cwd, stdio: "inherit", env })
  if (result.error) throw result.error
  if (result.status !== 0) throw new Error(`${command} exited with status ${result.status}`)
}

// Pin wasm-bindgen to the installed CLI and fix the template's TOML, as the
// Fleet browser package does. Idempotent: already-patched files are left.
const templates = join(
  typescriptRoot,
  "node_modules/uniffi-bindgen-react-native/crates/ubrn_cli/templates/wasm",
)
if (!existsSync(templates)) {
  throw new Error("missing pinned UBRN; run npm ci in libs/cua/typescript")
}
function patch(file, replacements) {
  const path = join(templates, file)
  let source = readFileSync(path, "utf8")
  for (const [from, to] of replacements) {
    if (source.includes(to)) continue
    if (source.split(from).length - 1 !== 1) throw new Error(`template ${file} changed: ${from}`)
    source = source.replace(from, to)
  }
  writeFileSync(path, source)
}
patch("Cargo.toml.txt", [
  ['wasm-bindgen = "*"', 'wasm-bindgen = "=0.2.126"'],
  ['opt-level = "3"', "opt-level = 3"],
  ["[workspace]", '[workspace]\nresolver = "2"'],
])

rmSync(work, { recursive: true, force: true })
mkdirSync(work, { recursive: true })
writeFileSync(
  join(work, "ubrn.config.yaml"),
  [
    // Paths are relative to the npm project root (libs/cua/typescript).
    "rust:",
    "  directory: ..",
    "  manifestPath: crates/cua-sdk/Cargo.toml",
    "bindings:",
    "  cpp: browser-build/cpp",
    "  ts: browser-build/ts",
    "web:",
    "  manifestPath: browser-build/rust_modules/wasm/Cargo.toml",
    "  tsBindings: browser-build/ts",
    "  entrypoint: browser-build/ts/index.web.ts",
    "  defaultFeatures: false",
    "  features: [web]",
    "  wasmCrateName: cua-sdk-wasm",
    "",
  ].join("\n"),
)
const ubrn = join(typescriptRoot, "node_modules", ".bin", "ubrn")
run(
  ubrn,
  ["build", "web", "--config", "ubrn.config.yaml", "--and-generate", ...(release ? ["--release"] : [])],
  work,
)

const out = join(typescriptRoot, "browser")
rmSync(out, { recursive: true, force: true })
mkdirSync(out, { recursive: true })
cpSync(join(work, "ts"), out, { recursive: true })

// Make the generated TypeScript valid NodeNext/ESM (explicit `.js` on
// relative module imports; the `.wasm` asset import stays for bundlers),
// then compile it next to the sources.
for (const name of readdirSync(out).filter((n) => n.endsWith(".ts") && !n.endsWith(".d.ts"))) {
  const path = join(out, name)
  const source = readFileSync(path, "utf8")
    .replaceAll("from './/", "from './")
    .replaceAll('from ".//', 'from "./')
    .replace(/(from\s+["']\.\/(?!wasm-bindgen\/index_bg\.wasm)[A-Za-z0-9_./-]+?)(?<!\.js)(["'])/g, "$1.js$2")
  writeFileSync(path, source)
}
writeFileSync(
  join(out, "tsconfig.json"),
  `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ES2022",
        moduleResolution: "bundler",
        declaration: true,
        skipLibCheck: true,
        strict: false,
        noImplicitAny: false,
        outDir: ".",
        rootDir: ".",
      },
      include: ["*.ts"],
      exclude: ["*.d.ts", "index.web.ts"],
    },
    null,
    2,
  )}\n`,
)
run(join(typescriptRoot, "node_modules", ".bin", "tsc"), ["-p", join(out, "tsconfig.json")], out)

// `@trycua/cua/browser` entry: re-exports the cua_sdk namespace and
// initializes the wasm module and every linked UniFFI namespace once.
const entry = `// Generated by libs/cua/scripts/build-wasm.mjs.
export * from "./cua_sdk.js"
import init from "./wasm-bindgen/index.js"
import * as cua_sdk from "./cua_sdk.js"
import * as cyclops_sdk_schema from "./cyclops_sdk_schema.js"
import * as fleet_sdk from "./fleet_sdk.js"

let ready
/** Loads the wasm module (URL, bytes or a compiled module); call once before use. */
export function initialize(wasm) {
  ready ??= (async () => {
    await init({ module_or_path: wasm ?? new URL("./wasm-bindgen/index_bg.wasm", import.meta.url) })
    cua_sdk.default.initialize()
    cyclops_sdk_schema.default.initialize()
    fleet_sdk.default.initialize()
  })()
  return ready
}
`
writeFileSync(join(out, "index.js"), entry)
writeFileSync(
  join(out, "index.d.ts"),
  `export * from "./cua_sdk.js"\nexport declare function initialize(wasm?: URL | string | BufferSource | WebAssembly.Module): Promise<void>\n`,
)
console.log(`built ${out}`)
