// cyclops-cs backend — sidecar for the cyclops-cs Pod.
//
// Every authenticated route runs through the standard
//
//	Trace → Log → TokenAuth → OPA → handler
//
// pipeline borrowed from r33drichards/grt:
//
//	/api/keys[/{id}]            — SPA-authenticated CRUD on per-user
//	                              service-account clients in Keycloak.
//
//	/api/gateway/{name}[/{p...}]— DEPRECATED (CUA-609). Returns 410 Gone.
//	                              The per-pool orchestrator HTTP layer has
//	                              been removed. All pool operations now use
//	                              OSGymSandboxClaim CRs (Path B) directly.
//	                              Zero HTTP traffic was confirmed before
//	                              removal. Route kept for OPA continuity
//	                              (per-key tokens still validated).
//
//	/api/batch/{pool}, /api/label/{pool}
//	                            — DEPRECATED. Returns 410 Gone for every
//	                              request. The orchestrator-backed batch
//	                              surface is retired; callers must
//	                              migrate to the replacement flow.
//
//	@title						Cyclops CS Backend API
//	@version					0.1
//	@description				Backend sidecar for the cyclops-cs SPA — Keycloak-authenticated key management, service proxies (k8s / orch / svc), namespace management, and deprecated gateway / batch / label routes that now return 410 Gone. All pool operations use OSGymSandboxClaim CRs (Path B).
//	@BasePath					/
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				Keycloak access token. For /api/keys and /api/{k8s,orch} the token is the SPA's user JWT (azp=cyclops-cs-spa). /api/gateway/{name} requires a per-key token whose `namespace` claim equals "pool-{name}" (enforced by OPA). The deprecated /api/batch/{pool} and /api/label/{pool} routes are permanently retired — they return 410 Gone for every request regardless of token validity.
package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"

	"github.com/spf13/cobra"

	"cyclops-cs-backend/auth"
	"cyclops-cs-backend/config"
	_ "cyclops-cs-backend/docs" // generated by `swag init`
	"cyclops-cs-backend/handlers"
	"cyclops-cs-backend/keycloak"
	"cyclops-cs-backend/metrics"
	"cyclops-cs-backend/middlewares"
	"cyclops-cs-backend/telemetry"
	"cyclops-cs-backend/templates"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	"github.com/trycua/cloud/pkg/featureflags"
)

var configValues *config.Configuration

// withMiddlewares mirrors grt — every authenticated route runs through
// Trace → Log → TokenAuth → OPA. RouteContext stamps the matched route
// (and its named params) onto the request context so the Rego policy
// can branch on `input.route` instead of regex-parsing the URL.
func withMiddlewares(route string, params []string, h http.HandlerFunc) http.Handler {
	return middlewares.TraceMiddleware(route,
		middlewares.LogMiddleware(
			auth.RouteContext(route, params...)(
				auth.TokenAuthMiddleware(
					auth.OpaMiddleware(
						http.HandlerFunc(h))))))
}

// withK8sMiddlewares is withMiddlewares + auth.K8sEventFilterMiddleware
// sitting immediately above the handler. The event filter only buffers
// responses whose upstream path is a K8s EventList; all other K8s API
// calls pass through untouched.
func withK8sMiddlewares(route string, params []string, h http.HandlerFunc) http.Handler {
	return middlewares.TraceMiddleware(route,
		middlewares.LogMiddleware(
			auth.RouteContext(route, params...)(
				auth.TokenAuthMiddleware(
					auth.OpaMiddleware(
						auth.K8sEventFilterMiddleware(
							http.HandlerFunc(h)))))))
}

func onlyLog(route string, h http.HandlerFunc) http.Handler {
	return middlewares.TraceMiddleware(route, middlewares.LogMiddleware(http.HandlerFunc(h)))
}

func setupRouter(c handlers.Handlers) http.Handler {
	r := http.NewServeMux()

	r.Handle("GET /healthz", onlyLog("/healthz", c.GetHealth))

	// Feature flags / per-user config. SPA-only (same auth as /api/keys).
	r.Handle("GET /api/config",
		withMiddlewares("/api/config", nil, c.GetConfig))

	// Swagger UI + JSON. The SPA points its codegen at /api/swagger/doc.json
	// (see cyclops-cs/scripts/codegen.sh). We don't put the doc behind auth
	// — the schema is public and the actual endpoints are still gated.
	r.Handle("GET /api/swagger/", onlyLog("/api/swagger/", func(w http.ResponseWriter, r *http.Request) {
		httpSwagger.Handler(httpSwagger.URL("/api/swagger/doc.json")).ServeHTTP(w, r)
	}))

	r.Handle("POST /api/keys",
		withMiddlewares("/api/keys", nil, c.CreateKey))
	r.Handle("GET /api/keys",
		withMiddlewares("/api/keys", nil, c.ListKeys))
	r.Handle("DELETE /api/keys/{id}",
		withMiddlewares("/api/keys/{id}", []string{"id"}, c.DeleteKey))

	// Namespace management — Capsule-backed per-user namespaces.
	// Uses K8s impersonation so Capsule sees the real user identity.
	r.Handle("GET /api/namespaces",
		withMiddlewares("/api/namespaces", nil, c.ListNamespaces))
	r.Handle("POST /api/namespaces",
		withMiddlewares("/api/namespaces", nil, c.CreateNamespace))
	r.Handle("DELETE /api/namespaces/{name}",
		withMiddlewares("/api/namespaces/{name}", []string{"name"}, c.DeleteNamespace))

	// Per-user API keys — Keycloak service-account clients (ukey- prefix).
	r.Handle("POST /api/user-keys",
		withMiddlewares("/api/user-keys", nil, c.CreateUserKey))
	r.Handle("GET /api/user-keys",
		withMiddlewares("/api/user-keys", nil, c.ListUserKeys))
	r.Handle("DELETE /api/user-keys/{id}",
		withMiddlewares("/api/user-keys/{id}", []string{"id"}, c.DeleteUserKey))

	// Per-user pool templates — Redis-backed saved pool configs the SPA
	// reuses to seed new pools. SPA-auth, same pipeline as /api/keys.
	// Always registered; the handlers reply 503 when no Redis is wired.
	r.Handle("POST /api/pool-templates",
		withMiddlewares("/api/pool-templates", nil, c.CreatePoolTemplate))
	r.Handle("GET /api/pool-templates",
		withMiddlewares("/api/pool-templates", nil, c.ListPoolTemplates))
	r.Handle("GET /api/pool-templates/{name}",
		withMiddlewares("/api/pool-templates/{name}", []string{"name"}, c.GetPoolTemplate))
	r.Handle("DELETE /api/pool-templates/{name}",
		withMiddlewares("/api/pool-templates/{name}", []string{"name"}, c.DeletePoolTemplate))

	r.Handle("/api/gateway/{name}",
		withMiddlewares("/api/gateway/{name}", []string{"name"}, c.Gateway))
	r.Handle("/api/gateway/{name}/{path...}",
		withMiddlewares("/api/gateway/{name}/{path...}", []string{"name", "path"}, c.Gateway))

	// Generic service proxy — reaches a K8s Service on port 80 in a
	// namespace the caller is authorized for. OPA gates authn/shape;
	// namespace ownership is enforced in the handler (per-key tokens via
	// their namespace claim, everyone else via an impersonated
	// RoleBinding probe — see handlers.requireNamespaceAccess).
	r.Handle("/api/svc/{namespace}/{service}",
		withMiddlewares("/api/svc/{namespace}/{service}",
			[]string{"namespace", "service"}, c.Svc))
	r.Handle("/api/svc/{namespace}/{service}/{path...}",
		withMiddlewares("/api/svc/{namespace}/{service}/{path...}",
			[]string{"namespace", "service", "path"}, c.Svc))

	// K8s API + per-namespace orchestrator catalog access — replace the
	// unauthenticated /k8s-api and /orch-api nginx locations from before.
	r.Handle("/api/k8s/{path...}",
		withK8sMiddlewares("/api/k8s/{path...}", []string{"path"}, c.K8s))
	r.Handle("/api/orch/{namespace}/{service}/{path...}",
		withMiddlewares("/api/orch/{namespace}/{service}/{path...}",
			[]string{"namespace", "service", "path"}, c.Orch))

	// Keep deprecated batch/label routes registered so callers get an explicit
	// terminal status instead of an implicit 404 from the router.
	r.Handle("POST /api/batch/{pool}/submit",
		withMiddlewares("/api/batch/{pool}/submit", []string{"pool"}, c.DeprecatedBatchRoute))
	r.Handle("POST /api/batch/{pool}/lanes",
		withMiddlewares("/api/batch/{pool}/lanes", []string{"pool"}, c.DeprecatedBatchRoute))
	r.Handle("DELETE /api/batch/{pool}/lanes",
		withMiddlewares("/api/batch/{pool}/lanes", []string{"pool"}, c.DeprecatedBatchRoute))
	r.Handle("GET /api/batch/{pool}/{id}/status",
		withMiddlewares("/api/batch/{pool}/{id}/status", []string{"pool", "id"}, c.DeprecatedBatchRoute))
	r.Handle("GET /api/batch/{pool}/{id}/results",
		withMiddlewares("/api/batch/{pool}/{id}/results", []string{"pool", "id"}, c.DeprecatedBatchRoute))
	r.Handle("DELETE /api/batch/{pool}/{id}",
		withMiddlewares("/api/batch/{pool}/{id}", []string{"pool", "id"}, c.DeprecatedBatchRoute))
	r.Handle("POST /api/label/{pool}/{label}/batch",
		withMiddlewares("/api/label/{pool}/{label}/batch", []string{"pool", "label"}, c.DeprecatedBatchRoute))
	r.Handle("GET /api/label/{pool}/{label}/status",
		withMiddlewares("/api/label/{pool}/{label}/status", []string{"pool", "label"}, c.DeprecatedBatchRoute))
	r.Handle("GET /api/label/{pool}/{label}/results",
		withMiddlewares("/api/label/{pool}/{label}/results", []string{"pool", "label"}, c.DeprecatedBatchRoute))
	r.Handle("DELETE /api/label/{pool}/{label}",
		withMiddlewares("/api/label/{pool}/{label}", []string{"pool", "label"}, c.DeprecatedBatchRoute))

	// Wrap the entire mux in the metrics middleware so every request
	// (including /healthz and unmatched routes) is recorded. This must be
	// the outermost layer so the status code from inner middlewares (auth,
	// OPA) is captured correctly.
	return metrics.Middleware(r)
}

var rootCmd = &cobra.Command{
	Use:           "cyclops-cs-backend",
	Short:         "cyclops-cs backend sidecar",
	SilenceUsage:  true,
	SilenceErrors: true,
	RunE:          func(_ *cobra.Command, _ []string) error { return run() },
}

func init() {
	config.RegisterFlags(rootCmd.PersistentFlags())
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		slog.Error("fatal", "err", err)
		os.Exit(1)
	}
}

func run() error {
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, nil)))
	ctx := context.Background()

	cfg, err := config.LoadConfig()
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	configValues = cfg

	telemetryShutdown := func(context.Context) error { return nil }
	if shutdown, err := telemetry.Init(ctx, telemetry.Config{
		Endpoint:         cfg.Telemetry.Endpoint,
		Protocol:         cfg.Telemetry.Protocol,
		ServiceName:      cfg.Telemetry.ServiceName,
		ServiceNamespace: cfg.Telemetry.ServiceNamespace,
		Environment:      cfg.Telemetry.Environment,
		ResourceAttrs:    cfg.Telemetry.ResourceAttrs,
	}); err != nil {
		slog.Warn("otel: init failed; tracing disabled", "err", err)
	} else {
		telemetryShutdown = shutdown
	}
	defer func() {
		if err := telemetryShutdown(context.Background()); err != nil {
			slog.Warn("otel: shutdown failed", "err", err)
		}
	}()

	slog.Info("starting", "issuer", cfg.Auth.Issuer, "listen", cfg.WebServer.Addr, "jwks_uri", cfg.Auth.JWKSUri)

	slog.Info("init: fetching JWKS")
	auth.MustInit(&cfg.Auth)
	slog.Info("init: JWKS ok, setting up OpenFeature provider")
	// SetupProvider returns a non-nil error when it falls back to the
	// from-env provider (missing creds / SSM init failure). Log it but
	// keep starting — flag evaluations still resolve via the fallback.
	if err := featureflags.SetupProvider(ctx, os.Getenv("ENVIRONMENT"), featureflags.AWSCredentials{
		AccessKeyID:     os.Getenv("AWS_ACCESS_KEY_ID"),
		SecretAccessKey: os.Getenv("AWS_SECRET_ACCESS_KEY"),
		Region:          os.Getenv("AWS_REGION"),
	}); err != nil {
		slog.Warn("openfeature: provider setup degraded", "err", err)
	}
	slog.Info("init: OpenFeature ok, loading OPA")
	auth.LoadOpa()
	slog.Info("init: OPA ok")

	// Start the Prometheus metrics server on a separate port so that it
	// doesn't compete with the main API server. The port is configurable
	// via METRICS_ADDR; the default :9091 avoids collision with the
	// in-namespace Prometheus deployment (which serves on :9090 / :80).
	metricsAddr := cfg.Metrics.Addr
	go func() {
		slog.Info("starting metrics server", "addr", metricsAddr)
		if err := metrics.StartMetricsServer(metricsAddr); err != nil {
			slog.Error("metrics server exited", "err", err)
		}
	}()

	admin := keycloak.NewAdmin(cfg.Keycloak.BaseURL, cfg.Keycloak.Realm, cfg.Keycloak.AdminClientID, cfg.Keycloak.AdminClientSecret, cfg.Auth.KeyClientPfx, cfg.Auth.UserKeyClientPfx)

	// Optional: admin client for the workloads realm, used to mint per-tenant
	// OIDC clients for OSGym pool VMs. Enabled only when its secret is set;
	// the admin client lives in the workloads realm because Keycloak
	// realm-management roles are per-realm. See
	// docs/decisions/2026-06-25-osgym-pool-workload-oidc.md.
	var workloadAdmin *keycloak.Admin
	if cfg.Keycloak.WorkloadAdminClientSecret != "" {
		workloadAdmin = keycloak.NewAdmin(
			cfg.Keycloak.BaseURL, cfg.Keycloak.WorkloadRealm,
			cfg.Keycloak.WorkloadAdminClientID, cfg.Keycloak.WorkloadAdminClientSecret,
			"", "",
		)
		slog.Info("workload-oidc: enabled", "realm", cfg.Keycloak.WorkloadRealm)
	} else {
		slog.Info("workload-oidc: disabled (KC_WORKLOAD_ADMIN_CLIENT_SECRET unset)")
	}

	// Redis-backed pool templates. A connection failure is non-fatal —
	// the routes stay registered and reply 503 until Redis is reachable,
	// mirroring how other optional surfaces degrade gracefully.
	h := handlers.New(admin, cfg)
	h.WorkloadAdmin = workloadAdmin
	h.WorkloadAudience = cfg.Keycloak.WorkloadAudience
	h.WorkloadTokenURL = cfg.Keycloak.WorkloadTokenURL
	if store, err := templates.New(ctx, cfg.Templates.RedisURL); err != nil {
		slog.Error("pool templates: init failed; /api/pool-templates will return 503", "err", err)
	} else if store != nil {
		h.Templates = store
		slog.Info("pool templates: enabled")
	} else {
		slog.Info("pool templates: disabled (no Redis URL configured)")
	}

	router := setupRouter(h)

	srv := &http.Server{Addr: cfg.WebServer.Addr, Handler: router}
	if err := srv.ListenAndServe(); err != nil {
		return fmt.Errorf("server exited: %w", err)
	}
	return nil
}
