# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .rb file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Ruby
# helpers directly inline like we're doing here.

require 'ffi'


module CyclopsSdkSchema
  def self.uniffi_in_range(i, type_name, min, max)
  raise TypeError, "no implicit conversion of #{i} into Integer" unless i.respond_to?(:to_int)
  i = i.to_int
  raise RangeError, "#{type_name} requires #{min} <= value < #{max}" unless (min <= i && i < max)
  i
end

def self.uniffi_utf8(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v = v.to_str.encode(Encoding::UTF_8)
  raise Encoding::InvalidByteSequenceError, "not a valid UTF-8 encoded string" unless v.valid_encoding?
  v
end

def self.uniffi_bytes(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v.to_str
end

  class RustBuffer < FFI::Struct
  layout :capacity, :uint64,
         :len,      :uint64,
         :data,     :pointer

  def self.alloc(size)
    return CyclopsSdkSchema.rust_call(:ffi_cyclops_sdk_schema_rustbuffer_alloc, size)
  end

  def self.reserve(rbuf, additional)
    return CyclopsSdkSchema.rust_call(:ffi_cyclops_sdk_schema_rustbuffer_reserve, rbuf, additional)
  end

  def free
    CyclopsSdkSchema.rust_call(:ffi_cyclops_sdk_schema_rustbuffer_free, self)
  end

  def capacity
    self[:capacity]
  end

  def len
    self[:len]
  end

  def len=(value)
    self[:len] = value
  end

  def data
    self[:data]
  end

  def to_s
    "RustBuffer(capacity=#{capacity}, len=#{len}, data=#{data.read_bytes len})"
  end

  # The allocated buffer will be automatically freed if an error occurs, ensuring that
  # we don't accidentally leak it.
  def self.allocWithBuilder
    builder = RustBufferBuilder.new

    begin
      yield builder
    rescue => e
      builder.discard
      raise e
    end
  end

  # The RustBuffer will be freed once the context-manager exits, ensuring that we don't
  # leak it even if an error occurs.
  def consumeWithStream
    stream = RustBufferStream.new self

    yield stream

    raise RuntimeError, 'junk data left in buffer after consuming' if stream.remaining != 0
  ensure
    free
  end# The primitive String type.

  def self.allocFromString(value)
    RustBuffer.allocWithBuilder do |builder|
      builder.write value.encode('utf-8')
      return builder.finalize
    end
  end

  def consumeIntoString
    consumeWithStream do |stream|
      return stream.read(stream.remaining).force_encoding(Encoding::UTF_8)
    end
  end

  # The Record type ClaimLifecycle.

  def self.check_lower_TypeClaimLifecycle(v)
    RustBuffer.check_lower_Optionalstring(v.shutdown_time)
    RustBuffer.check_lower_Optionalstring(v.shutdown_policy)
    RustBuffer.check_lower_Optionalbool(v.auto_renew)
  end

  def self.alloc_from_TypeClaimLifecycle(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeClaimLifecycle(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeClaimLifecycle
    consumeWithStream do |stream|
      return stream.readTypeClaimLifecycle
    end
  end

  # The Record type ClaimSpec.

  def self.check_lower_TypeClaimSpec(v)
    RustBuffer.check_lower_TypeSandboxTemplateRef(v.sandbox_template_ref)
    RustBuffer.check_lower_Optionalstring(v.warmpool)
    RustBuffer.check_lower_Optionalu32(v.bind_deadline)
    RustBuffer.check_lower_OptionalTypeClaimLifecycle(v.lifecycle)
  end

  def self.alloc_from_TypeClaimSpec(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeClaimSpec(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeClaimSpec
    consumeWithStream do |stream|
      return stream.readTypeClaimSpec
    end
  end

  # The Record type OSGymSandboxClaimCondition.

  def self.check_lower_TypeOSGymSandboxClaimCondition(v)
    RustBuffer.check_lower_Optionalstring(v.type)
    RustBuffer.check_lower_Optionalstring(v.status)
    RustBuffer.check_lower_Optionalstring(v.reason)
    RustBuffer.check_lower_Optionalstring(v.message)
    RustBuffer.check_lower_Optionalstring(v.last_transition_time)
  end

  def self.alloc_from_TypeOSGymSandboxClaimCondition(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxClaimCondition(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxClaimCondition
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxClaimCondition
    end
  end

  # The Record type OSGymSandboxClaimSandbox.

  def self.check_lower_TypeOSGymSandboxClaimSandbox(v)
    RustBuffer.check_lower_Optionalstring(v.name)
    RustBuffer.check_lower_Optionalstring(v.service)
  end

  def self.alloc_from_TypeOSGymSandboxClaimSandbox(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxClaimSandbox(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxClaimSandbox
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxClaimSandbox
    end
  end

  # The Record type OSGymSandboxClaimStatus.

  def self.check_lower_TypeOSGymSandboxClaimStatus(v)
    RustBuffer.check_lower_Optionalstring(v.phase)
    RustBuffer.check_lower_OptionalSequenceTypeOsGymSandboxClaimCondition(v.conditions)
    RustBuffer.check_lower_OptionalTypeOsGymSandboxClaimSandbox(v.sandbox)
  end

  def self.alloc_from_TypeOSGymSandboxClaimStatus(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxClaimStatus(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxClaimStatus
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxClaimStatus
    end
  end

  # The Record type OSGymSandboxSpec.

  def self.check_lower_TypeOSGymSandboxSpec(v)
    RustBuffer.check_lower_TypeVmTemplate(v.vm_template)
  end

  def self.alloc_from_TypeOSGymSandboxSpec(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxSpec(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxSpec
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxSpec
    end
  end

  # The Record type OSGymSandboxStatus.

  def self.check_lower_TypeOSGymSandboxStatus(v)
    RustBuffer.check_lower_Optionalstring(v.phase)
    RustBuffer.check_lower_Optionalstring(v.runtime)
    RustBuffer.check_lower_Optionalbool(v.ready)
    RustBuffer.check_lower_Optionalstring(v.vm_name)
    RustBuffer.check_lower_Optionalstring(v.service)
    RustBuffer.check_lower_Optionalstring(v.message)
    RustBuffer.check_lower_Optionalstring(v.reset_issued_at)
    RustBuffer.check_lower_Optionalstring(v.reset_vmi_uid)
  end

  def self.alloc_from_TypeOSGymSandboxStatus(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxStatus(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxStatus
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxStatus
    end
  end

  # The Record type OSGymSandboxTemplateSpec.

  def self.check_lower_TypeOSGymSandboxTemplateSpec(v)
    RustBuffer.check_lower_TypeVmTemplate(v.vm_template)
  end

  def self.alloc_from_TypeOSGymSandboxTemplateSpec(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxTemplateSpec(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxTemplateSpec
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxTemplateSpec
    end
  end

  # The Record type OSGymSandboxWarmPoolSpec.

  def self.check_lower_TypeOSGymSandboxWarmPoolSpec(v)

    RustBuffer.check_lower_TypeSandboxTemplateRef(v.sandbox_template_ref)
    RustBuffer.check_lower_OptionalTypeWarmPoolAutoscaling(v.autoscaling)
  end

  def self.alloc_from_TypeOSGymSandboxWarmPoolSpec(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxWarmPoolSpec(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxWarmPoolSpec
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxWarmPoolSpec
    end
  end

  # The Record type OSGymSandboxWarmPoolStatus.

  def self.check_lower_TypeOSGymSandboxWarmPoolStatus(v)
    RustBuffer.check_lower_Optionalu32(v.replicas)
    RustBuffer.check_lower_Optionalu32(v.ready_replicas)
    RustBuffer.check_lower_Optionalstring(v.selector)
  end

  def self.alloc_from_TypeOSGymSandboxWarmPoolStatus(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymSandboxWarmPoolStatus(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymSandboxWarmPoolStatus
    consumeWithStream do |stream|
      return stream.readTypeOSGymSandboxWarmPoolStatus
    end
  end

  # The Record type OSGymWorkspacePoolStatus.

  def self.check_lower_TypeOSGymWorkspacePoolStatus(v)
    RustBuffer.check_lower_Optionalstring(v.phase)
    RustBuffer.check_lower_Optionalu32(v.total_count)
    RustBuffer.check_lower_Optionalu32(v.available_count)
    RustBuffer.check_lower_Optionalu32(v.claimed_count)
  end

  def self.alloc_from_TypeOSGymWorkspacePoolStatus(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOSGymWorkspacePoolStatus(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOSGymWorkspacePoolStatus
    consumeWithStream do |stream|
      return stream.readTypeOSGymWorkspacePoolStatus
    end
  end

  # The Record type OidcConfig.

  def self.check_lower_TypeOidcConfig(v)


    RustBuffer.check_lower_Optionalstring(v.aws_role_arn)
    RustBuffer.check_lower_Optionalstring(v.aws_region)
    RustBuffer.check_lower_Optionalu32(v.refresh_interval_seconds)
  end

  def self.alloc_from_TypeOidcConfig(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeOidcConfig(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeOidcConfig
    consumeWithStream do |stream|
      return stream.readTypeOidcConfig
    end
  end

  # The Record type PoolSpec.

  def self.check_lower_TypePoolSpec(v)

    RustBuffer.check_lower_TypePoolTemplate(v.template)
    RustBuffer.check_lower_OptionalTypeWarmPoolAutoscaling(v.autoscaling)
    RustBuffer.check_lower_OptionalSequenceTypeSandboxService(v.services)
  end

  def self.alloc_from_TypePoolSpec(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypePoolSpec(v)
      return builder.finalize
    end
  end

  def consumeIntoTypePoolSpec
    consumeWithStream do |stream|
      return stream.readTypePoolSpec
    end
  end

  # The Record type PoolTemplate.

  def self.check_lower_TypePoolTemplate(v)
    RustBuffer.check_lower_OptionalTypeRuntimeKind(v.runtime)
    RustBuffer.check_lower_Optionalstring(v.runtime_class_name)
    RustBuffer.check_lower_OptionalMapStringString(v.node_selector)
    RustBuffer.check_lower_OptionalSequenceTypePreservedJson(v.tolerations)
    RustBuffer.check_lower_OptionalSequencestring(v.command)

    RustBuffer.check_lower_Optionalstring(v.image_pull_secret)
    RustBuffer.check_lower_Optionalu32(v.cpu_cores)
    RustBuffer.check_lower_Optionalstring(v.memory)
    RustBuffer.check_lower_OptionalTypeFirmware(v.firmware)
    RustBuffer.check_lower_OptionalTypePreservedJson(v.probes)
    RustBuffer.check_lower_OptionalTypeOidcConfig(v.oidc)
  end

  def self.alloc_from_TypePoolTemplate(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypePoolTemplate(v)
      return builder.finalize
    end
  end

  def consumeIntoTypePoolTemplate
    consumeWithStream do |stream|
      return stream.readTypePoolTemplate
    end
  end

  # The Record type SandboxService.

  def self.check_lower_TypeSandboxService(v)


    RustBuffer.check_lower_OptionalTypeServiceProtocol(v.protocol)
  end

  def self.alloc_from_TypeSandboxService(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeSandboxService(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeSandboxService
    consumeWithStream do |stream|
      return stream.readTypeSandboxService
    end
  end

  # The Record type SandboxTemplateRef.

  def self.check_lower_TypeSandboxTemplateRef(v)

  end

  def self.alloc_from_TypeSandboxTemplateRef(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeSandboxTemplateRef(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeSandboxTemplateRef
    consumeWithStream do |stream|
      return stream.readTypeSandboxTemplateRef
    end
  end

  # The Record type VmTemplate.

  def self.check_lower_TypeVmTemplate(v)

    RustBuffer.check_lower_OptionalSequencestring(v.command)
    RustBuffer.check_lower_OptionalTypeRuntimeKind(v.runtime)
    RustBuffer.check_lower_Optionalstring(v.runtime_class_name)
    RustBuffer.check_lower_OptionalMapStringString(v.node_selector)
    RustBuffer.check_lower_OptionalSequenceTypePreservedJson(v.tolerations)
    RustBuffer.check_lower_OptionalTypeImagePullPolicy(v.image_pull_policy)
    RustBuffer.check_lower_Optionalstring(v.image_pull_secret)
    RustBuffer.check_lower_Optionalu32(v.cpu_cores)
    RustBuffer.check_lower_Optionalstring(v.memory)
    RustBuffer.check_lower_OptionalTypeFirmware(v.firmware)
    RustBuffer.check_lower_OptionalTypePreservedJson(v.probes)
    RustBuffer.check_lower_OptionalSequenceTypeSandboxService(v.services)
    RustBuffer.check_lower_OptionalTypeOidcConfig(v.oidc)
  end

  def self.alloc_from_TypeVmTemplate(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeVmTemplate(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeVmTemplate
    consumeWithStream do |stream|
      return stream.readTypeVmTemplate
    end
  end

  # The Record type WarmPoolAutoscaling.

  def self.check_lower_TypeWarmPoolAutoscaling(v)
    RustBuffer.check_lower_Optionalu32(v.min_pool_size)
    RustBuffer.check_lower_Optionalu32(v.initial_pool_size)
    RustBuffer.check_lower_Optionalu32(v.max_pool_size)
  end

  def self.alloc_from_TypeWarmPoolAutoscaling(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeWarmPoolAutoscaling(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeWarmPoolAutoscaling
    consumeWithStream do |stream|
      return stream.readTypeWarmPoolAutoscaling
    end
  end

  # The Enum type Firmware.

  def self.check_lower_TypeFirmware(v)
  end

  def self.alloc_from_TypeFirmware(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeFirmware(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeFirmware
    consumeWithStream do |stream|
      return stream.readTypeFirmware
    end
  end


  # The Enum type ImagePullPolicy.

  def self.check_lower_TypeImagePullPolicy(v)
  end

  def self.alloc_from_TypeImagePullPolicy(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeImagePullPolicy(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeImagePullPolicy
    consumeWithStream do |stream|
      return stream.readTypeImagePullPolicy
    end
  end




  # The Enum type RuntimeKind.

  def self.check_lower_TypeRuntimeKind(v)
  end

  def self.alloc_from_TypeRuntimeKind(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeRuntimeKind(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeRuntimeKind
    consumeWithStream do |stream|
      return stream.readTypeRuntimeKind
    end
  end


  # The Enum type ServiceProtocol.

  def self.check_lower_TypeServiceProtocol(v)
  end

  def self.alloc_from_TypeServiceProtocol(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeServiceProtocol(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeServiceProtocol
    consumeWithStream do |stream|
      return stream.readTypeServiceProtocol
    end
  end


  # The Optional<T> type for u32.

  def self.check_lower_Optionalu32(v)
    if not v.nil?

    end
  end

  def self.alloc_from_Optionalu32(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Optionalu32(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalu32
    consumeWithStream do |stream|
      return stream.readOptionalu32
    end
  end

  # The Optional<T> type for bool.

  def self.check_lower_Optionalbool(v)
    if not v.nil?

    end
  end

  def self.alloc_from_Optionalbool(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Optionalbool(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalbool
    consumeWithStream do |stream|
      return stream.readOptionalbool
    end
  end

  # The Optional<T> type for string.

  def self.check_lower_Optionalstring(v)
    if not v.nil?

    end
  end

  def self.alloc_from_Optionalstring(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Optionalstring(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalstring
    consumeWithStream do |stream|
      return stream.readOptionalstring
    end
  end

  # The Optional<T> type for TypePreservedJson.

  def self.check_lower_OptionalTypePreservedJson(v)
    if not v.nil?
      (PreservedJson.uniffi_check_lower v)
    end
  end

  def self.alloc_from_OptionalTypePreservedJson(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypePreservedJson(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypePreservedJson
    consumeWithStream do |stream|
      return stream.readOptionalTypePreservedJson
    end
  end

  # The Optional<T> type for TypeClaimLifecycle.

  def self.check_lower_OptionalTypeClaimLifecycle(v)
    if not v.nil?
      RustBuffer.check_lower_TypeClaimLifecycle(v)
    end
  end

  def self.alloc_from_OptionalTypeClaimLifecycle(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeClaimLifecycle(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeClaimLifecycle
    consumeWithStream do |stream|
      return stream.readOptionalTypeClaimLifecycle
    end
  end

  # The Optional<T> type for TypeOSGymSandboxClaimSandbox.

  def self.check_lower_OptionalTypeOSGymSandboxClaimSandbox(v)
    if not v.nil?
      RustBuffer.check_lower_TypeOsGymSandboxClaimSandbox(v)
    end
  end

  def self.alloc_from_OptionalTypeOSGymSandboxClaimSandbox(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeOSGymSandboxClaimSandbox(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeOSGymSandboxClaimSandbox
    consumeWithStream do |stream|
      return stream.readOptionalTypeOSGymSandboxClaimSandbox
    end
  end

  # The Optional<T> type for TypeOidcConfig.

  def self.check_lower_OptionalTypeOidcConfig(v)
    if not v.nil?
      RustBuffer.check_lower_TypeOidcConfig(v)
    end
  end

  def self.alloc_from_OptionalTypeOidcConfig(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeOidcConfig(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeOidcConfig
    consumeWithStream do |stream|
      return stream.readOptionalTypeOidcConfig
    end
  end

  # The Optional<T> type for TypeWarmPoolAutoscaling.

  def self.check_lower_OptionalTypeWarmPoolAutoscaling(v)
    if not v.nil?
      RustBuffer.check_lower_TypeWarmPoolAutoscaling(v)
    end
  end

  def self.alloc_from_OptionalTypeWarmPoolAutoscaling(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeWarmPoolAutoscaling(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeWarmPoolAutoscaling
    consumeWithStream do |stream|
      return stream.readOptionalTypeWarmPoolAutoscaling
    end
  end

  # The Optional<T> type for TypeFirmware.

  def self.check_lower_OptionalTypeFirmware(v)
    if not v.nil?
      RustBuffer.check_lower_TypeFirmware(v)
    end
  end

  def self.alloc_from_OptionalTypeFirmware(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeFirmware(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeFirmware
    consumeWithStream do |stream|
      return stream.readOptionalTypeFirmware
    end
  end

  # The Optional<T> type for TypeImagePullPolicy.

  def self.check_lower_OptionalTypeImagePullPolicy(v)
    if not v.nil?
      RustBuffer.check_lower_TypeImagePullPolicy(v)
    end
  end

  def self.alloc_from_OptionalTypeImagePullPolicy(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeImagePullPolicy(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeImagePullPolicy
    consumeWithStream do |stream|
      return stream.readOptionalTypeImagePullPolicy
    end
  end

  # The Optional<T> type for TypeRuntimeKind.

  def self.check_lower_OptionalTypeRuntimeKind(v)
    if not v.nil?
      RustBuffer.check_lower_TypeRuntimeKind(v)
    end
  end

  def self.alloc_from_OptionalTypeRuntimeKind(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeRuntimeKind(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeRuntimeKind
    consumeWithStream do |stream|
      return stream.readOptionalTypeRuntimeKind
    end
  end

  # The Optional<T> type for TypeServiceProtocol.

  def self.check_lower_OptionalTypeServiceProtocol(v)
    if not v.nil?
      RustBuffer.check_lower_TypeServiceProtocol(v)
    end
  end

  def self.alloc_from_OptionalTypeServiceProtocol(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeServiceProtocol(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeServiceProtocol
    consumeWithStream do |stream|
      return stream.readOptionalTypeServiceProtocol
    end
  end

  # The Optional<T> type for Sequencestring.

  def self.check_lower_OptionalSequencestring(v)
    if not v.nil?
      RustBuffer.check_lower_Sequencestring(v)
    end
  end

  def self.alloc_from_OptionalSequencestring(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalSequencestring(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalSequencestring
    consumeWithStream do |stream|
      return stream.readOptionalSequencestring
    end
  end

  # The Optional<T> type for SequenceTypePreservedJson.

  def self.check_lower_OptionalSequenceTypePreservedJson(v)
    if not v.nil?
      RustBuffer.check_lower_SequenceTypePreservedJson(v)
    end
  end

  def self.alloc_from_OptionalSequenceTypePreservedJson(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalSequenceTypePreservedJson(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalSequenceTypePreservedJson
    consumeWithStream do |stream|
      return stream.readOptionalSequenceTypePreservedJson
    end
  end

  # The Optional<T> type for SequenceTypeOSGymSandboxClaimCondition.

  def self.check_lower_OptionalSequenceTypeOSGymSandboxClaimCondition(v)
    if not v.nil?
      RustBuffer.check_lower_SequenceTypeOsGymSandboxClaimCondition(v)
    end
  end

  def self.alloc_from_OptionalSequenceTypeOSGymSandboxClaimCondition(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalSequenceTypeOSGymSandboxClaimCondition(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalSequenceTypeOSGymSandboxClaimCondition
    consumeWithStream do |stream|
      return stream.readOptionalSequenceTypeOSGymSandboxClaimCondition
    end
  end

  # The Optional<T> type for SequenceTypeSandboxService.

  def self.check_lower_OptionalSequenceTypeSandboxService(v)
    if not v.nil?
      RustBuffer.check_lower_SequenceTypeSandboxService(v)
    end
  end

  def self.alloc_from_OptionalSequenceTypeSandboxService(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalSequenceTypeSandboxService(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalSequenceTypeSandboxService
    consumeWithStream do |stream|
      return stream.readOptionalSequenceTypeSandboxService
    end
  end

  # The Optional<T> type for MapStringString.

  def self.check_lower_OptionalMapStringString(v)
    if not v.nil?
      RustBuffer.check_lower_MapStringString(v)
    end
  end

  def self.alloc_from_OptionalMapStringString(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalMapStringString(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalMapStringString
    consumeWithStream do |stream|
      return stream.readOptionalMapStringString
    end
  end

  # The Sequence<T> type for string.

  def self.check_lower_Sequencestring(v)
    v.each do |item|

    end
  end

  def self.alloc_from_Sequencestring(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Sequencestring(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequencestring
    consumeWithStream do |stream|
      return stream.readSequencestring
    end
  end

  # The Sequence<T> type for TypePreservedJson.

  def self.check_lower_SequenceTypePreservedJson(v)
    v.each do |item|
      (PreservedJson.uniffi_check_lower item)
    end
  end

  def self.alloc_from_SequenceTypePreservedJson(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_SequenceTypePreservedJson(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceTypePreservedJson
    consumeWithStream do |stream|
      return stream.readSequenceTypePreservedJson
    end
  end

  # The Sequence<T> type for TypeOSGymSandboxClaimCondition.

  def self.check_lower_SequenceTypeOSGymSandboxClaimCondition(v)
    v.each do |item|
      RustBuffer.check_lower_TypeOsGymSandboxClaimCondition(item)
    end
  end

  def self.alloc_from_SequenceTypeOSGymSandboxClaimCondition(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_SequenceTypeOSGymSandboxClaimCondition(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceTypeOSGymSandboxClaimCondition
    consumeWithStream do |stream|
      return stream.readSequenceTypeOSGymSandboxClaimCondition
    end
  end

  # The Sequence<T> type for TypeSandboxService.

  def self.check_lower_SequenceTypeSandboxService(v)
    v.each do |item|
      RustBuffer.check_lower_TypeSandboxService(item)
    end
  end

  def self.alloc_from_SequenceTypeSandboxService(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_SequenceTypeSandboxService(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceTypeSandboxService
    consumeWithStream do |stream|
      return stream.readSequenceTypeSandboxService
    end
  end

  # The Map<T> type for string.

  def self.check_lower_MapStringString(v)
    v.each do |k, v|


    end
  end

  def self.alloc_from_MapStringString(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_MapStringString(v)
      return builder.finalize
    end
  end

  def consumeIntoMapStringString
    consumeWithStream do |stream|
      return stream.readMapStringString
    end
  end
end

module UniFFILib
  class ForeignBytes < FFI::Struct
    layout :len,      :int32,
           :data,     :pointer

    def len
      self[:len]
    end

    def data
      self[:data]
    end

    def to_s
      "ForeignBytes(len=#{len}, data=#{data.read_bytes(len)})"
    end
  end
end

private_constant :UniFFILib

# Helper for structured reading of values from a RustBuffer.
class RustBufferStream

  def initialize(rbuf)
    @rbuf = rbuf
    @offset = 0
  end

  def remaining
    @rbuf.len - @offset
  end

  def read(size)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    data = @rbuf.data.get_bytes @offset, size

    @offset += size

    data
  end

  def readU16
    unpack_from 2, 'S>'
  end

  def readU32
    unpack_from 4, 'L>'
  end

  def readU64
    unpack_from 8, 'Q>'
  end

  def readBool
    v = unpack_from 1, 'c'

    return false if v == 0
    return true if v == 1

    raise InternalError, 'Unexpected byte for Boolean type'
  end

  def readString
    size = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative string length' if size.negative?

    read(size).force_encoding(Encoding::UTF_8)
  end

  # The Object type PreservedJson.

  def readTypePreservedJson
    handle = unpack_from 8, 'Q>'
    return PreservedJson.uniffi_allocate(handle)
  end

  # The Record type ClaimLifecycle.

  def readTypeClaimLifecycle
    ClaimLifecycle.new(
      shutdown_time: readOptionalstring,
      shutdown_policy: readOptionalstring,
      auto_renew: readOptionalbool
    )
  end

  # The Record type ClaimSpec.

  def readTypeClaimSpec
    ClaimSpec.new(
      sandbox_template_ref: readTypeSandboxTemplateRef,
      warmpool: readOptionalstring,
      bind_deadline: readOptionalu32,
      lifecycle: readOptionalTypeClaimLifecycle
    )
  end

  # The Record type OSGymSandboxClaimCondition.

  def readTypeOsGymSandboxClaimCondition
    OsGymSandboxClaimCondition.new(
      type: readOptionalstring,
      status: readOptionalstring,
      reason: readOptionalstring,
      message: readOptionalstring,
      last_transition_time: readOptionalstring
    )
  end

  # The Record type OSGymSandboxClaimSandbox.

  def readTypeOsGymSandboxClaimSandbox
    OsGymSandboxClaimSandbox.new(
      name: readOptionalstring,
      service: readOptionalstring
    )
  end

  # The Record type OSGymSandboxClaimStatus.

  def readTypeOsGymSandboxClaimStatus
    OsGymSandboxClaimStatus.new(
      phase: readOptionalstring,
      conditions: readOptionalSequenceTypeOsGymSandboxClaimCondition,
      sandbox: readOptionalTypeOsGymSandboxClaimSandbox
    )
  end

  # The Record type OSGymSandboxSpec.

  def readTypeOsGymSandboxSpec
    OsGymSandboxSpec.new(
      vm_template: readTypeVmTemplate
    )
  end

  # The Record type OSGymSandboxStatus.

  def readTypeOsGymSandboxStatus
    OsGymSandboxStatus.new(
      phase: readOptionalstring,
      runtime: readOptionalstring,
      ready: readOptionalbool,
      vm_name: readOptionalstring,
      service: readOptionalstring,
      message: readOptionalstring,
      reset_issued_at: readOptionalstring,
      reset_vmi_uid: readOptionalstring
    )
  end

  # The Record type OSGymSandboxTemplateSpec.

  def readTypeOsGymSandboxTemplateSpec
    OsGymSandboxTemplateSpec.new(
      vm_template: readTypeVmTemplate
    )
  end

  # The Record type OSGymSandboxWarmPoolSpec.

  def readTypeOsGymSandboxWarmPoolSpec
    OsGymSandboxWarmPoolSpec.new(
      replicas: readU32,
      sandbox_template_ref: readTypeSandboxTemplateRef,
      autoscaling: readOptionalTypeWarmPoolAutoscaling
    )
  end

  # The Record type OSGymSandboxWarmPoolStatus.

  def readTypeOsGymSandboxWarmPoolStatus
    OsGymSandboxWarmPoolStatus.new(
      replicas: readOptionalu32,
      ready_replicas: readOptionalu32,
      selector: readOptionalstring
    )
  end

  # The Record type OSGymWorkspacePoolStatus.

  def readTypeOsGymWorkspacePoolStatus
    OsGymWorkspacePoolStatus.new(
      phase: readOptionalstring,
      total_count: readOptionalu32,
      available_count: readOptionalu32,
      claimed_count: readOptionalu32
    )
  end

  # The Record type OidcConfig.

  def readTypeOidcConfig
    OidcConfig.new(
      credentials_secret: readString,
      token_url: readString,
      aws_role_arn: readOptionalstring,
      aws_region: readOptionalstring,
      refresh_interval_seconds: readOptionalu32
    )
  end

  # The Record type PoolSpec.

  def readTypePoolSpec
    PoolSpec.new(
      replicas: readU32,
      template: readTypePoolTemplate,
      autoscaling: readOptionalTypeWarmPoolAutoscaling,
      services: readOptionalSequenceTypeSandboxService
    )
  end

  # The Record type PoolTemplate.

  def readTypePoolTemplate
    PoolTemplate.new(
      runtime: readOptionalTypeRuntimeKind,
      runtime_class_name: readOptionalstring,
      node_selector: readOptionalMapStringString,
      tolerations: readOptionalSequenceTypePreservedJson,
      command: readOptionalSequencestring,
      container_disk_image: readString,
      image_pull_secret: readOptionalstring,
      cpu_cores: readOptionalu32,
      memory: readOptionalstring,
      firmware: readOptionalTypeFirmware,
      probes: readOptionalTypePreservedJson,
      oidc: readOptionalTypeOidcConfig
    )
  end

  # The Record type SandboxService.

  def readTypeSandboxService
    SandboxService.new(
      name: readString,
      target_port: readU16,
      protocol: readOptionalTypeServiceProtocol
    )
  end

  # The Record type SandboxTemplateRef.

  def readTypeSandboxTemplateRef
    SandboxTemplateRef.new(
      name: readString
    )
  end

  # The Record type VmTemplate.

  def readTypeVmTemplate
    VmTemplate.new(
      container_disk_image: readString,
      command: readOptionalSequencestring,
      runtime: readOptionalTypeRuntimeKind,
      runtime_class_name: readOptionalstring,
      node_selector: readOptionalMapStringString,
      tolerations: readOptionalSequenceTypePreservedJson,
      image_pull_policy: readOptionalTypeImagePullPolicy,
      image_pull_secret: readOptionalstring,
      cpu_cores: readOptionalu32,
      memory: readOptionalstring,
      firmware: readOptionalTypeFirmware,
      probes: readOptionalTypePreservedJson,
      services: readOptionalSequenceTypeSandboxService,
      oidc: readOptionalTypeOidcConfig
    )
  end

  # The Record type WarmPoolAutoscaling.

  def readTypeWarmPoolAutoscaling
    WarmPoolAutoscaling.new(
      min_pool_size: readOptionalu32,
      initial_pool_size: readOptionalu32,
      max_pool_size: readOptionalu32
    )
  end



  # The Enum type Firmware.

  def readTypeFirmware
    variant = unpack_from 4, 'l>'

    if variant == 1
      return Firmware::BIOS
    end
    if variant == 2
      return Firmware::EFI
    end

    raise InternalError, 'Unexpected variant tag for TypeFirmware'
  end





  # The Enum type ImagePullPolicy.

  def readTypeImagePullPolicy
    variant = unpack_from 4, 'l>'

    if variant == 1
      return ImagePullPolicy::ALWAYS
    end
    if variant == 2
      return ImagePullPolicy::IF_NOT_PRESENT
    end
    if variant == 3
      return ImagePullPolicy::NEVER
    end

    raise InternalError, 'Unexpected variant tag for TypeImagePullPolicy'
  end







  # The Error type JsonValueError

  def readTypeJsonValueError
    variant = unpack_from 4, 'l>'

    if variant == 1
        return JsonValueError::Invalid.new(
            readString()
        )
    end

    raise InternalError, 'Unexpected variant tag for TypeJsonValueError'
  end




  # The Enum type RuntimeKind.

  def readTypeRuntimeKind
    variant = unpack_from 4, 'l>'

    if variant == 1
      return RuntimeKind::KUBEVIRT
    end
    if variant == 2
      return RuntimeKind::MACOS
    end
    if variant == 3
      return RuntimeKind::GVISOR
    end

    raise InternalError, 'Unexpected variant tag for TypeRuntimeKind'
  end





  # The Enum type ServiceProtocol.

  def readTypeServiceProtocol
    variant = unpack_from 4, 'l>'

    if variant == 1
      return ServiceProtocol::TCP
    end
    if variant == 2
      return ServiceProtocol::UDP
    end

    raise InternalError, 'Unexpected variant tag for TypeServiceProtocol'
  end



  # The Optional<T> type for u32.

  def readOptionalu32
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readU32
    else
      raise InternalError, 'Unexpected flag byte for Optionalu32'
    end
  end

  # The Optional<T> type for bool.

  def readOptionalbool
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readBool
    else
      raise InternalError, 'Unexpected flag byte for Optionalbool'
    end
  end

  # The Optional<T> type for string.

  def readOptionalstring
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readString
    else
      raise InternalError, 'Unexpected flag byte for Optionalstring'
    end
  end

  # The Optional<T> type for TypePreservedJson.

  def readOptionalTypePreservedJson
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypePreservedJson
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypePreservedJson'
    end
  end

  # The Optional<T> type for TypeClaimLifecycle.

  def readOptionalTypeClaimLifecycle
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeClaimLifecycle
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeClaimLifecycle'
    end
  end

  # The Optional<T> type for TypeOSGymSandboxClaimSandbox.

  def readOptionalTypeOsGymSandboxClaimSandbox
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeOsGymSandboxClaimSandbox
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeOsGymSandboxClaimSandbox'
    end
  end

  # The Optional<T> type for TypeOidcConfig.

  def readOptionalTypeOidcConfig
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeOidcConfig
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeOidcConfig'
    end
  end

  # The Optional<T> type for TypeWarmPoolAutoscaling.

  def readOptionalTypeWarmPoolAutoscaling
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeWarmPoolAutoscaling
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeWarmPoolAutoscaling'
    end
  end

  # The Optional<T> type for TypeFirmware.

  def readOptionalTypeFirmware
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeFirmware
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeFirmware'
    end
  end

  # The Optional<T> type for TypeImagePullPolicy.

  def readOptionalTypeImagePullPolicy
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeImagePullPolicy
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeImagePullPolicy'
    end
  end

  # The Optional<T> type for TypeRuntimeKind.

  def readOptionalTypeRuntimeKind
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeRuntimeKind
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeRuntimeKind'
    end
  end

  # The Optional<T> type for TypeServiceProtocol.

  def readOptionalTypeServiceProtocol
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeServiceProtocol
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeServiceProtocol'
    end
  end

  # The Optional<T> type for Sequencestring.

  def readOptionalSequencestring
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readSequencestring
    else
      raise InternalError, 'Unexpected flag byte for OptionalSequencestring'
    end
  end

  # The Optional<T> type for SequenceTypePreservedJson.

  def readOptionalSequenceTypePreservedJson
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readSequenceTypePreservedJson
    else
      raise InternalError, 'Unexpected flag byte for OptionalSequenceTypePreservedJson'
    end
  end

  # The Optional<T> type for SequenceTypeOSGymSandboxClaimCondition.

  def readOptionalSequenceTypeOsGymSandboxClaimCondition
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readSequenceTypeOsGymSandboxClaimCondition
    else
      raise InternalError, 'Unexpected flag byte for OptionalSequenceTypeOsGymSandboxClaimCondition'
    end
  end

  # The Optional<T> type for SequenceTypeSandboxService.

  def readOptionalSequenceTypeSandboxService
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readSequenceTypeSandboxService
    else
      raise InternalError, 'Unexpected flag byte for OptionalSequenceTypeSandboxService'
    end
  end

  # The Optional<T> type for MapStringString.

  def readOptionalMapStringString
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readMapStringString
    else
      raise InternalError, 'Unexpected flag byte for OptionalMapStringString'
    end
  end

  # The Sequence<T> type for string.

  def readSequencestring
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readString
    end

    items
  end

  # The Sequence<T> type for TypePreservedJson.

  def readSequenceTypePreservedJson
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readTypePreservedJson
    end

    items
  end

  # The Sequence<T> type for TypeOSGymSandboxClaimCondition.

  def readSequenceTypeOsGymSandboxClaimCondition
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readTypeOsGymSandboxClaimCondition
    end

    items
  end

  # The Sequence<T> type for TypeSandboxService.

  def readSequenceTypeSandboxService
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readTypeSandboxService
    end

    items
  end

  # The Map<T> type for string.

  def readMapStringString
    count = unpack_from 4, 'l>'
    raise InternalError, 'Unexpected negative map size' if count.negative?

    items = {}
    count.times do
      key = readString
      items[key] = readString
    end

    items
  end

  def unpack_from(size, format)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    value = @rbuf.data.get_bytes(@offset, size).unpack format

    @offset += size

    # TODO: verify this
    raise 'more than one element!!!' if value.size > 1

    value[0]
  end
end

private_constant :RustBufferStream

# Helper for structured writing of values into a RustBuffer.
class RustBufferBuilder
  def initialize
    @rust_buf = RustBuffer.alloc 16
    @rust_buf.len = 0
  end

  def finalize
    rbuf = @rust_buf

    @rust_buf = nil

    rbuf
  end

  def discard
    return if @rust_buf.nil?

    rbuf = finalize
    rbuf.free
  end

  def write(value)
    reserve(value.bytes.size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, value.bytes
    end
  end

  def write_U16(v)
    v = CyclopsSdkSchema::uniffi_in_range(v, "u16", 0, 2**16)
    pack_into(2, 'S>', v)
  end

  def write_U32(v)
    v = CyclopsSdkSchema::uniffi_in_range(v, "u32", 0, 2**32)
    pack_into(4, 'L>', v)
  end

  def write_U64(v)
    v = CyclopsSdkSchema::uniffi_in_range(v, "u64", 0, 2**64)
    pack_into(8, 'Q>', v)
  end

  def write_Bool(v)
    pack_into(1, 'c', v ? 1 : 0)
  end

  def write_String(v)
    v = CyclopsSdkSchema::uniffi_utf8(v)
    pack_into 4, 'l>', v.bytes.size
    write v
  end

  # The Object type PreservedJson.

  def write_TypePreservedJson(obj)
    handle = PreservedJson.uniffi_lower obj
    pack_into(8, 'Q>', handle)
  end

  # The Record type ClaimLifecycle.

  def write_TypeClaimLifecycle(v)
    self.write_Optionalstring(v.shutdown_time)
    self.write_Optionalstring(v.shutdown_policy)
    self.write_Optionalbool(v.auto_renew)
  end

  # The Record type ClaimSpec.

  def write_TypeClaimSpec(v)
    self.write_TypeSandboxTemplateRef(v.sandbox_template_ref)
    self.write_Optionalstring(v.warmpool)
    self.write_Optionalu32(v.bind_deadline)
    self.write_OptionalTypeClaimLifecycle(v.lifecycle)
  end

  # The Record type OSGymSandboxClaimCondition.

  def write_TypeOsGymSandboxClaimCondition(v)
    self.write_Optionalstring(v.type)
    self.write_Optionalstring(v.status)
    self.write_Optionalstring(v.reason)
    self.write_Optionalstring(v.message)
    self.write_Optionalstring(v.last_transition_time)
  end

  # The Record type OSGymSandboxClaimSandbox.

  def write_TypeOsGymSandboxClaimSandbox(v)
    self.write_Optionalstring(v.name)
    self.write_Optionalstring(v.service)
  end

  # The Record type OSGymSandboxClaimStatus.

  def write_TypeOsGymSandboxClaimStatus(v)
    self.write_Optionalstring(v.phase)
    self.write_OptionalSequenceTypeOsGymSandboxClaimCondition(v.conditions)
    self.write_OptionalTypeOsGymSandboxClaimSandbox(v.sandbox)
  end

  # The Record type OSGymSandboxSpec.

  def write_TypeOsGymSandboxSpec(v)
    self.write_TypeVmTemplate(v.vm_template)
  end

  # The Record type OSGymSandboxStatus.

  def write_TypeOsGymSandboxStatus(v)
    self.write_Optionalstring(v.phase)
    self.write_Optionalstring(v.runtime)
    self.write_Optionalbool(v.ready)
    self.write_Optionalstring(v.vm_name)
    self.write_Optionalstring(v.service)
    self.write_Optionalstring(v.message)
    self.write_Optionalstring(v.reset_issued_at)
    self.write_Optionalstring(v.reset_vmi_uid)
  end

  # The Record type OSGymSandboxTemplateSpec.

  def write_TypeOsGymSandboxTemplateSpec(v)
    self.write_TypeVmTemplate(v.vm_template)
  end

  # The Record type OSGymSandboxWarmPoolSpec.

  def write_TypeOsGymSandboxWarmPoolSpec(v)
    self.write_U32(v.replicas)
    self.write_TypeSandboxTemplateRef(v.sandbox_template_ref)
    self.write_OptionalTypeWarmPoolAutoscaling(v.autoscaling)
  end

  # The Record type OSGymSandboxWarmPoolStatus.

  def write_TypeOsGymSandboxWarmPoolStatus(v)
    self.write_Optionalu32(v.replicas)
    self.write_Optionalu32(v.ready_replicas)
    self.write_Optionalstring(v.selector)
  end

  # The Record type OSGymWorkspacePoolStatus.

  def write_TypeOsGymWorkspacePoolStatus(v)
    self.write_Optionalstring(v.phase)
    self.write_Optionalu32(v.total_count)
    self.write_Optionalu32(v.available_count)
    self.write_Optionalu32(v.claimed_count)
  end

  # The Record type OidcConfig.

  def write_TypeOidcConfig(v)
    self.write_String(v.credentials_secret)
    self.write_String(v.token_url)
    self.write_Optionalstring(v.aws_role_arn)
    self.write_Optionalstring(v.aws_region)
    self.write_Optionalu32(v.refresh_interval_seconds)
  end

  # The Record type PoolSpec.

  def write_TypePoolSpec(v)
    self.write_U32(v.replicas)
    self.write_TypePoolTemplate(v.template)
    self.write_OptionalTypeWarmPoolAutoscaling(v.autoscaling)
    self.write_OptionalSequenceTypeSandboxService(v.services)
  end

  # The Record type PoolTemplate.

  def write_TypePoolTemplate(v)
    self.write_OptionalTypeRuntimeKind(v.runtime)
    self.write_Optionalstring(v.runtime_class_name)
    self.write_OptionalMapStringString(v.node_selector)
    self.write_OptionalSequenceTypePreservedJson(v.tolerations)
    self.write_OptionalSequencestring(v.command)
    self.write_String(v.container_disk_image)
    self.write_Optionalstring(v.image_pull_secret)
    self.write_Optionalu32(v.cpu_cores)
    self.write_Optionalstring(v.memory)
    self.write_OptionalTypeFirmware(v.firmware)
    self.write_OptionalTypePreservedJson(v.probes)
    self.write_OptionalTypeOidcConfig(v.oidc)
  end

  # The Record type SandboxService.

  def write_TypeSandboxService(v)
    self.write_String(v.name)
    self.write_U16(v.target_port)
    self.write_OptionalTypeServiceProtocol(v.protocol)
  end

  # The Record type SandboxTemplateRef.

  def write_TypeSandboxTemplateRef(v)
    self.write_String(v.name)
  end

  # The Record type VmTemplate.

  def write_TypeVmTemplate(v)
    self.write_String(v.container_disk_image)
    self.write_OptionalSequencestring(v.command)
    self.write_OptionalTypeRuntimeKind(v.runtime)
    self.write_Optionalstring(v.runtime_class_name)
    self.write_OptionalMapStringString(v.node_selector)
    self.write_OptionalSequenceTypePreservedJson(v.tolerations)
    self.write_OptionalTypeImagePullPolicy(v.image_pull_policy)
    self.write_Optionalstring(v.image_pull_secret)
    self.write_Optionalu32(v.cpu_cores)
    self.write_Optionalstring(v.memory)
    self.write_OptionalTypeFirmware(v.firmware)
    self.write_OptionalTypePreservedJson(v.probes)
    self.write_OptionalSequenceTypeSandboxService(v.services)
    self.write_OptionalTypeOidcConfig(v.oidc)
  end

  # The Record type WarmPoolAutoscaling.

  def write_TypeWarmPoolAutoscaling(v)
    self.write_Optionalu32(v.min_pool_size)
    self.write_Optionalu32(v.initial_pool_size)
    self.write_Optionalu32(v.max_pool_size)
  end

  # The Enum type Firmware.

  def write_TypeFirmware(v)
    pack_into(4, 'l>', v)
 end


  # The Enum type ImagePullPolicy.

  def write_TypeImagePullPolicy(v)
    pack_into(4, 'l>', v)
 end




  # The Enum type RuntimeKind.

  def write_TypeRuntimeKind(v)
    pack_into(4, 'l>', v)
 end


  # The Enum type ServiceProtocol.

  def write_TypeServiceProtocol(v)
    pack_into(4, 'l>', v)
 end


  # The Optional<T> type for u32.

  def write_Optionalu32(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_U32(v)
    end
  end

  # The Optional<T> type for bool.

  def write_Optionalbool(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_Bool(v)
    end
  end

  # The Optional<T> type for string.

  def write_Optionalstring(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_String(v)
    end
  end

  # The Optional<T> type for TypePreservedJson.

  def write_OptionalTypePreservedJson(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypePreservedJson(v)
    end
  end

  # The Optional<T> type for TypeClaimLifecycle.

  def write_OptionalTypeClaimLifecycle(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeClaimLifecycle(v)
    end
  end

  # The Optional<T> type for TypeOSGymSandboxClaimSandbox.

  def write_OptionalTypeOsGymSandboxClaimSandbox(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeOsGymSandboxClaimSandbox(v)
    end
  end

  # The Optional<T> type for TypeOidcConfig.

  def write_OptionalTypeOidcConfig(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeOidcConfig(v)
    end
  end

  # The Optional<T> type for TypeWarmPoolAutoscaling.

  def write_OptionalTypeWarmPoolAutoscaling(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeWarmPoolAutoscaling(v)
    end
  end

  # The Optional<T> type for TypeFirmware.

  def write_OptionalTypeFirmware(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeFirmware(v)
    end
  end

  # The Optional<T> type for TypeImagePullPolicy.

  def write_OptionalTypeImagePullPolicy(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeImagePullPolicy(v)
    end
  end

  # The Optional<T> type for TypeRuntimeKind.

  def write_OptionalTypeRuntimeKind(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeRuntimeKind(v)
    end
  end

  # The Optional<T> type for TypeServiceProtocol.

  def write_OptionalTypeServiceProtocol(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeServiceProtocol(v)
    end
  end

  # The Optional<T> type for Sequencestring.

  def write_OptionalSequencestring(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_Sequencestring(v)
    end
  end

  # The Optional<T> type for SequenceTypePreservedJson.

  def write_OptionalSequenceTypePreservedJson(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_SequenceTypePreservedJson(v)
    end
  end

  # The Optional<T> type for SequenceTypeOSGymSandboxClaimCondition.

  def write_OptionalSequenceTypeOsGymSandboxClaimCondition(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_SequenceTypeOsGymSandboxClaimCondition(v)
    end
  end

  # The Optional<T> type for SequenceTypeSandboxService.

  def write_OptionalSequenceTypeSandboxService(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_SequenceTypeSandboxService(v)
    end
  end

  # The Optional<T> type for MapStringString.

  def write_OptionalMapStringString(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_MapStringString(v)
    end
  end

  # The Sequence<T> type for string.

  def write_Sequencestring(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_String(item)
    end
  end

  # The Sequence<T> type for TypePreservedJson.

  def write_SequenceTypePreservedJson(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_TypePreservedJson(item)
    end
  end

  # The Sequence<T> type for TypeOSGymSandboxClaimCondition.

  def write_SequenceTypeOsGymSandboxClaimCondition(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_TypeOsGymSandboxClaimCondition(item)
    end
  end

  # The Sequence<T> type for TypeSandboxService.

  def write_SequenceTypeSandboxService(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_TypeSandboxService(item)
    end
  end

  # The Map<T> type for string.

  def write_MapStringString(items)
    pack_into(4, 'l>', items.size)

    items.each do |k, v|
      write_String(k)
      self.write_String(v)
    end
  end

  private

  def reserve(num_bytes)
    if @rust_buf.len + num_bytes > @rust_buf.capacity
      @rust_buf = RustBuffer.reserve(@rust_buf, num_bytes)
    end

    yield

    @rust_buf.len += num_bytes
  end

  def pack_into(size, format, value)
    reserve(size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, [value].pack(format).bytes
    end
  end
end

private_constant :RustBufferBuilder

  # Error definitions
  class RustCallStatus < FFI::Struct
  layout :code,    :int8,
         :error_buf, RustBuffer

  def code
    self[:code]
  end

  def error_buf
    self[:error_buf]
  end

  def to_s
    "RustCallStatus(code=#{self[:code]})"
  end
end

# These match the values from the uniffi::rustcalls module
CALL_SUCCESS = 0
CALL_ERROR = 1
CALL_PANIC = 2






module JsonValueError
  class Invalid < StandardError
    def initialize(reason)
        @reason = reason
        super()
      end

    attr_reader :reason


    def to_s
     "#{self.class.name}(reason=#{@reason.inspect})"
    end
  end

end


# Map error modules to the RustBuffer method name that reads them
ERROR_MODULE_TO_READER_METHOD = {





  JsonValueError => :readTypeJsonValueError,

}

private_constant :ERROR_MODULE_TO_READER_METHOD, :CALL_SUCCESS, :CALL_ERROR, :CALL_PANIC,
                 :RustCallStatus

def self.consume_buffer_into_error(error_module, rust_buffer)
  rust_buffer.consumeWithStream do |stream|
    reader_method = ERROR_MODULE_TO_READER_METHOD[error_module]
    return stream.send(reader_method)
  end
end

class InternalError < StandardError
end

def self.rust_call(fn_name, *args)
  # Call a rust function
  rust_call_with_error(nil, fn_name, *args)
end

def self.rust_call_with_error(error_module, fn_name, *args)
  # Call a rust function and handle errors
  #
  # Use this when the rust function returns a Result<>.  error_module must be the error_module that corresponds to that Result.


  # Note: RustCallStatus.new zeroes out the struct, which is exactly what we
  # want to pass to Rust (code=0, error_buf=RustBuffer(len=0, capacity=0,
  # data=NULL))
  status = RustCallStatus.new
  args << status

  result = UniFFILib.public_send(fn_name, *args)

  case status.code
  when CALL_SUCCESS
    result
  when CALL_ERROR
    if error_module.nil?
      status.error_buf.free
      raise InternalError, "CALL_ERROR with no error_module set"
    else
      raise consume_buffer_into_error(error_module, status.error_buf)
    end
  when CALL_PANIC
    # When the rust code sees a panic, it tries to construct a RustBuffer
    # with the message.  But if that code panics, then it just sends back
    # an empty buffer.
    if status.error_buf.len > 0
      raise InternalError, status.error_buf.consumeIntoString()
    else
      raise InternalError, "Rust panic"
    end
  else
    raise InternalError, "Unknown call status: #{status.code}"
  end
end

private_class_method :consume_buffer_into_error

  # This is how we find and load the dynamic library provided by the component.
# For now we just look it up by name.
module UniFFILib
  extend FFI::Library


  ffi_lib 'cyclops_sdk'


  attach_function :uniffi_cyclops_sdk_schema_fn_clone_preservedjson,
    [:uint64, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_cyclops_sdk_schema_fn_free_preservedjson,
    [:uint64, RustCallStatus.by_ref],
    :void
  attach_function :uniffi_cyclops_sdk_schema_fn_constructor_preservedjson_from_json,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_cyclops_sdk_schema_fn_method_preservedjson_to_json,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_cyclops_sdk_schema_fn_method_poolspec_uniffi_trait_eq_eq,
    [RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    :int8
  attach_function :uniffi_cyclops_sdk_schema_fn_method_poolspec_uniffi_trait_eq_ne,
    [RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    :int8
  attach_function :uniffi_cyclops_sdk_schema_fn_method_poolspec_uniffi_trait_hash,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :uint64
  attach_function :ffi_cyclops_sdk_schema_rustbuffer_alloc,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_cyclops_sdk_schema_rustbuffer_from_bytes,
    [ForeignBytes, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_cyclops_sdk_schema_rustbuffer_free,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :void
  attach_function :ffi_cyclops_sdk_schema_rustbuffer_reserve,
    [RustBuffer.by_value, :uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_cyclops_sdk_schema_checksum_method_preservedjson_to_json,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_cyclops_sdk_schema_checksum_constructor_preservedjson_from_json,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :ffi_cyclops_sdk_schema_uniffi_contract_version,
    [RustCallStatus.by_ref],
    :uint32

end

  # Public interface members begin here.





class Firmware
  BIOS = 1
  EFI = 2

end






class ImagePullPolicy
  ALWAYS = 1
  IF_NOT_PRESENT = 2
  NEVER = 3

end






class RuntimeKind
  KUBEVIRT = 1
  MACOS = 2
  GVISOR = 3

end






class ServiceProtocol
  TCP = 1
  UDP = 2

end




  # Record type ClaimLifecycle
class ClaimLifecycle
  attr_reader :shutdown_time, :shutdown_policy, :auto_renew

  def initialize(shutdown_time:, shutdown_policy:, auto_renew:)
    @shutdown_time = shutdown_time
    @shutdown_policy = shutdown_policy
    @auto_renew = auto_renew
  end

  def ==(other)
    if @shutdown_time != other.shutdown_time
      return false
    end
    if @shutdown_policy != other.shutdown_policy
      return false
    end
    if @auto_renew != other.auto_renew
      return false
    end

    true
  end
end

  # Record type ClaimSpec
class ClaimSpec
  attr_reader :sandbox_template_ref, :warmpool, :bind_deadline, :lifecycle

  def initialize(sandbox_template_ref:, warmpool:, bind_deadline:, lifecycle:)
    @sandbox_template_ref = sandbox_template_ref
    @warmpool = warmpool
    @bind_deadline = bind_deadline
    @lifecycle = lifecycle
  end

  def ==(other)
    if @sandbox_template_ref != other.sandbox_template_ref
      return false
    end
    if @warmpool != other.warmpool
      return false
    end
    if @bind_deadline != other.bind_deadline
      return false
    end
    if @lifecycle != other.lifecycle
      return false
    end

    true
  end
end

  # Record type OSGymSandboxClaimCondition
class OsGymSandboxClaimCondition
  attr_reader :type, :status, :reason, :message, :last_transition_time

  def initialize(type:, status:, reason:, message:, last_transition_time:)
    @type = type
    @status = status
    @reason = reason
    @message = message
    @last_transition_time = last_transition_time
  end

  def ==(other)
    if @type != other.type
      return false
    end
    if @status != other.status
      return false
    end
    if @reason != other.reason
      return false
    end
    if @message != other.message
      return false
    end
    if @last_transition_time != other.last_transition_time
      return false
    end

    true
  end
end

  # Record type OSGymSandboxClaimSandbox
class OsGymSandboxClaimSandbox
  attr_reader :name, :service

  def initialize(name:, service:)
    @name = name
    @service = service
  end

  def ==(other)
    if @name != other.name
      return false
    end
    if @service != other.service
      return false
    end

    true
  end
end

  # Record type OSGymSandboxClaimStatus
class OsGymSandboxClaimStatus
  attr_reader :phase, :conditions, :sandbox

  def initialize(phase:, conditions:, sandbox:)
    @phase = phase
    @conditions = conditions
    @sandbox = sandbox
  end

  def ==(other)
    if @phase != other.phase
      return false
    end
    if @conditions != other.conditions
      return false
    end
    if @sandbox != other.sandbox
      return false
    end

    true
  end
end

  # Record type OidcConfig
class OidcConfig
  attr_reader :credentials_secret, :token_url, :aws_role_arn, :aws_region, :refresh_interval_seconds

  def initialize(credentials_secret:, token_url:, aws_role_arn:, aws_region:, refresh_interval_seconds:)
    @credentials_secret = credentials_secret
    @token_url = token_url
    @aws_role_arn = aws_role_arn
    @aws_region = aws_region
    @refresh_interval_seconds = refresh_interval_seconds
  end

  def ==(other)
    if @credentials_secret != other.credentials_secret
      return false
    end
    if @token_url != other.token_url
      return false
    end
    if @aws_role_arn != other.aws_role_arn
      return false
    end
    if @aws_region != other.aws_region
      return false
    end
    if @refresh_interval_seconds != other.refresh_interval_seconds
      return false
    end

    true
  end
end

  # Record type SandboxService
class SandboxService
  attr_reader :name, :target_port, :protocol

  def initialize(name:, target_port:, protocol:)
    @name = name
    @target_port = target_port
    @protocol = protocol
  end

  def ==(other)
    if @name != other.name
      return false
    end
    if @target_port != other.target_port
      return false
    end
    if @protocol != other.protocol
      return false
    end

    true
  end
end

  # Record type SandboxTemplateRef
class SandboxTemplateRef
  attr_reader :name

  def initialize(name:)
    @name = name
  end

  def ==(other)
    if @name != other.name
      return false
    end

    true
  end
end

  # Record type VmTemplate
class VmTemplate
  attr_reader :container_disk_image, :command, :runtime, :runtime_class_name, :node_selector, :tolerations, :image_pull_policy, :image_pull_secret, :cpu_cores, :memory, :firmware, :probes, :services, :oidc

  def initialize(container_disk_image:, command:, runtime:, runtime_class_name:, node_selector:, tolerations:, image_pull_policy:, image_pull_secret:, cpu_cores:, memory:, firmware:, probes:, services:, oidc:)
    @container_disk_image = container_disk_image
    @command = command
    @runtime = runtime
    @runtime_class_name = runtime_class_name
    @node_selector = node_selector
    @tolerations = tolerations
    @image_pull_policy = image_pull_policy
    @image_pull_secret = image_pull_secret
    @cpu_cores = cpu_cores
    @memory = memory
    @firmware = firmware
    @probes = probes
    @services = services
    @oidc = oidc
  end

  def ==(other)
    if @container_disk_image != other.container_disk_image
      return false
    end
    if @command != other.command
      return false
    end
    if @runtime != other.runtime
      return false
    end
    if @runtime_class_name != other.runtime_class_name
      return false
    end
    if @node_selector != other.node_selector
      return false
    end
    if @tolerations != other.tolerations
      return false
    end
    if @image_pull_policy != other.image_pull_policy
      return false
    end
    if @image_pull_secret != other.image_pull_secret
      return false
    end
    if @cpu_cores != other.cpu_cores
      return false
    end
    if @memory != other.memory
      return false
    end
    if @firmware != other.firmware
      return false
    end
    if @probes != other.probes
      return false
    end
    if @services != other.services
      return false
    end
    if @oidc != other.oidc
      return false
    end

    true
  end
end

  # Record type OSGymSandboxSpec
class OsGymSandboxSpec
  attr_reader :vm_template

  def initialize(vm_template:)
    @vm_template = vm_template
  end

  def ==(other)
    if @vm_template != other.vm_template
      return false
    end

    true
  end
end

  # Record type OSGymSandboxStatus
class OsGymSandboxStatus
  attr_reader :phase, :runtime, :ready, :vm_name, :service, :message, :reset_issued_at, :reset_vmi_uid

  def initialize(phase:, runtime:, ready:, vm_name:, service:, message:, reset_issued_at:, reset_vmi_uid:)
    @phase = phase
    @runtime = runtime
    @ready = ready
    @vm_name = vm_name
    @service = service
    @message = message
    @reset_issued_at = reset_issued_at
    @reset_vmi_uid = reset_vmi_uid
  end

  def ==(other)
    if @phase != other.phase
      return false
    end
    if @runtime != other.runtime
      return false
    end
    if @ready != other.ready
      return false
    end
    if @vm_name != other.vm_name
      return false
    end
    if @service != other.service
      return false
    end
    if @message != other.message
      return false
    end
    if @reset_issued_at != other.reset_issued_at
      return false
    end
    if @reset_vmi_uid != other.reset_vmi_uid
      return false
    end

    true
  end
end

  # Record type OSGymSandboxTemplateSpec
class OsGymSandboxTemplateSpec
  attr_reader :vm_template

  def initialize(vm_template:)
    @vm_template = vm_template
  end

  def ==(other)
    if @vm_template != other.vm_template
      return false
    end

    true
  end
end

  # Record type OSGymSandboxWarmPoolSpec
class OsGymSandboxWarmPoolSpec
  attr_reader :replicas, :sandbox_template_ref, :autoscaling

  def initialize(replicas:, sandbox_template_ref:, autoscaling:)
    @replicas = replicas
    @sandbox_template_ref = sandbox_template_ref
    @autoscaling = autoscaling
  end

  def ==(other)
    if @replicas != other.replicas
      return false
    end
    if @sandbox_template_ref != other.sandbox_template_ref
      return false
    end
    if @autoscaling != other.autoscaling
      return false
    end

    true
  end
end

  # Record type OSGymSandboxWarmPoolStatus
class OsGymSandboxWarmPoolStatus
  attr_reader :replicas, :ready_replicas, :selector

  def initialize(replicas:, ready_replicas:, selector:)
    @replicas = replicas
    @ready_replicas = ready_replicas
    @selector = selector
  end

  def ==(other)
    if @replicas != other.replicas
      return false
    end
    if @ready_replicas != other.ready_replicas
      return false
    end
    if @selector != other.selector
      return false
    end

    true
  end
end

  # Record type WarmPoolAutoscaling
class WarmPoolAutoscaling
  attr_reader :min_pool_size, :initial_pool_size, :max_pool_size

  def initialize(min_pool_size:, initial_pool_size:, max_pool_size:)
    @min_pool_size = min_pool_size
    @initial_pool_size = initial_pool_size
    @max_pool_size = max_pool_size
  end

  def ==(other)
    if @min_pool_size != other.min_pool_size
      return false
    end
    if @initial_pool_size != other.initial_pool_size
      return false
    end
    if @max_pool_size != other.max_pool_size
      return false
    end

    true
  end
end

  # Record type OSGymWorkspacePoolStatus
class OsGymWorkspacePoolStatus
  attr_reader :phase, :total_count, :available_count, :claimed_count

  def initialize(phase:, total_count:, available_count:, claimed_count:)
    @phase = phase
    @total_count = total_count
    @available_count = available_count
    @claimed_count = claimed_count
  end

  def ==(other)
    if @phase != other.phase
      return false
    end
    if @total_count != other.total_count
      return false
    end
    if @available_count != other.available_count
      return false
    end
    if @claimed_count != other.claimed_count
      return false
    end

    true
  end
end

  # Record type PoolSpec
class PoolSpec
  attr_reader :replicas, :template, :autoscaling, :services

  def initialize(replicas:, template:, autoscaling:, services:)
    @replicas = replicas
    @template = template
    @autoscaling = autoscaling
    @services = services
  end

  def ==(other)
    if @replicas != other.replicas
      return false
    end
    if @template != other.template
      return false
    end
    if @autoscaling != other.autoscaling
      return false
    end
    if @services != other.services
      return false
    end

    true
  end
end

  # Record type PoolTemplate
class PoolTemplate
  attr_reader :runtime, :runtime_class_name, :node_selector, :tolerations, :command, :container_disk_image, :image_pull_secret, :cpu_cores, :memory, :firmware, :probes, :oidc

  def initialize(runtime:, runtime_class_name:, node_selector:, tolerations:, command:, container_disk_image:, image_pull_secret:, cpu_cores:, memory:, firmware:, probes:, oidc:)
    @runtime = runtime
    @runtime_class_name = runtime_class_name
    @node_selector = node_selector
    @tolerations = tolerations
    @command = command
    @container_disk_image = container_disk_image
    @image_pull_secret = image_pull_secret
    @cpu_cores = cpu_cores
    @memory = memory
    @firmware = firmware
    @probes = probes
    @oidc = oidc
  end

  def ==(other)
    if @runtime != other.runtime
      return false
    end
    if @runtime_class_name != other.runtime_class_name
      return false
    end
    if @node_selector != other.node_selector
      return false
    end
    if @tolerations != other.tolerations
      return false
    end
    if @command != other.command
      return false
    end
    if @container_disk_image != other.container_disk_image
      return false
    end
    if @image_pull_secret != other.image_pull_secret
      return false
    end
    if @cpu_cores != other.cpu_cores
      return false
    end
    if @memory != other.memory
      return false
    end
    if @firmware != other.firmware
      return false
    end
    if @probes != other.probes
      return false
    end
    if @oidc != other.oidc
      return false
    end

    true
  end
end





  class PreservedJson

  # A private helper for initializing instances of the class from a raw handle,
  # bypassing any initialization logic and ensuring they are GC'd properly.
  def self.uniffi_allocate(handle)
    inst = allocate
    inst.instance_variable_set :@handle, handle
    ObjectSpace.define_finalizer(inst, uniffi_define_finalizer_by_handle(handle, inst.object_id))
    return inst
  end

  # A private helper for registering an object finalizer.
  # N.B. it's important that this does not capture a reference
  # to the actual instance, only its underlying handle.
  def self.uniffi_define_finalizer_by_handle(handle, object_id)
    Proc.new do |_id|
      CyclopsSdkSchema.rust_call(
        :uniffi_cyclops_sdk_schema_fn_free_preservedjson,
        handle
      )
    end
  end

  # A private helper for lowering instances into a raw handle.
  # This does an explicit typecheck, because accidentally lowering a different type of
  # object in a place where this type is expected, could lead to memory unsafety.
  def self.uniffi_check_lower(inst)
    if not inst.is_a? self
      raise TypeError.new "Expected a PreservedJson instance, got #{inst}"
    end
  end

  def uniffi_clone_handle()
    return CyclopsSdkSchema.rust_call(
      :uniffi_cyclops_sdk_schema_fn_clone_preservedjson,
      @handle
    )
  end

  def self.uniffi_lower(inst)
    return inst.uniffi_clone_handle()
  end

  def self.from_json(value)
        value = CyclopsSdkSchema::uniffi_utf8(value)

    # Call the (fallible) function before creating any half-baked object instances.
    # Lightly yucky way to bypass the usual "initialize" logic
    # and just create a new instance with the required handle.
    return uniffi_allocate(CyclopsSdkSchema.rust_call_with_error(JsonValueError,:uniffi_cyclops_sdk_schema_fn_constructor_preservedjson_from_json,RustBuffer.allocFromString(value)))
  end


  def to_json()
    result = CyclopsSdkSchema.rust_call(:uniffi_cyclops_sdk_schema_fn_method_preservedjson_to_json,uniffi_clone_handle(),)
    return result.consumeIntoString
  end

end

end
