name: Build and Publish CUA XFCE Container

on:
  push:
    branches:
      - main
    tags:
      - "docker-xfce-v*.*.*"
    paths:
      - "libs/xfce/**"
      - ".github/workflows/docker-publish-xfce.yml"
      - ".github/workflows/docker-reusable-publish.yml"
  pull_request:
    paths:
      - "libs/xfce/**"
      - ".github/workflows/docker-publish-xfce.yml"
      - ".github/workflows/docker-reusable-publish.yml"

jobs:
  publish:
    uses: ./.github/workflows/docker-reusable-publish.yml
    with:
      image_name: cua-xfce
      context_dir: libs/xfce
      dockerfile_path: Dockerfile
      tag_prefix: docker-xfce-v
      docker_hub_org: trycua
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
