name: Reusable Python Package Publishing Workflow

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      package_dir:
        required: true
        type: string
      version:
        required: true
        type: string
      is_lume_package:
        required: false
        type: boolean
        default: false
      base_package_name:
        required: false
        type: string
        default: ""
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Update version
        working-directory: ${{ inputs.package_dir }}
        run: |
          # Update version in pyproject.toml
          VERSION="${{ inputs.version }}"
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          else
            sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          fi
          echo "Updated version to $VERSION"
          cat pyproject.toml | grep version
      
      - name: Build package
        working-directory: ${{ inputs.package_dir }}
        run: python -m build
      
      - name: Publish to PyPI
        working-directory: ${{ inputs.package_dir }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ inputs.package_name }}-v${{ inputs.version }}"
          name: "${{ inputs.package_name }} v${{ inputs.version }}"
          draft: false
          prerelease: false
          generate_release_notes: true 