name: Test valididation script

on:
  pull_request:
    paths:
      - '.github/scripts/**'
      - '.github/workflows/test-scripts.yml'
  push:
    branches:
      - main
    paths:
      - '.github/scripts/**'
      - '.github/workflows/test-scripts.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest toml

      - name: Run tests
        run: |
          cd .github/scripts
          pytest tests/ -v
